// pages/start/data.js
// === 游戏静态数据配置表：天赋与灵根 (200天赋 + 60灵根 满血扩展版) ===

const MASTER_TALENTS = [
  // ---------------- 【凡品 - 灰色 (40个) - 填池子的炮灰与负面状态】 ----------------
  { t_id: "T_001", name: "平平无奇", rarity: "Gray", desc: "没有任何特点，全属性+1。", weight: 3000, attr: { wealth: 1, body: 1, talent: 1, luck: 1, insight: 1 } },
  { t_id: "T_002", name: "先天漏体", rarity: "Gray", desc: "体虚气短，寿命极短。体魄-5。", weight: 1500, attr: { wealth: 0, body: -5, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_003", name: "家徒四壁", rarity: "Gray", desc: "穷得叮当响。家境-5。", weight: 1500, attr: { wealth: -5, body: 0, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_004", name: "榆木脑袋", rarity: "Gray", desc: "别人悟道你打盹。悟性-5。", weight: 1500, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: -5 } },
  { t_id: "T_005", name: "厄运缠身", rarity: "Gray", desc: "走平路都会摔跤。福源-5。", weight: 1500, attr: { wealth: 0, body: 0, talent: 0, luck: -5, insight: 0 } },
  { t_id: "T_006", name: "经脉阻塞", rarity: "Gray", desc: "修炼比蜗牛还慢。根骨-5。", weight: 1500, attr: { wealth: 0, body: 0, talent: -5, luck: 0, insight: 0 } },
  { t_id: "T_007", name: "弱不禁风", rarity: "Gray", desc: "一阵风就能吹倒。体魄-3，家境+1。", weight: 1250, attr: { wealth: 1, body: -3, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_008", name: "面目可憎", rarity: "Gray", desc: "容易被人找茬。福源-3，体魄+1。", weight: 1250, attr: { wealth: 0, body: 1, talent: 0, luck: -3, insight: 0 } },
  { t_id: "T_009", name: "散财童子", rarity: "Gray", desc: "有钱也留不住。家境-8，福源+2。", weight: 1250, attr: { wealth: -8, body: 0, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_010", name: "天生愚钝", rarity: "Gray", desc: "看功法像看天书。悟性-8，体魄+2。", weight: 1250, attr: { wealth: 0, body: 2, talent: 0, luck: 0, insight: -8 } },
  { t_id: "T_011", name: "命犯孤星", rarity: "Gray", desc: "克死亲友。福源-8，根骨+2。", weight: 1250, attr: { wealth: 0, body: 0, talent: 2, luck: -8, insight: 0 } },
  { t_id: "T_012", name: "霉运当头", rarity: "Gray", desc: "喝水塞牙缝。福源-10。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -10, insight: 0 } },
  { t_id: "T_013", name: "碌碌无为", rarity: "Gray", desc: "干啥啥不行。全属性-1。", weight: 1500, attr: { wealth: -1, body: -1, talent: -1, luck: -1, insight: -1 } },
  { t_id: "T_014", name: "气血亏虚", rarity: "Gray", desc: "早衰之象。体魄-8。", weight: 1000, attr: { wealth: 0, body: -8, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_015", name: "冥顽不灵", rarity: "Gray", desc: "死脑筋。悟性-10。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: -10 } },
  { t_id: "T_016", name: "根骨平庸", rarity: "Gray", desc: "毫无仙缘。根骨-10。", weight: 1000, attr: { wealth: 0, body: 0, talent: -10, luck: 0, insight: 0 } },
  { t_id: "T_017", name: "囊中羞涩", rarity: "Gray", desc: "出门连个铜板都没有。家境-10。", weight: 1000, attr: { wealth: -10, body: 0, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_018", name: "六根不净", rarity: "Gray", desc: "杂念太多。悟性-3，福源-3。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -3, insight: -3 } },
  { t_id: "T_019", name: "胆小如鼠", rarity: "Gray", desc: "历练经常落荒而逃。体魄-2，福源+1。", weight: 1200, attr: { wealth: 0, body: -2, talent: 0, luck: 1, insight: 0 } },
  { t_id: "T_020", name: "凡夫俗子", rarity: "Gray", desc: "你只是个路人甲。全属性-10。", weight: 500, attr: { wealth: -10, body: -10, talent: -10, luck: -10, insight: -10 } },
  // -- 新增灰色天赋 --
  { t_id: "T_021", name: "嗜睡症", rarity: "Gray", desc: "一天要睡十个时辰。悟性-3，体魄+1。", weight: 1000, attr: { wealth: 0, body: 1, talent: 0, luck: 0, insight: -3 } },
  { t_id: "T_022", name: "贪吃鬼", rarity: "Gray", desc: "恩格尔系数极高。体魄+2，家境-3。", weight: 1000, attr: { wealth: -3, body: 2, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_023", name: "旱鸭子", rarity: "Gray", desc: "极度怕水。体魄-2，水系功法绝缘。", weight: 1000, attr: { wealth: 0, body: -2, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_024", name: "恐高症", rarity: "Gray", desc: "御剑飞行经常腿软。悟性-2，福源-1。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -1, insight: -2 } },
  { t_id: "T_025", name: "先天盲目", rarity: "Gray", desc: "看不见世界，但心眼略开。悟性+3，体魄-8。", weight: 700, attr: { wealth: 0, body: -8, talent: 0, luck: 0, insight: 3 } },
  { t_id: "T_026", name: "先天聋哑", rarity: "Gray", desc: "无法言语交流。悟性-5，福源-3。", weight: 700, attr: { wealth: 0, body: 0, talent: 0, luck: -3, insight: -5 } },
  { t_id: "T_027", name: "天生跛脚", rarity: "Gray", desc: "行动不便。体魄-6，根骨-2。", weight: 700, attr: { wealth: 0, body: -6, talent: -2, luck: 0, insight: 0 } },
  { t_id: "T_028", name: "性格孤僻", rarity: "Gray", desc: "没人愿意和你组队。福源-4，悟性+2。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -4, insight: 2 } },
  { t_id: "T_029", name: "多嘴多舌", rarity: "Gray", desc: "容易祸从口出。福源-5。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -5, insight: 0 } },
  { t_id: "T_030", name: "严重洁癖", rarity: "Gray", desc: "荒郊野岭没法修炼。体魄-2，悟性-2。", weight: 1000, attr: { wealth: 0, body: -2, talent: 0, luck: 0, insight: -2 } },
  { t_id: "T_031", name: "暴躁易怒", rarity: "Gray", desc: "走火入魔常客。悟性-6，体魄+2。", weight: 1000, attr: { wealth: 0, body: 2, talent: 0, luck: 0, insight: -6 } },
  { t_id: "T_032", name: "生性懦弱", rarity: "Gray", desc: "斗法总是先逃跑。体魄-4，福源+1。", weight: 1000, attr: { wealth: 0, body: -4, talent: 0, luck: 1, insight: 0 } },
  { t_id: "T_033", name: "极度懒惰", rarity: "Gray", desc: "能躺着绝不坐着。根骨-6，悟性-2。", weight: 1000, attr: { wealth: 0, body: 0, talent: -6, luck: 0, insight: -2 } },
  { t_id: "T_034", name: "视财如命", rarity: "Gray", desc: "为了灵石不要命。家境+3，福源-6。", weight: 1000, attr: { wealth: 3, body: 0, talent: 0, luck: -6, insight: 0 } },
  { t_id: "T_035", name: "沉迷酒色", rarity: "Gray", desc: "掏空了身体。体魄-6，悟性-3。", weight: 1000, attr: { wealth: 0, body: -6, talent: 0, luck: 0, insight: -3 } },
  { t_id: "T_036", name: "十赌九输", rarity: "Gray", desc: "把裤衩都输光了。家境-8，福源-4。", weight: 700, attr: { wealth: -8, body: 0, talent: 0, luck: -4, insight: 0 } },
  { t_id: "T_037", name: "重度路痴", rarity: "Gray", desc: "历练永远找不到宝藏。福源-8。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: -8, insight: 0 } },
  { t_id: "T_038", name: "晕血症", rarity: "Gray", desc: "见血就倒。体魄-4，根骨-2。", weight: 1000, attr: { wealth: 0, body: -4, talent: -2, luck: 0, insight: 0 } },
  { t_id: "T_039", name: "天煞孤星", rarity: "Gray", desc: "周围人全死光，你也倒霉。福源-15。", weight: 500, attr: { wealth: 0, body: 0, talent: 0, luck: -15, insight: 0 } },
  { t_id: "T_040", name: "药罐子", rarity: "Gray", desc: "从小泡在药里续命。体魄-10，悟性+2。", weight: 700, attr: { wealth: 0, body: -10, talent: 0, luck: 0, insight: 2 } },

  // ---------------- 【灵品 - 绿色 (60个) - 基础正向加成与凡间职业】 ----------------
  { t_id: "T_101", name: "村口恶霸", rarity: "Green", desc: "打架是把好手。体魄+3，福源-1。", weight: 1000, attr: { wealth: 0, body: 3, talent: 0, luck: -1, insight: 0 } },
  { t_id: "T_102", name: "小有家产", rarity: "Green", desc: "比上不足比下有余。家境+3。", weight: 1000, attr: { wealth: 3, body: 0, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_103", name: "耳聪目明", rarity: "Green", desc: "学东西很快。悟性+3。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: 3 } },
  { t_id: "T_104", name: "身强体壮", rarity: "Green", desc: "不容易生病。体魄+3。", weight: 1000, attr: { wealth: 0, body: 3, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_105", name: "踩狗屎运", rarity: "Green", desc: "运气偶尔不错。福源+3。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: 3, insight: 0 } },
  { t_id: "T_106", name: "气血充盈", rarity: "Green", desc: "生命力顽强。体魄+4，悟性-1。", weight: 900, attr: { wealth: 0, body: 4, talent: 0, luck: 0, insight: -1 } },
  { t_id: "T_107", name: "粗通拳脚", rarity: "Green", desc: "会点三脚猫功夫。体魄+2，根骨+2。", weight: 900, attr: { wealth: 0, body: 2, talent: 2, luck: 0, insight: 0 } },
  { t_id: "T_108", name: "略有薄产", rarity: "Green", desc: "祖上留了点地。家境+4，福源-1。", weight: 900, attr: { wealth: 4, body: 0, talent: 0, luck: -1, insight: 0 } },
  { t_id: "T_109", name: "过目成诵", rarity: "Green", desc: "背书很快。悟性+4，体魄-1。", weight: 900, attr: { wealth: 0, body: -1, talent: 0, luck: 0, insight: 4 } },
  { t_id: "T_110", name: "筋骨硬朗", rarity: "Green", desc: "非常耐揍。体魄+5，福源-2。", weight: 700, attr: { wealth: 0, body: 5, talent: 0, luck: -2, insight: 0 } },
  { t_id: "T_111", name: "吉星高照", rarity: "Green", desc: "总能逢凶化吉。福源+5，家境-2。", weight: 700, attr: { wealth: -2, body: 0, talent: 0, luck: 5, insight: 0 } },
  { t_id: "T_112", name: "乡绅之子", rarity: "Green", desc: "吃穿不愁。家境+5，根骨-2。", weight: 700, attr: { wealth: 5, body: 0, talent: -2, luck: 0, insight: 0 } },
  { t_id: "T_113", name: "精神抖擞", rarity: "Green", desc: "熬夜修仙不困。悟性+2，体魄+2。", weight: 900, attr: { wealth: 0, body: 2, talent: 0, luck: 0, insight: 2 } },
  { t_id: "T_114", name: "敏而好学", rarity: "Green", desc: "喜欢提问。悟性+5，福源-2。", weight: 700, attr: { wealth: 0, body: 0, talent: 0, luck: -2, insight: 5 } },
  { t_id: "T_115", name: "寻宝雷达", rarity: "Green", desc: "对灵石很敏感。福源+3, 家境+2。", weight: 800, attr: { wealth: 2, body: 0, talent: 0, luck: 3, insight: 0 } },
  { t_id: "T_116", name: "铁胃", rarity: "Green", desc: "吃毒药都没事。体魄+4。", weight: 900, attr: { wealth: 0, body: 4, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_117", name: "健步如飞", rarity: "Green", desc: "跑路第一名。福源+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 4, insight: 0 } },
  { t_id: "T_118", name: "容光焕发", rarity: "Green", desc: "长得挺精神。福源+2，悟性+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 2, insight: 2 } },
  { t_id: "T_119", name: "左右逢源", rarity: "Green", desc: "人缘好。家境+2, 福源+2。", weight: 900, attr: { wealth: 2, body: 0, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_120", name: "泥瓦匠", rarity: "Green", desc: "修洞府一把好手。体魄+2, 家境+2。", weight: 900, attr: { wealth: 2, body: 2, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_121", name: "捕猎好手", rarity: "Green", desc: "野外生存强。体魄+3, 福源+1。", weight: 900, attr: { wealth: 0, body: 3, talent: 0, luck: 1, insight: 0 } },
  { t_id: "T_122", name: "识文断字", rarity: "Green", desc: "不至于当文盲。悟性+3, 家境+1。", weight: 900, attr: { wealth: 1, body: 0, talent: 0, luck: 0, insight: 3 } },
  { t_id: "T_123", name: "算盘打得精", rarity: "Green", desc: "从不吃亏。家境+4。", weight: 900, attr: { wealth: 4, body: 0, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_124", name: "街头霸王", rarity: "Green", desc: "实战经验丰富。体魄+5, 悟性-1。", weight: 800, attr: { wealth: 0, body: 5, talent: 0, luck: 0, insight: -1 } },
  { t_id: "T_125", name: "跑得快", rarity: "Green", desc: "逃跑率上升。福源+5, 体魄-1。", weight: 800, attr: { wealth: 0, body: -1, talent: 0, luck: 5, insight: 0 } },
  { t_id: "T_126", name: "闭气功", rarity: "Green", desc: "装死神技。体魄+2, 根骨+2。", weight: 900, attr: { wealth: 0, body: 2, talent: 2, luck: 0, insight: 0 } },
  { t_id: "T_127", name: "铁头功", rarity: "Green", desc: "头铁。体魄+6, 悟性-3。", weight: 700, attr: { wealth: 0, body: 6, talent: 0, luck: 0, insight: -3 } },
  { t_id: "T_128", name: "鹰眼", rarity: "Green", desc: "洞察力强。悟性+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: 4 } },
  { t_id: "T_129", name: "狼鼻", rarity: "Green", desc: "嗅觉灵敏。福源+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 4, insight: 0 } },
  { t_id: "T_130", name: "鱼跃", rarity: "Green", desc: "身法灵动。根骨+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 4, luck: 0, insight: 0 } },
  // -- 新增绿色天赋 --
  { t_id: "T_131", name: "采药童子", rarity: "Green", desc: "懂些草药知识。福源+3，悟性+1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: 3, insight: 1 } },
  { t_id: "T_132", name: "铁匠学徒", rarity: "Green", desc: "打铁锻炼了肌肉。体魄+4，家境+1。", weight: 1800, attr: { wealth: 1, body: 4, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_133", name: "渔夫出身", rarity: "Green", desc: "深谙水性。体魄+2，福源+2。", weight: 1800, attr: { wealth: 0, body: 2, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_134", name: "屠户人家", rarity: "Green", desc: "杀气略重。体魄+3，悟性-1，根骨+2。", weight: 1800, attr: { wealth: 0, body: 3, talent: 2, luck: 0, insight: -1 } },
  { t_id: "T_135", name: "酒楼厨子", rarity: "Green", desc: "把自己吃得很壮。体魄+4，家境+1。", weight: 1800, attr: { wealth: 1, body: 4, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_136", name: "落第书生", rarity: "Green", desc: "虽然没考上，但书没白读。悟性+5，体魄-2。", weight: 1800, attr: { wealth: 0, body: -2, talent: 0, luck: 0, insight: 5 } },
  { t_id: "T_137", name: "街头画师", rarity: "Green", desc: "对符文有初步美感。悟性+3，家境+1。", weight: 1800, attr: { wealth: 1, body: 0, talent: 0, luck: 0, insight: 3 } },
  { t_id: "T_138", name: "勾栏琴师", rarity: "Green", desc: "懂音律之妙。悟性+4，福源+1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: 1, insight: 4 } },
  { t_id: "T_139", name: "民间棋手", rarity: "Green", desc: "推演能力尚可。悟性+5，福源-1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: -1, insight: 5 } },
  { t_id: "T_140", name: "能工巧匠", rarity: "Green", desc: "手脚麻利。根骨+3，家境+1。", weight: 1800, attr: { wealth: 1, body: 0, talent: 3, luck: 0, insight: 0 } },
  { t_id: "T_141", name: "客栈跑堂", rarity: "Green", desc: "察言观色。福源+3，悟性+1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: 3, insight: 1 } },
  { t_id: "T_142", name: "商铺账房", rarity: "Green", desc: "对数字敏感。家境+3，悟性+2。", weight: 1800, attr: { wealth: 3, body: 0, talent: 0, luck: 0, insight: 2 } },
  { t_id: "T_143", name: "深山樵夫", rarity: "Green", desc: "每天砍树，臂力过人。体魄+4，福源+1。", weight: 1800, attr: { wealth: 0, body: 4, talent: 0, luck: 1, insight: 0 } },
  { t_id: "T_144", name: "打更人", rarity: "Green", desc: "习惯了熬夜。体魄+2，悟性+2。", weight: 1800, attr: { wealth: 0, body: 2, talent: 0, luck: 0, insight: 2 } },
  { t_id: "T_145", name: "老乞丐", rarity: "Green", desc: "虽然穷，但命硬。家境-5，体魄+5，福源+4。", weight: 1500, attr: { wealth: -5, body: 5, talent: 0, luck: 4, insight: 0 } },
  { t_id: "T_146", name: "江湖游医", rarity: "Green", desc: "知道点偏方。悟性+3，福源+2。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: 2, insight: 3 } },
  { t_id: "T_147", name: "天桥相士", rarity: "Green", desc: "会点忽悠人的玄学。福源+4，悟性+1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: 4, insight: 1 } },
  { t_id: "T_148", name: "飞贼", rarity: "Green", desc: "经常光顾富户。家境+4，福源-2，身法+2。", weight: 1800, attr: { wealth: 4, body: 0, talent: 2, luck: -2, insight: 0 } },
  { t_id: "T_149", name: "退伍老卒", rarity: "Green", desc: "上过战场没死。体魄+4，根骨+1。", weight: 1800, attr: { wealth: 0, body: 4, talent: 1, luck: 0, insight: 0 } },
  { t_id: "T_150", name: "轻骑兵", rarity: "Green", desc: "马背上长大的。根骨+3，体魄+2。", weight: 1800, attr: { wealth: 0, body: 2, talent: 3, luck: 0, insight: 0 } },
  { t_id: "T_151", name: "远洋水手", rarity: "Green", desc: "见识过大风大浪。体魄+3，福源+2。", weight: 1800, attr: { wealth: 0, body: 3, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_152", name: "挖矿人", rarity: "Green", desc: "力气大但吸了粉尘。体魄+5，寿命略减。家境+2。", weight: 1800, attr: { wealth: 2, body: 5, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_153", name: "养马小厮", rarity: "Green", desc: "亲近自然。福源+3，根骨+1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 1, luck: 3, insight: 0 } },
  { t_id: "T_154", name: "衙门捕快", rarity: "Green", desc: "黑白两道都认识。家境+2，福源+2，悟性+1。", weight: 1800, attr: { wealth: 2, body: 0, talent: 0, luck: 2, insight: 1 } },
  { t_id: "T_155", name: "义庄仵作", rarity: "Green", desc: "见惯了生死。悟性+4，福源-1。", weight: 1800, attr: { wealth: 0, body: 0, talent: 0, luck: -1, insight: 4 } },
  { t_id: "T_156", name: "走镖人", rarity: "Green", desc: "刀口舔血赚辛苦钱。体魄+3，家境+2。", weight: 1800, attr: { wealth: 2, body: 3, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_157", name: "草台戏子", rarity: "Green", desc: "身体柔韧性好。根骨+4，家境-1。", weight: 1800, attr: { wealth: -1, body: 0, talent: 4, luck: 0, insight: 0 } },
  { t_id: "T_158", name: "街头杂耍", rarity: "Green", desc: "反应敏捷。根骨+3，福源+2。", weight: 1800, attr: { wealth: 0, body: 0, talent: 3, luck: 2, insight: 0 } },
  { t_id: "T_159", name: "扫地沙弥", rarity: "Green", desc: "心中有佛。悟性+3，根骨+2。", weight: 1800, attr: { wealth: 0, body: 0, talent: 2, luck: 0, insight: 3 } },
  { t_id: "T_160", name: "夜猫子", rarity: "Green", desc: "一到晚上就精神。悟性+4，体魄-1。", weight: 1800, attr: { wealth: 0, body: -1, talent: 0, luck: 0, insight: 4 } },

  // ---------------- 【奇品 - 蓝色 (50个) - 优秀流派组件】 ----------------
  { t_id: "T_201", name: "家财万贯", rarity: "Blue", desc: "开局自带大笔灵石。家境+10。", weight: 1000, attr: { wealth: 10, body: 0, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_202", name: "天生神力", rarity: "Blue", desc: "力拔山兮气盖世。体魄+10。", weight: 1000, attr: { wealth: 0, body: 10, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_203", name: "过目不忘", rarity: "Blue", desc: "看过的功法一眼学会。悟性+10。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: 10 } },
  { t_id: "T_204", name: "骨骼惊奇", rarity: "Blue", desc: "万里挑一的练武奇才。根骨+10。", weight: 1000, attr: { wealth: 0, body: 0, talent: 10, luck: 0, insight: 0 } },
  { t_id: "T_205", name: "锦鲤附体", rarity: "Blue", desc: "出门总能捡到钱。福源+10。", weight: 1000, attr: { wealth: 0, body: 0, talent: 0, luck: 10, insight: 0 } },
  { t_id: "T_206", name: "武林世家", rarity: "Blue", desc: "从小打熬筋骨。体魄+5, 根骨+5。", weight: 900, attr: { wealth: 0, body: 5, talent: 5, luck: 0, insight: 0 } },
  { t_id: "T_207", name: "剑心通明", rarity: "Blue", desc: "天生适合练剑。悟性+6, 根骨+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 4, luck: 0, insight: 6 } },
  { t_id: "T_208", name: "百毒不侵", rarity: "Blue", desc: "不惧瘴气毒素。体魄+8, 福源+2。", weight: 900, attr: { wealth: 0, body: 8, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_209", name: "铜皮铁骨", rarity: "Blue", desc: "刀枪不入。体魄+12, 悟性-2。", weight: 800, attr: { wealth: 0, body: 12, talent: 0, luck: 0, insight: -2 } },
  { t_id: "T_210", name: "寻龙点穴", rarity: "Blue", desc: "擅长寻找洞天福地。福源+8, 悟性+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 8, insight: 2 } },
  { t_id: "T_211", name: "沉鱼落雁", rarity: "Blue", desc: "美貌能当饭吃。福源+12, 体魄-2。", weight: 800, attr: { wealth: 0, body: -2, talent: 0, luck: 12, insight: 0 } },
  { t_id: "T_212", name: "商业奇才", rarity: "Blue", desc: "经商天才。家境+12, 根骨-2。", weight: 800, attr: { wealth: 12, body: 0, talent: -2, luck: 0, insight: 0 } },
  { t_id: "T_213", name: "医道传人", rarity: "Blue", desc: "精通药理。悟性+5, 福源+5。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 5, insight: 5 } },
  { t_id: "T_214", name: "阵法天才", rarity: "Blue", desc: "对阵法一点就通。悟性+12, 体魄-2。", weight: 800, attr: { wealth: 0, body: -2, talent: 0, luck: 0, insight: 12 } },
  { t_id: "T_215", name: "符箓神童", rarity: "Blue", desc: "画符如喝水。悟性+8, 家境+2。", weight: 900, attr: { wealth: 2, body: 0, talent: 0, luck: 0, insight: 8 } },
  { t_id: "T_216", name: "炼器学徒", rarity: "Blue", desc: "能自己打装备。体魄+5, 悟性+5。", weight: 900, attr: { wealth: 0, body: 5, talent: 0, luck: 0, insight: 5 } },
  { t_id: "T_217", name: "灵农传人", rarity: "Blue", desc: "种田流必备。家境+5, 体魄+5。", weight: 900, attr: { wealth: 5, body: 5, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_218", name: "御兽之姿", rarity: "Blue", desc: "招小动物喜欢。福源+6, 根骨+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 4, luck: 6, insight: 0 } },
  { t_id: "T_219", name: "巧夺天工", rarity: "Blue", desc: "手极巧。悟性+6, 家境+4。", weight: 900, attr: { wealth: 4, body: 0, talent: 0, luck: 0, insight: 6 } },
  { t_id: "T_220", name: "慧根深种", rarity: "Blue", desc: "佛门好苗子。悟性+8, 根骨+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 2, luck: 0, insight: 8 } },
  { t_id: "T_221", name: "气运交加", rarity: "Blue", desc: "好运连连。福源+8, 家境+2。", weight: 900, attr: { wealth: 2, body: 0, talent: 0, luck: 8, insight: 0 } },
  { t_id: "T_222", name: "九牛二虎", rarity: "Blue", desc: "力量爆表。体魄+15, 悟性-5。", weight: 700, attr: { wealth: 0, body: 15, talent: 0, luck: 0, insight: -5 } },
  { t_id: "T_223", name: "踏雪无痕", rarity: "Blue", desc: "轻功绝顶。福源+7, 根骨+3。", weight: 900, attr: { wealth: 0, body: 0, talent: 3, luck: 7, insight: 0 } },
  { t_id: "T_224", name: "趋吉避凶", rarity: "Blue", desc: "直觉极准。福源+10, 体魄-1。", weight: 900, attr: { wealth: 0, body: -1, talent: 0, luck: 10, insight: 0 } },
  { t_id: "T_225", name: "八面玲珑", rarity: "Blue", desc: "社交达人。家境+5, 福源+5。", weight: 900, attr: { wealth: 5, body: 0, talent: 0, luck: 5, insight: 0 } },
  // -- 新增蓝色天赋 --
  { t_id: "T_226", name: "灵气亲和", rarity: "Blue", desc: "吸收灵气速度略快。根骨+8，悟性+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 8, luck: 0, insight: 2 } },
  { t_id: "T_227", name: "刀法小成", rarity: "Blue", desc: "耍大刀很有一套。体魄+6，根骨+4。", weight: 900, attr: { wealth: 0, body: 6, talent: 4, luck: 0, insight: 0 } },
  { t_id: "T_228", name: "枪出如龙", rarity: "Blue", desc: "长枪一动威震八方。体魄+5，悟性+5。", weight: 900, attr: { wealth: 0, body: 5, talent: 0, luck: 0, insight: 5 } },
  { t_id: "T_229", name: "百步穿杨", rarity: "Blue", desc: "弓箭奇才。悟性+6，福源+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 4, insight: 6 } },
  { t_id: "T_230", name: "炼丹手感", rarity: "Blue", desc: "就算乱炖也能出丹。悟性+5，福源+5。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 5, insight: 5 } },
  { t_id: "T_231", name: "阵法精要", rarity: "Blue", desc: "一眼看穿低级阵法。悟性+10。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 0, insight: 10 } },
  { t_id: "T_232", name: "符文律动", rarity: "Blue", desc: "画符带闪电。悟性+8，根骨+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 2, luck: 0, insight: 8 } },
  { t_id: "T_233", name: "兽语者", rarity: "Blue", desc: "能听懂低级妖兽说话。福源+8，悟性+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 8, insight: 2 } },
  { t_id: "T_234", name: "灵植大师", rarity: "Blue", desc: "种啥活啥。家境+6，福源+4。", weight: 900, attr: { wealth: 6, body: 0, talent: 0, luck: 4, insight: 0 } },
  { t_id: "T_235", name: "寻脉探穴", rarity: "Blue", desc: "找灵石矿脉的专家。家境+8，福源+2。", weight: 900, attr: { wealth: 8, body: 0, talent: 0, luck: 2, insight: 0 } },
  { t_id: "T_236", name: "机关传人", rarity: "Blue", desc: "精通奇门遁甲。悟性+7，家境+3。", weight: 900, attr: { wealth: 3, body: 0, talent: 0, luck: 0, insight: 7 } },
  { t_id: "T_237", name: "初级傀儡师", rarity: "Blue", desc: "能造木头人打架。根骨+5，悟性+5。", weight: 900, attr: { wealth: 0, body: 0, talent: 5, luck: 0, insight: 5 } },
  { t_id: "T_238", name: "音律入道", rarity: "Blue", desc: "弹琴能杀人。悟性+8, 体魄-2, 根骨+4。", weight: 900, attr: { wealth: 0, body: -2, talent: 4, luck: 0, insight: 8 } },
  { t_id: "T_239", name: "画卷生花", rarity: "Blue", desc: "画出来的鸟能飞。悟性+9，福源+1。", weight: 900, attr: { wealth: 0, body: 0, talent: 0, luck: 1, insight: 9 } },
  { t_id: "T_240", name: "棋局幻境", rarity: "Blue", desc: "用棋盘布阵。悟性+10, 体魄-1。", weight: 900, attr: { wealth: 0, body: -1, talent: 0, luck: 0, insight: 10 } },
  { t_id: "T_241", name: "阴阳眼", rarity: "Blue", desc: "能见鬼物。悟性+8，福源-2，体魄-2。", weight: 900, attr: { wealth: 0, body: -2, talent: 0, luck: -2, insight: 8 } },
  { t_id: "T_242", name: "龙象微力", rarity: "Blue", desc: "有一点点龙象的力气。体魄+12。", weight: 900, attr: { wealth: 0, body: 12, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_243", name: "龟息功", rarity: "Blue", desc: "憋气能活很久。体魄+8，根骨-2。", weight: 900, attr: { wealth: 0, body: 8, talent: -2, luck: 0, insight: 0 } },
  { t_id: "T_244", name: "灵猿之捷", rarity: "Blue", desc: "像猴子一样灵活。根骨+6，福源+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 6, luck: 4, insight: 0 } },
  { t_id: "T_245", name: "苍鹰之视", rarity: "Blue", desc: "动态视力极强。悟性+8，根骨+2。", weight: 900, attr: { wealth: 0, body: 0, talent: 2, luck: 0, insight: 8 } },
  { t_id: "T_246", name: "猛虎之骨", rarity: "Blue", desc: "骨骼粗壮。体魄+8，根骨+2。", weight: 900, attr: { wealth: 0, body: 8, talent: 2, luck: 0, insight: 0 } },
  { t_id: "T_247", name: "巨熊之腰", rarity: "Blue", desc: "底盘极稳。体魄+10。", weight: 900, attr: { wealth: 0, body: 10, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_248", name: "灵蛇之行", rarity: "Blue", desc: "身法诡异。根骨+8，体魄-1。", weight: 900, attr: { wealth: 0, body: -1, talent: 8, luck: 0, insight: 0 } },
  { t_id: "T_249", name: "仙鹤之步", rarity: "Blue", desc: "步法飘逸。根骨+6, 悟性+4。", weight: 900, attr: { wealth: 0, body: 0, talent: 6, luck: 0, insight: 4 } },
  { t_id: "T_250", name: "猎豹之跃", rarity: "Blue", desc: "爆发力极强。体魄+5, 根骨+5。", weight: 900, attr: { wealth: 0, body: 5, talent: 5, luck: 0, insight: 0 } },

  // ---------------- 【秘品 - 紫色 (30个) - 强力单卡与双刃剑】 ----------------
  { t_id: "T_301", name: "貌比潘安", rarity: "Purple", desc: "帅到天理难容。福源+20, 体魄-5。", weight: 400, attr: { wealth: 0, body: -5, talent: 0, luck: 20, insight: 0 } },
  { t_id: "T_302", name: "剑道痴儿", rarity: "Purple", desc: "为剑而生。悟性+20, 家境-5。", weight: 400, attr: { wealth: -5, body: 0, talent: 0, luck: 0, insight: 20 } },
  { t_id: "T_303", name: "狂战士", rarity: "Purple", desc: "抗雷劫如饮水。体魄+25, 悟性-10。", weight: 350, attr: { wealth: 0, body: 25, talent: 0, luck: 0, insight: -10 } },
  { t_id: "T_304", name: "修仙富二代", rarity: "Purple", desc: "拿钱砸死雷劫。家境+25, 根骨-10。", weight: 350, attr: { wealth: 25, body: 0, talent: -10, luck: 0, insight: 0 } },
  { t_id: "T_305", name: "纯阳之体", rarity: "Purple", desc: "阳气极重。体魄+15, 根骨+5。", weight: 400, attr: { wealth: 0, body: 15, talent: 5, luck: 0, insight: 0 } },
  { t_id: "T_306", name: "玄阴之体", rarity: "Purple", desc: "极阴之体。根骨+15, 悟性+5。", weight: 400, attr: { wealth: 0, body: 0, talent: 15, luck: 0, insight: 5 } },
  { t_id: "T_307", name: "杀戮剑意", rarity: "Purple", desc: "杀气冲天。根骨+20, 福源-5。", weight: 400, attr: { wealth: 0, body: 0, talent: 20, luck: -5, insight: 0 } },
  { t_id: "T_308", name: "长寿龟", rarity: "Purple", desc: "苟道至尊。体魄+30, 悟性-15。", weight: 300, attr: { wealth: 0, body: 30, talent: 0, luck: 0, insight: -15 } },
  { t_id: "T_309", name: "丹道宗师", rarity: "Purple", desc: "嗑药如吃饭。悟性+10, 福源+10。", weight: 400, attr: { wealth: 0, body: 0, talent: 0, luck: 10, insight: 10 } },
  { t_id: "T_310", name: "轮回印记", rarity: "Purple", desc: "带有一丝前世记忆。全属性+4。", weight: 400, attr: { wealth: 4, body: 4, talent: 4, luck: 4, insight: 4 } },
  { t_id: "T_311", name: "破妄之眼", rarity: "Purple", desc: "看破一切虚妄。悟性+15, 福源+5。", weight: 400, attr: { wealth: 0, body: 0, talent: 0, luck: 5, insight: 15 } },
  { t_id: "T_312", name: "先天残体", rarity: "Purple", desc: "废柴逆袭标配。悟性+30, 体魄-15。", weight: 300, attr: { wealth: 0, body: -15, talent: 0, luck: 0, insight: 30 } },
  { t_id: "T_313", name: "天生剑骨", rarity: "Purple", desc: "骨骼锋利如剑。体魄+10, 根骨+10。", weight: 400, attr: { wealth: 0, body: 10, talent: 10, luck: 0, insight: 0 } },
  { t_id: "T_314", name: "药王在世", rarity: "Purple", desc: "吸一口气都是药香。福源+15, 根骨+5。", weight: 400, attr: { wealth: 0, body: 0, talent: 5, luck: 15, insight: 0 } },
  { t_id: "T_315", name: "绝命毒师", rarity: "Purple", desc: "一身毒功。体魄+20, 家境-5。", weight: 400, attr: { wealth: -5, body: 20, talent: 0, luck: 0, insight: 0 } },
  // -- 新增紫色天赋 --
  { t_id: "T_316", name: "雷霆真身", rarity: "Purple", desc: "沐浴雷电而生。体魄+15, 悟性+5。", weight: 400, attr: { wealth: 0, body: 15, talent: 0, luck: 0, insight: 5 } },
  { t_id: "T_317", name: "极寒冰骨", rarity: "Purple", desc: "冰系功法神速。根骨+20, 体魄-2, 悟性+2。", weight: 400, attr: { wealth: 0, body: -2, talent: 20, luck: 0, insight: 2 } },
  { t_id: "T_318", name: "九阳之体", rarity: "Purple", desc: "至阳至刚。体魄+18, 根骨+7。", weight: 400, attr: { wealth: 0, body: 18, talent: 7, luck: 0, insight: 0 } },
  { t_id: "T_319", name: "九阴之体", rarity: "Purple", desc: "至阴至柔。根骨+18, 悟性+7。", weight: 400, attr: { wealth: 0, body: 0, talent: 18, luck: 0, insight: 7 } },
  { t_id: "T_320", name: "无垢剑心", rarity: "Purple", desc: "不染尘埃的剑道奇才。悟性+18, 根骨+7。", weight: 400, attr: { wealth: 0, body: 0, talent: 7, luck: 0, insight: 18 } },
  { t_id: "T_321", name: "药仙转世", rarity: "Purple", desc: "天生带草药亲和力。福源+12, 悟性+10。", weight: 400, attr: { wealth: 0, body: 0, talent: 0, luck: 12, insight: 10 } },
  { t_id: "T_322", name: "天机算尽", rarity: "Purple", desc: "折寿算卦。悟性+25, 体魄-10。", weight: 350, attr: { wealth: 0, body: -10, talent: 0, luck: 0, insight: 25 } },
  { t_id: "T_323", name: "万兽之主", rarity: "Purple", desc: "群兽臣服。福源+15, 体魄+5。", weight: 400, attr: { wealth: 0, body: 5, talent: 0, luck: 15, insight: 0 } },
  { t_id: "T_324", name: "千机百炼", rarity: "Purple", desc: "炼器大宗师之资。悟性+15, 家境+5。", weight: 400, attr: { wealth: 5, body: 0, talent: 0, luck: 0, insight: 15 } },
  { t_id: "T_325", name: "五行之体", rarity: "Purple", desc: "五行功法皆可修。根骨+12, 体魄+8。", weight: 400, attr: { wealth: 0, body: 8, talent: 12, luck: 0, insight: 0 } },
  { t_id: "T_326", name: "星辰之子", rarity: "Purple", desc: "夜间修炼加倍。福源+15, 根骨+5。", weight: 400, attr: { wealth: 0, body: 0, talent: 5, luck: 15, insight: 0 } },
  { t_id: "T_327", name: "霸王降世", rarity: "Purple", desc: "力能扛鼎但脑子不好。体魄+25, 悟性-5。", weight: 350, attr: { wealth: 0, body: 25, talent: 0, luck: 0, insight: -5 } },
  { t_id: "T_328", name: "幻月妖瞳", rarity: "Purple", desc: "精通幻术。悟性+18, 福源-2, 体魄-2。", weight: 400, attr: { wealth: 0, body: -2, talent: 0, luck: -2, insight: 18 } },
  { t_id: "T_329", name: "饕餮胃袋", rarity: "Purple", desc: "吃石头都能转化气血。体魄+20, 家境-5。", weight: 400, attr: { wealth: -5, body: 20, talent: 0, luck: 0, insight: 0 } },
  { t_id: "T_330", name: "菩提佛心", rarity: "Purple", desc: "大彻大悟。悟性+18, 福源+4。", weight: 400, attr: { wealth: 0, body: 0, talent: 0, luck: 4, insight: 18 } },

  // ---------------- 【圣品 - 橙色 (14个) - 绝对的神仙开局】 ----------------
  { t_id: "T_401", name: "位面之子", rarity: "Orange", desc: "出门捡神装，跳崖得神功。福源+35, 悟性+15。", weight: 80, attr: { wealth: 0, body: 0, talent: 0, luck: 35, insight: 15 } },
  { t_id: "T_402", name: "荒古圣体", rarity: "Orange", desc: "肉身成圣，横推万古！体魄+40, 悟性-10。", weight: 80, attr: { wealth: 0, body: 40, talent: 0, luck: 0, insight: -10 } },
  { t_id: "T_403", name: "先天道胎", rarity: "Orange", desc: "生来与道相融。根骨+40, 体魄-10。", weight: 80, attr: { wealth: 0, body: -10, talent: 40, luck: 0, insight: 0 } },
  { t_id: "T_404", name: "重瞳者", rarity: "Orange", desc: "上古圣人之相。悟性+30, 福源+20。", weight: 80, attr: { wealth: 0, body: 0, talent: 0, luck: 20, insight: 30 } },
  { t_id: "T_405", name: "混沌剑体", rarity: "Orange", desc: "一剑破万法。根骨+25, 悟性+25。", weight: 80, attr: { wealth: 0, body: 0, talent: 25, luck: 0, insight: 25 } },
  { t_id: "T_406", name: "万法不侵", rarity: "Orange", desc: "雷劫劈不死你。体魄+30, 福源+20。", weight: 80, attr: { wealth: 0, body: 30, talent: 0, luck: 20, insight: 0 } },
  { t_id: "T_407", name: "九劫秘典", rarity: "Orange", desc: "越挨劈越强。体魄+20, 根骨+30。", weight: 80, attr: { wealth: 0, body: 20, talent: 30, luck: 0, insight: 0 } },
  // -- 新增橙色天赋 --
  { t_id: "T_408", name: "时空旅者", rarity: "Orange", desc: "能在时间长河中漫步。福源+25, 悟性+25。", weight: 80, attr: { wealth: 0, body: 0, talent: 0, luck: 25, insight: 25 } },
  { t_id: "T_409", name: "毁灭之源", rarity: "Orange", desc: "触之即死。体魄+35, 根骨+15。", weight: 80, attr: { wealth: 0, body: 35, talent: 15, luck: 0, insight: 0 } },
  { t_id: "T_410", name: "生命回响", rarity: "Orange", desc: "寿元几乎无限。体魄+30, 福源+20。", weight: 80, attr: { wealth: 0, body: 30, talent: 0, luck: 20, insight: 0 } },
  { t_id: "T_411", name: "虚空行者", rarity: "Orange", desc: "没人抓得住你。根骨+30, 福源+20。", weight: 80, attr: { wealth: 0, body: 0, talent: 30, luck: 20, insight: 0 } },
  { t_id: "T_412", name: "气运凝珠", rarity: "Orange", desc: "上天的私生子。家境+20, 福源+30。", weight: 80, attr: { wealth: 20, body: 0, talent: 0, luck: 30, insight: 0 } },
  { t_id: "T_413", name: "万剑归宗", rarity: "Orange", desc: "天下名剑皆认你为主。根骨+35, 悟性+15。", weight: 80, attr: { wealth: 0, body: 0, talent: 35, luck: 0, insight: 15 } },
  { t_id: "T_414", name: "涅槃神羽", rarity: "Orange", desc: "死后有概率浴火重生。体魄+25, 福源+25。", weight: 80, attr: { wealth: 0, body: 25, talent: 0, luck: 25, insight: 0 } },

  // ---------------- 【神品 - 金色 (4个) - 破坏游戏平衡的挂壁】 ----------------
  { t_id: "T_501", name: "仙帝转世", rarity: "Gold", desc: "天下功法一看便知！全属性+15。", weight: 15, attr: { wealth: 15, body: 15, talent: 15, luck: 15, insight: 15 } },
  { t_id: "T_502", name: "神秘小瓶", rarity: "Gold", desc: "韩天尊同款，催熟万物！家境+50, 福源+30。", weight: 15, attr: { wealth: 50, body: 0, talent: 0, luck: 30, insight: 0 } },
  // -- 新增金色天赋 --
  { t_id: "T_503", name: "随身老爷爷", rarity: "Gold", desc: "戒指里有个残魂指点你。悟性+40, 福源+40。", weight: 15, attr: { wealth: 0, body: 0, talent: 0, luck: 40, insight: 40 } },
  { t_id: "T_504", name: "天道私生子", rarity: "Gold", desc: "你就是天理！福源+60, 家境+20。", weight: 15, attr: { wealth: 20, body: 0, talent: 0, luck: 60, insight: 0 } },

  // ---------------- 【帝品 - 闪红 (2个) - 极致的爽与极致的痛】 ----------------
  { t_id: "T_601", name: "天妒英才", rarity: "Red", desc: "修炼速度毁天灭地！但极易夭折。根骨+60, 悟性+60, 体魄-40。", weight: 5, attr: { wealth: 0, body: -40, talent: 60, luck: 0, insight: 60 } },
  // -- 新增红色天赋 --
  { t_id: "T_602", name: "万世情劫", rarity: "Red", desc: "历经九十九世情伤，大道终成！悟性+99, 福源-50。", weight: 5, attr: { wealth: 0, body: 0, talent: 0, luck: -50, insight: 99 } }
];


// === 灵根库 (60种，完全覆盖所有品质与变异种类) ===
const ROOT_POOL = [
  // --- 灰品 (13种) - 修炼极慢 ---
  { name: "凡人无灵根", color: "Gray", multi: 0.1, weight: 500},
  { name: "杂品废灵根", color: "Gray", multi: 0.3, weight: 400 },
  { name: "五系斑驳灵根", color: "Gray", multi: 0.5, weight: 300 },
  { name: "四系伪灵根", color: "Gray", multi: 0.7, weight: 250 },
  { name: "朽木灵根", color: "Gray", multi: 0.8, weight: 200 },
  { name: "浊土灵根", color: "Gray", multi: 0.8, weight: 200 },
  { name: "枯水灵根", color: "Gray", multi: 0.8, weight: 200 },
  { name: "暗金残根", color: "Gray", multi: 0.8, weight: 200 },
  { name: "微火弱根", color: "Gray", multi: 0.8, weight: 200 },
  { name: "废土灵根", color: "Gray", multi: 0.6, weight: 250 },
  { name: "死水灵根", color: "Gray", multi: 0.6, weight: 250 },
  { name: "钝金灵根", color: "Gray", multi: 0.6, weight: 250 },
  { name: "残木灵根", color: "Gray", multi: 0.6, weight: 250 },

  // --- 绿品 (12种) - 勉强修仙 ---
  { name: "三系真灵根", color: "Green", multi: 1.0, weight: 300 },
  { name: "凡木灵根", color: "Green", multi: 1.2, weight: 250 },
  { name: "凡火灵根", color: "Green", multi: 1.2, weight: 250 },
  { name: "凡水灵根", color: "Green", multi: 1.2, weight: 250 },
  { name: "凡金灵根", color: "Green", multi: 1.2, weight: 250 },
  { name: "凡土灵根", color: "Green", multi: 1.2, weight: 250 },
  { name: "水木双系", color: "Green", multi: 1.4, weight: 200 },
  { name: "金水双系", color: "Green", multi: 1.4, weight: 200 },
  { name: "土金双系", color: "Green", multi: 1.4, weight: 200 },
  { name: "火土双系", color: "Green", multi: 1.4, weight: 200 },
  { name: "木火双系", color: "Green", multi: 1.4, weight: 200 },
  { name: "风水双系", color: "Green", multi: 1.5, weight: 180 },

  // --- 蓝品 (12种) - 中流砥柱 ---
  { name: "双系地灵根", color: "Blue", multi: 2.0, weight: 150 },
  { name: "真木灵根", color: "Blue", multi: 2.5, weight: 120 },
  { name: "真火灵根", color: "Blue", multi: 2.5, weight: 120 },
  { name: "真水灵根", color: "Blue", multi: 2.5, weight: 120 },
  { name: "真金灵根", color: "Blue", multi: 2.5, weight: 120 },
  { name: "真土灵根", color: "Blue", multi: 2.5, weight: 120 },
  { name: "风雷变异根", color: "Blue", multi: 2.8, weight: 100 },
  { name: "冰魄灵根", color: "Blue", multi: 2.8, weight: 100 },
  { name: "熔岩灵根", color: "Blue", multi: 2.6, weight: 110 },
  { name: "毒沼灵根", color: "Blue", multi: 2.6, weight: 110 },
  { name: "星光灵根", color: "Blue", multi: 2.8, weight: 100 },
  { name: "幻音灵根", color: "Blue", multi: 2.6, weight: 110 },

  // --- 紫品 (12种) - 门派天才 ---
  { name: "单系天灵根", color: "Purple", multi: 4.0, weight: 80 },
  { name: "极木天灵根", color: "Purple", multi: 5.0, weight: 60 },
  { name: "极火天灵根", color: "Purple", multi: 5.0, weight: 60 },
  { name: "极水天灵根", color: "Purple", multi: 5.0, weight: 60 },
  { name: "极金天灵根", color: "Purple", multi: 5.0, weight: 60 },
  { name: "极土天灵根", color: "Purple", multi: 5.0, weight: 60 },
  { name: "太阳真灵根", color: "Purple", multi: 5.5, weight: 55 },
  { name: "太阴真灵根", color: "Purple", multi: 5.5, weight: 55 },
  { name: "纯阳剑根", color: "Purple", multi: 5.8, weight: 50 },
  { name: "纯阴淼根", color: "Purple", multi: 5.8, weight: 50 },
  { name: "涅槃火根", color: "Purple", multi: 6.0, weight: 45 },
  { name: "戊土神根", color: "Purple", multi: 6.0, weight: 45 },

  // --- 橙品 (9种) - 天地异象 ---
  { name: "变异风灵根", color: "Orange", multi: 8.0, weight: 30 },
  { name: "变异冰灵根", color: "Orange", multi: 8.0, weight: 30 },
  { name: "变异雷灵根", color: "Orange", multi: 8.0, weight: 30 },
  { name: "变异暗灵根", color: "Orange", multi: 10.0, weight: 10 },
  { name: "空间系灵根", color: "Orange", multi: 12.0, weight: 8 },
  { name: "时间系灵根", color: "Orange", multi: 12.0, weight: 8 },
  { name: "毁灭系灵根", color: "Orange", multi: 11.0, weight: 8 },
  { name: "生命系灵根", color: "Orange", multi: 11.0, weight: 8 },
  { name: "吞噬系灵根", color: "Orange", multi: 12.0, weight: 6 },

  // --- 金品 (2种) - 气运之子 ---
  { name: "混沌道体", color: "Gold", multi: 20.0, weight: 2 },
  { name: "鸿蒙本源根", color: "Gold", multi: 30.0, weight: 2 }
];



const GAME_HELP = {
  title: "天道法则 (玩法说明)",
  content: "【核心法则】\n本游戏为完全随机的肉鸽修仙！每次开局自动随机抽取 3个天赋、1个灵根，并随机分配属性点。\n\n【关于天赋 (200种)】\n分为 灰、绿、蓝、紫、橙、金、红 七大品阶。红品为绝世妖孽，灰品可能让你寸步难行！\n\n【关于灵根 (60种)】\n灵根直接决定你闭关修炼的获取倍率，最强灵根可达普通人的数十倍！\n\n【关于功德转化】\n修仙路漫漫，每一世陨落后结算的「功德」，会在下一次投胎时自动消耗殆尽。每 100 功德 = 1 点额外自由属性点（随机分配给当前这一世）。功德不会永久累加，死后清零重算，保证天道平衡！\n\n【逆天改命】\n如果对初始资质不满意，可消耗次数「重新投胎」。次数不足时，可通过【观看广告】(+5次) 或 【分享给道友】(+3次，每日限3次) 获取。"
};

module.exports = {
  MASTER_TALENTS,
  ROOT_POOL,
  GAME_HELP // 把帮助文档也暴露出去

};