import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

import { BUILD_V1, ContentRegistry, runBuildAudit, sealContentPack, validateBuildPack, validateContentPack } from "../packages/content/src/index.ts";
import { activeBuildProgressionSources, activeBuildRiskSources, applyBuildEvidence, applyEventEffects, buildStage, createCommandLog, createOfferedRun, createSnapshot, executeLoggedCommand, orderedBuildHooks, projectDirectorBuildSignals, reduce, replayCommandLog, ruleStateHash, validateGameState, validateSnapshot, validateStateTransition } from "../packages/core/src/index.ts";
import { ServerViewModelBuilder } from "../server/src/index.ts";

const contentPack = JSON.parse(fs.readFileSync(new URL("../packages/content/dev-fixtures/minimal-pack.json", import.meta.url), "utf8"));
function registry() { const content = new ContentRegistry(); content.register(contentPack); return content; }
function active({ currentEvent = false, nodeIndex = 0 } = {}) { const content = registry(); const offered = createOfferedRun({ schemaVersion: 2, rulesVersion: "2.0.0", contentVersion: "dev-0.1.0", runId: "run-build", playerId: "player-build", rootSeed: "build-fixed-seed", metaView: { unlocks: [], entitlements: [], discoveries: [] }, fixture: { offerId: "offer-build", destinyIds: ["destiny.steady-foundation", "destiny.volatile-star", "destiny.hidden-mentor"], age: 20, maxAge: 80, runName: "Build", realm: { id: "mortal", order: 0, cultivation: 0 }, attributes: { insight: 10, body: 10, spiritSense: 10, fortune: 10 }, resources: { spiritStone: 0, items: {} }, availableActions: ["cultivate", "travel"], world: { regionId: "dev.start", knownRegionIds: ["dev.start"], tags: [], factionStanding: {} } } }); const started = reduce({ state: offered, command: { type: "START_RUN", offerId: "offer-build", destinyId: "destiny.steady-foundation" }, context: { rulesVersion: "2.0.0", contentVersion: "dev-0.1.0", content, commandId: "cmd:start-build" } }).state; return { content, state: validateGameState({ ...started, run: { ...started.run, nodeIndex, events: currentEvent ? { history: [], current: { eventId: "dev.first-choice", kind: "choice" } } : started.run.events } }) }; }
function evidence(state, buildId, amount, index = 0, pack = BUILD_V1) { return applyBuildEvidence(state, pack, { buildId, amount, reasonTag: `test.reason.${index}` }, { commandId: `cmd:evidence:${index}`, sourceRef: "event:test" }); }
function customDefinition(id, source = BUILD_V1.definitions[0]) { return { ...structuredClone(source), id, displayName: id, compatibleWith: [], conflictsWith: [], parentBuildIds: [], requiresTags: [], forbidsTags: [], hooks: [], stages: structuredClone(source.stages), modifiers: [] }; }

test("BuildAffinity schema accepts scalable maps and rejects invalid bounds", () => { const { state } = active(); const valid = validateGameState({ ...state, run: { ...state.run, build: { ...state.run.build, affinities: { "build.sword": { buildId: "build.sword", affinityBps: 100, lifetimeEvidence: 200, lastEvidenceNodeIndex: 0 } } } } }); assert.equal(valid.run.build.affinities["build.sword"].affinityBps, 100); assert.throws(() => validateGameState({ ...valid, run: { ...valid.run, build: { ...valid.run.build, affinities: { "build.sword": { buildId: "build.sword", affinityBps: 10001, lifetimeEvidence: 0, lastEvidenceNodeIndex: 0 } } } } })); });

test("ADD_BUILD_EVIDENCE applies only authored semantic evidence with source trace", () => { const { state } = active({ currentEvent: true }); const result = reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "study-sword" }, context: { rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, content: registry(), commandId: "cmd:study-sword" } }); const affinity = result.state.run.build.affinities["build.sword"]; assert.equal(affinity.affinityBps, 2500); assert.equal(affinity.lifetimeEvidence, 2500); assert.equal(result.narrativeFacts.some((fact) => fact.type === "BUILD_FIRST_EVIDENCE"), true); assert.equal(result.state.run.build.evidenceFacts[0].source, "dev.first-choice"); });

test("Build stages derive deterministically from versioned thresholds", () => { assert.deepEqual([0,1999,2000,4499,4500,7499,7500,10000].map((value) => buildStage(BUILD_V1.rules, value)), ["latent","latent","emerging","emerging","formed","formed","refined","refined"]); });

test("lifetimeEvidence is monotonic while affinity may fall", () => { let state = active().state; state = evidence(state, "build.sword", 3000, 1).state; state = evidence(state, "build.body", 1000, 2).state; assert.equal(state.run.build.affinities["build.sword"].affinityBps, 2800); assert.equal(state.run.build.affinities["build.sword"].lifetimeEvidence, 3000); const invalid = structuredClone(state); invalid.run.build.affinities["build.sword"].lifetimeEvidence = 1; assert.throws(() => validateStateTransition(state, invalid), /monotonic/); });

test("focus pressure uses versioned 20 percent and never underflows", () => { let state = active().state; state = evidence(state, "build.sword", 3000, 1).state; state = evidence(state, "build.body", 1000, 2).state; assert.equal(state.run.build.affinities["build.sword"].affinityBps, 2800); for (let index = 3; index < 8; index += 1) state = evidence(state, "build.body", 3000, index).state; assert.equal(state.run.build.affinities["build.sword"].affinityBps, 0); });

test("dominant build forms and switches only across the configured margin", () => { let state = active().state; state = evidence(state, "build.sword", 2500, 1).state; state = evidence(state, "build.sword", 2500, 2).state; assert.equal(state.run.build.dominantBuildId, "build.sword"); state = evidence(state, "build.body", 3000, 3).state; assert.equal(state.run.build.dominantBuildId, "build.sword"); state = evidence(state, "build.body", 3000, 4).state; assert.equal(state.run.build.dominantBuildId, "build.body"); });

test("equal formed affinities use stable buildId canonical ordering without RNG", () => { const { state: base } = active(); const state = validateGameState({ ...base, run: { ...base.run, build: { ...base.run.build, affinities: { "build.sword": { buildId: "build.sword", affinityBps: 5000, lifetimeEvidence: 5000, lastEvidenceNodeIndex: 0 }, "build.body": { buildId: "build.body", affinityBps: 5000, lifetimeEvidence: 5000, lastEvidenceNodeIndex: 0 } } } } }); const result = evidence(state, "build.alchemy", 200, 1); assert.equal(result.state.run.build.dominantBuildId, "build.body"); assert.deepEqual(result.state.run.rng, state.run.rng); });

test("sword, body and alchemy activate only registered PROG01/RISK01 modifiers", () => { const { state: base, content } = active(); const state = validateGameState({ ...base, run: { ...base.run, build: { ...base.run.build, affinities: { "build.sword": { buildId: "build.sword", affinityBps: 7500, lifetimeEvidence: 7500, lastEvidenceNodeIndex: 0 }, "build.body": { buildId: "build.body", affinityBps: 7500, lifetimeEvidence: 7500, lastEvidenceNodeIndex: 0 }, "build.alchemy": { buildId: "build.alchemy", affinityBps: 7500, lifetimeEvidence: 7500, lastEvidenceNodeIndex: 0 } } } } }); const progression = activeBuildProgressionSources(state, BUILD_V1).flatMap((source) => source.modifiers); const risk = activeBuildRiskSources(state, BUILD_V1).flatMap((source) => source.modifiers); const total = (kind) => progression.filter((modifier) => modifier.kind === kind).reduce((sum, modifier) => sum + modifier.value, 0); assert.equal(total("cultivationGainRateDeltaBps"), 300); assert.equal(total("foundationGainRateDeltaBps"), 700); assert.equal(total("breakthroughScoreDelta"), 20); assert.equal(total("breakthroughDifficultyDelta"), -10); assert.equal(total("failureCultivationLossDelta"), -500); assert.equal(risk.filter((modifier) => modifier.kind === "riskScoreDelta").reduce((sum, modifier) => sum + modifier.value, 0), 20); assert.ok(content.getBuild("dev-0.1.0")); });

test("fortune Build changes identity only and never changes RNG, Check, or Outcome", () => { const { state } = active(); const before = structuredClone(state.run.rng); const result = evidence(state, "build.fortune", 3000, 1); assert.deepEqual(result.state.run.rng, before); assert.deepEqual(activeBuildProgressionSources(result.state, BUILD_V1), []); assert.deepEqual(activeBuildRiskSources(result.state, BUILD_V1), []); });

test("short life may end after three nodes with no formed Build", () => { let state = active().state; for (let index = 1; index <= 3; index += 1) state = evidence(state, "build.sword", 200, index).state; state = validateGameState({ ...state, run: { ...state.run, nodeIndex: 3, status: "dying" } }); assert.equal(buildStage(BUILD_V1.rules, state.run.build.affinities["build.sword"].affinityBps), "latent"); assert.equal(state.run.build.dominantBuildId, undefined); });

test("few decisive evidence facts can rapidly form a Build", () => { let state = active().state; state = evidence(state, "build.sword", 2500, 1).state; state = evidence(state, "build.sword", 2500, 2).state; assert.equal(buildStage(BUILD_V1.rules, state.run.build.affinities["build.sword"].affinityBps), "formed"); });

test("30+ focused nodes refine one Build without auto-populating others", () => { let state = active({ nodeIndex: 30 }).state; state = evidence(state, "build.sword", 2500, 1).state; state = evidence(state, "build.sword", 2500, 2).state; state = evidence(state, "build.sword", 2500, 3).state; assert.equal(buildStage(BUILD_V1.rules, state.run.build.affinities["build.sword"].affinityBps), "refined"); assert.deepEqual(Object.keys(state.run.build.affinities), ["build.sword"]); });

test("30+ mixed nodes support dual paths and turn-path without maxing everything", () => { let state = active({ nodeIndex: 35 }).state; for (let index = 0; index < 20; index += 1) state = evidence(state, index % 2 === 0 ? "build.sword" : "build.body", 400, index).state; const affinities = Object.values(state.run.build.affinities); assert.equal(affinities.length, 2); assert.equal(affinities.every((value) => value.affinityBps === 10000), false); assert.ok(affinities.every((value) => value.lifetimeEvidence > 0)); });

test("repeated events without Build evidence never change Build state", () => { let state = active().state; const before = structuredClone(state.run.build); for (let index = 0; index < 40; index += 1) state = applyEventEffects(state, [{ op: "ADD_RESOURCE", key: "spiritStone", amount: 1 }], `event:${index}`).state; assert.deepEqual(state.run.build, before); });

test("turn-path emits deterministic dominant-change facts", () => { let state = active().state; for (const [index, amount] of [2500,2500].entries()) state = evidence(state, "build.sword", amount, index).state; state = evidence(state, "build.body", 3000, 3).state; const result = evidence(state, "build.body", 3000, 4); assert.equal(result.facts.some((fact) => fact.type === "BUILD_DOMINANT_CHANGED" && fact.fromBuildId === "build.sword" && fact.toBuildId === "build.body"), true); });

test("Snapshot roundtrip preserves authoritative Build state", () => { const state = evidence(active().state, "build.sword", 2500, 1).state; const snapshot = createSnapshot(state, 0); const restored = validateSnapshot(JSON.parse(JSON.stringify(snapshot))); assert.deepEqual(restored.state.run.build, state.run.build); });

test("event Evidence replays to identical Build state, RNG and canonical hash", () => { const { content, state } = active({ currentEvent: true }); const envelope = { commandId: "cmd:build-replay", playerId: state.run.playerId, runId: state.run.runId, expectedStateVersion: state.stateVersion, rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, clientPlatform: "dev", clientBuild: "build-test", command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "study-sword" } }; const executed = executeLoggedCommand(state, createCommandLog(state), envelope, {}, content); const replayed = replayCommandLog({ initialState: state, commandLog: executed.commandLog, content }); assert.deepEqual(replayed.state.run.build, executed.output.state.run.build); assert.deepEqual(replayed.state.run.rng, executed.output.state.run.rng); assert.equal(replayed.finalRuleStateHash, ruleStateHash(executed.output.state)); });

test("ViewModel exposes semantic stages but never exact affinity or lifetime evidence", () => { const { content, state: base } = active(); const state = evidence(base, "build.sword", 2500, 1).state; const view = new ServerViewModelBuilder(content).build(state); const json = JSON.stringify(view); assert.equal(json.includes("build.sword"), true); assert.equal(json.includes("emerging"), true); assert.equal(json.includes("affinityBps"), false); assert.equal(json.includes("lifetimeEvidence"), false); });

test("Definition Registry validates IDs, references, cycles and insertion independence", () => { assert.strictEqual(validateBuildPack(BUILD_V1), BUILD_V1); const reversed = structuredClone(BUILD_V1); reversed.definitions.reverse(); validateBuildPack(reversed); const initial = active().state; assert.deepEqual(evidence(initial, "build.sword", 2500, 1, BUILD_V1).state.run.build, evidence(initial, "build.sword", 2500, 1, reversed).state.run.build); const cycle = structuredClone(BUILD_V1); cycle.definitions[0].parentBuildIds = ["build.body"]; cycle.definitions[1].parentBuildIds = ["build.sword"]; assert.throws(() => validateBuildPack(cycle), /cycle/); });

test("Build hooks are whitelist-only, canonical and reject arbitrary executable content", () => { const pack = structuredClone(BUILD_V1); pack.definitions[0].stages[2].hooks.push({ id: "build.after-stage-transition", systemOwner: "BUILD01", order: 20 }); validateBuildPack(pack); const state = evidence(active().state, "build.sword", 2500, 1, pack).state; const formed = evidence(state, "build.sword", 2500, 2, pack).state; assert.deepEqual(orderedBuildHooks(formed, pack).map((hook) => hook.id), ["build.after-stage-transition"]); const unknown = structuredClone(pack); unknown.definitions[0].hooks.push({ id: "build.eval", systemOwner: "BUILD01", order: 1 }); assert.throws(() => validateBuildPack(unknown), /hook/); const executable = structuredClone(BUILD_V1); executable.definitions[0].script = () => 1; assert.throws(() => validateBuildPack(executable), /finite JSON|unknown field/); });

test("custom fifth Build registers, accumulates, dominates, modifies, serializes and replays without Core changes", () => {
  const pack = structuredClone(BUILD_V1); pack.id = "build.test-five"; const custom = customDefinition("build.test-custom-5"); custom.stages[2].modifiers = [{ kind: "cultivationGainRateDeltaBps", value: 111, systemOwner: "PROG01" }]; pack.definitions.push(custom); pack.manifest.buildCount += 1; validateBuildPack(pack);
  const content = new ContentRegistry(); content.registerBuildPack(pack); const source = structuredClone(contentPack); source.events[0].choices.find((choice) => choice.id === "study-sword").outcomes.success.effects[0].buildId = custom.id; const { checksum: _checksum, ...manifest } = source.manifest; const customContent = sealContentPack({ ...source, manifest: { ...manifest, contentVersion: "dev-custom-five" }, buildPackId: pack.id }); content.register(customContent);
  const offered = createOfferedRun({ schemaVersion: 2, rulesVersion: "2.0.0", contentVersion: "dev-custom-five", runId: "run-custom-five", playerId: "player-custom-five", rootSeed: "custom-five-seed", metaView: { unlocks: [], entitlements: [], discoveries: [] }, fixture: { offerId: "offer", destinyIds: ["destiny.steady-foundation", "destiny.volatile-star", "destiny.hidden-mentor"], age: 20, maxAge: 80, runName: "Custom", realm: { id: "mortal", order: 0, cultivation: 0 }, attributes: { insight: 1, body: 1, spiritSense: 1, fortune: 1 }, resources: { spiritStone: 0, items: {} }, availableActions: ["cultivate"], world: { regionId: "dev.start", knownRegionIds: ["dev.start"], tags: [], factionStanding: {} } } }); const started = reduce({ state: offered, command: { type: "START_RUN", offerId: "offer", destinyId: "destiny.steady-foundation" }, context: { rulesVersion: "2.0.0", contentVersion: "dev-custom-five", content, commandId: "cmd:start-custom" } }).state;
  const state = validateGameState({ ...started, run: { ...started.run, events: { history: [], current: { eventId: "dev.first-choice", kind: "choice" } }, build: { ...started.run.build, affinities: { [custom.id]: { buildId: custom.id, affinityBps: 2500, lifetimeEvidence: 2500, lastEvidenceNodeIndex: 0 } } } } }); const envelope = { commandId: "cmd:custom-evidence", playerId: state.run.playerId, runId: state.run.runId, expectedStateVersion: state.stateVersion, rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, clientPlatform: "dev", clientBuild: "build-test", command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "study-sword" } }; const executed = executeLoggedCommand(state, createCommandLog(state), envelope, {}, content); const replayed = replayCommandLog({ initialState: state, commandLog: executed.commandLog, content });
  assert.equal(executed.output.state.run.build.dominantBuildId, custom.id); assert.equal(activeBuildProgressionSources(executed.output.state, pack)[0].modifiers[0].value, 111); assert.deepEqual(replayed.state.run.build, executed.output.state.run.build); assert.equal(replayed.finalRuleStateHash, ruleStateHash(executed.output.state)); assert.deepEqual(JSON.parse(JSON.stringify(executed.output.state.run.build)), executed.output.state.run.build);
});

test("hybrid Build unlocks through parentBuildIds plus whitelist BuildConditionExpr", () => { const pack = structuredClone(BUILD_V1); pack.id = "build.test-hybrid"; const hybrid = customDefinition("build.test-hybrid"); hybrid.parentBuildIds = ["build.sword", "build.body"]; hybrid.unlockConditions = [{ all: [{ buildAffinityGte: ["build.sword", 4500] }, { buildStageIs: ["build.body", "formed"] }] }]; pack.definitions.push(hybrid); pack.manifest.buildCount += 1; validateBuildPack(pack); let state = active().state; state = evidence(state, "build.sword", 3000, 1, pack).state; state = evidence(state, "build.sword", 3000, 2, pack).state; state = evidence(state, "build.body", 3000, 3, pack).state; const result = evidence(state, "build.body", 3000, 4, pack); assert.equal(result.state.run.build.unlockedBuildIds.includes(hybrid.id), true); assert.equal(result.facts.some((fact) => fact.type === "BUILD_BRANCH_UNLOCKED"), true); });

test("build-audit and contentVersion isolation pass with deterministic Director read model", () => { const audit = runBuildAudit(); for (const key of ["invalidDefinitions", "cycleViolations", "hookConflicts", "shortLifeFailures", "longLifeFailures", "determinismFailures", "replayFailures", "securityViolations"]) assert.equal(audit[key], 0, key); assert.equal(audit.buildDefinitions, 4); const { state } = active(); const developed = evidence(state, "build.sword", 2500, 1).state; assert.deepEqual(projectDirectorBuildSignals(developed, BUILD_V1).builds[0], { buildId: "build.sword", stage: "emerging", tags: ["sword"] }); const customPack = structuredClone(BUILD_V1); customPack.id = "build.content-v2"; customPack.definitions.push(customDefinition("build.content-only")); customPack.manifest.buildCount += 1; const content = registry(); content.registerBuildPack(customPack); const source = structuredClone(contentPack); const { checksum: _checksum, ...manifest } = source.manifest; const next = sealContentPack({ ...source, manifest: { ...manifest, contentVersion: "dev-build-v2" }, buildPackId: customPack.id }); content.register(next); assert.equal(content.getBuild("dev-0.1.0").definitions.length, 4); assert.equal(content.getBuild("dev-build-v2").definitions.length, 5); });

test("fixed input Build evidence is deterministic and Content lint enforces authoring range/references", () => { const first = evidence(active().state, "build.sword", 2500, 1); const second = evidence(active().state, "build.sword", 2500, 1); assert.deepEqual(first, second); assert.deepEqual(first.state.run.rng, active().state.run.rng); for (const invalidEffect of [{ op: "ADD_BUILD_EVIDENCE", buildId: "build.sword", amount: 199, reasonTag: "bad" }, { op: "ADD_BUILD_EVIDENCE", buildId: "build.unknown", amount: 200, reasonTag: "bad" }]) { const source = structuredClone(contentPack); source.events[0].choices[0].outcomes.success.effects = [invalidEffect]; const { checksum: _checksum, ...manifest } = source.manifest; assert.throws(() => validateContentPack(sealContentPack({ ...source, manifest })), /amount|BuildDefinition/); } });
