import assert from "node:assert/strict";
import test from "node:test";

import { CONTENT01_ARCHETYPES, CONTENT01_CAUSE_CHAINS, CONTENT01_EVENTS, CONTENT01_PACK, CONTENT01_VERSION, CONTENT01_ZH_CN, ContentRegistry, NPC_CONTENT01_V1, runContentPlayabilityAudit, runContentSimulation, sealContentPack, validateContentPack, validateNpcPack } from "../packages/content/src/index.ts";
import { advanceCauses, buildStage, createCommandLog, createOfferedRun, createSnapshot, executeLoggedCommand, materializeEventParticipants, reduce, replayCommandLog, ruleStateHash, validateGameState, validateSnapshot } from "../packages/core/src/index.ts";
import { ServerViewModelBuilder } from "../server/src/index.ts";

function registry(pack = CONTENT01_PACK, npcPack = NPC_CONTENT01_V1) { const content = new ContentRegistry(); content.registerNpcPack(npcPack); content.register(pack); return content; }
function offered(maxAge = 200, contentVersion = CONTENT01_VERSION, firstRun = false, seed = "content01-test") { return createOfferedRun({ schemaVersion: 2, rulesVersion: "2.0.0", contentVersion, runId: `run:${contentVersion}:${seed}`, playerId: "player:content01", rootSeed: seed, metaView: { unlocks: [], entitlements: [], discoveries: [] }, fixture: { offerId: `offer:${contentVersion}:${seed}`, destinyIds: ["content01.destiny.steady", "content01.destiny.edge", "content01.destiny.echo"], age: 20, maxAge, runName: "一世", realm: { id: "mortal", order: 0, cultivation: 0 }, attributes: { insight: 45, body: 45, spiritSense: 45, fortune: 45 }, resources: { spiritStone: 0, items: {} }, availableActions: ["cultivate", "travel", "worldly", "pursuit"], world: { regionId: "region.green-river", knownRegionIds: ["region.green-river"], tags: [], factionStanding: {} }, firstRun } }); }
function active(content = registry(), maxAge = 200, contentVersion = CONTENT01_VERSION, firstRun = false, seed = "content01-test") { const state = offered(maxAge, contentVersion, firstRun, seed); return reduce({ state, command: { type: "START_RUN", offerId: state.run.offer.offerId, destinyId: "content01.destiny.steady" }, context: { rulesVersion: state.rulesVersion, contentVersion, content, commandId: `cmd:${seed}:start` } }).state; }
function context(content, state, commandId, extra = {}) { return { rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, content, commandId, ...extra }; }
function enter(state, eventId, content, commandId = `cmd:enter:${eventId}`) { const event = content.getEvent(state.contentVersion, eventId); const staged = validateGameState({ ...state, run: { ...state.run, events: { ...state.run.events, current: { eventId, kind: event.kind } } } }); return materializeEventParticipants(staged, content, eventId, `event:${commandId}:${eventId}`).state; }
function safeChoice(event) { return event.choices.find((choice) => choice.id === "turn-away" || choice.id === "decline" || choice.id === "consider") ?? event.choices[0]; }
function resolveCurrent(state, content, commandId) { const event = content.getEvent(state.contentVersion, state.run.events.current.eventId); const choice = safeChoice(event); return reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: event.id, optionId: choice.id }, context: context(content, state, commandId) }).state; }

test("CONTENT01-001: formal versioned pack and NPC pack load", () => { const content = registry(); assert.equal(content.get(CONTENT01_VERSION).manifest.packId, "tianfu.playable.v1"); assert.equal(content.getNpc(CONTENT01_VERSION).id, "npc.content01.v1"); });
test("CONTENT01-002: formal pack contains at least 60 unique Events", () => { assert.equal(CONTENT01_EVENTS.length, 66); assert.equal(new Set(CONTENT01_EVENTS.map((event) => event.id)).size, 66); });
test("CONTENT01-003: five named core NPCs carry stable content identities", () => { assert.deepEqual(NPC_CONTENT01_V1.coreDefinitions.map((npc) => npc.displayName), ["裴照川", "姜雪芜", "岑不归", "谢听潮", "许长安"]); });
test("CONTENT01-004: eight generated archetypes validate", () => { assert.equal(CONTENT01_ARCHETYPES.length, 8); assert.doesNotThrow(() => validateNpcPack(NPC_CONTENT01_V1)); });
test("CONTENT01-005: six Cause chains cover ten templates", () => { assert.equal(CONTENT01_CAUSE_CHAINS.length, 6); assert.equal(CONTENT01_PACK.causeTemplates.length, 10); assert.ok(CONTENT01_CAUSE_CHAINS.every((chain) => chain.templates.every((id) => CONTENT01_PACK.causeTemplates.some((template) => template.id === id)))); });
test("CONTENT01-006: onboarding content has at least six natural scenes", () => assert.ok(CONTENT01_PACK.events.filter((event) => event.directorHints.onboardingEligible).length >= 6));
test("CONTENT01-007: every action has broad candidate coverage", () => { for (const action of ["cultivate", "travel", "worldly", "pursuit"]) assert.ok(CONTENT01_PACK.events.filter((event) => event.actionAffinity?.includes(action)).length >= 10, action); });
test("CONTENT01-008: each v1 Build has at least three authored Events", () => { for (const build of ["sword", "body", "alchemy", "fortune"]) assert.ok(CONTENT01_PACK.events.filter((event) => event.directorHints.buildAffinityTags.includes(build)).length >= 3, build); });
test("CONTENT01-009: at least eight Events use RISK01 Threats", () => assert.ok(CONTENT01_PACK.events.filter((event) => event.choices.some((choice) => choice.threatId !== undefined)).length >= 8));
test("CONTENT01-010: at least ten non-Cause ordinary fallbacks exist", () => { const linked = new Set(CONTENT01_PACK.causeTemplates.flatMap((template) => template.linkedEventIds)); assert.ok(CONTENT01_PACK.events.filter((event) => !event.actionAffinity && !linked.has(event.id)).length >= 10); });
test("CONTENT01-011: salience distribution remains paced", () => { const counts = Object.groupBy(CONTENT01_PACK.events, (event) => String(event.directorHints.salience)); assert.ok((counts["1"]?.length ?? 0) >= 9); assert.ok((counts["5"]?.length ?? 0) <= 6); });
test("CONTENT01-012: Director tag vocabulary is closed", () => assert.equal(runContentPlayabilityAudit(CONTENT01_PACK).unknownTags, 0));
test("CONTENT01-013: titles and bodies are unique", () => { const audit = runContentPlayabilityAudit(CONTENT01_PACK); assert.equal(audit.duplicateTitles, 0); assert.equal(audit.duplicateBodies, 0); });
test("CONTENT01-014: Chinese authoring lengths and forbidden jargon pass", () => { const audit = runContentPlayabilityAudit(CONTENT01_PACK); assert.equal(audit.invalidTextLengths, 0); const text = Object.values(CONTENT01_ZH_CN).join("\n"); for (const term of ["SSR", "成功率", "系统提示", "Build", "Cause", "NPC好感"]) assert.equal(text.includes(term), false, term); });
test("CONTENT01-015: public text contains no hidden knowledge keys", () => assert.equal(runContentPlayabilityAudit(CONTENT01_PACK).knowledgeLeakViolations, 0));
test("CONTENT01-016: every Event has a legal direct reachability fixture", () => { const content = registry(); for (const event of CONTENT01_PACK.events) { const state = enter(active(content, 300, CONTENT01_VERSION, false, `reach:${event.id}`), event.id, content); assert.doesNotThrow(() => resolveCurrent(state, content, `cmd:reach:${event.id}`), event.id); } });
test("CONTENT01-017: all core NPCs have reachable participant scenes", () => { const content = registry(); for (const npc of NPC_CONTENT01_V1.coreDefinitions) { const event = CONTENT01_PACK.events.find((candidate) => candidate.participants?.some((entry) => entry.source.kind === "core" && entry.source.npcDefinitionId === npc.id)); const state = enter(active(content), event.id, content); assert.ok(Object.values(state.run.npcs.byId).some((instance) => instance.definitionId === npc.id), npc.id); } });
test("CONTENT01-018: generated participant names are deterministic and public-safe", () => { const content = registry(); const first = enter(active(content, 200, CONTENT01_VERSION, false, "generated-fixed"), "content01.road.help", content); const second = enter(active(content, 200, CONTENT01_VERSION, false, "generated-fixed"), "content01.road.help", content); assert.deepEqual(first.run.events.current.participantBindings, second.run.events.current.participantBindings); assert.deepEqual(first.run.rng, second.run.rng); const view = new ServerViewModelBuilder(content).build(first); assert.equal(typeof view.currentInteraction.body.participants[0].displayName, "string"); assert.equal(JSON.stringify(view.currentInteraction.body).includes("npc:generated"), false); });
test("CONTENT01-019: every Build route can reach formed through authored evidence", () => { const content = registry(); for (const build of ["sword", "body", "alchemy", "fortune"]) { let state = active(content, 500, CONTENT01_VERSION, false, `build:${build}`); const events = CONTENT01_PACK.events.filter((event) => event.tags.includes(`build-${build}`) && event.choices.some((choice) => choice.id === "engage")); for (const event of events) { state = enter(state, event.id, content); state = reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: event.id, optionId: "engage" }, context: context(content, state, `cmd:build:${build}:${event.id}`) }).state; } assert.ok(["formed", "refined"].includes(buildStage(content.getBuild(state.contentVersion).rules, state.run.build.affinities[`build.${build}`].affinityBps)), build); } });
test("CONTENT01-020: representative origin from every Cause chain matures and echoes", () => { const content = registry(); const origins = ["content01.pei.broken-blade", "content01.jiang.herb-price", "content01.cen.shoulder-road", "content01.xie.secret-map", "content01.xu.mortal-letter", "content01.road.help"]; for (const originId of origins) { let state = enter(active(content, 500, CONTENT01_VERSION, false, `cause:${originId}`), originId, content); state = reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: originId, optionId: "bind-1" }, context: context(content, state, `cmd:cause:${originId}:origin`) }).state; const causeId = Object.keys(state.run.causes.byId)[0]; for (let step = 0; step < 8 && state.run.causes.byId[causeId].echoCount === 0; step += 1) { if (state.run.events.current !== undefined) state = resolveCurrent(state, content, `cmd:cause:${originId}:${step}:resolve`); else state = reduce({ state, command: { type: "CHOOSE_ACTION", actionId: "cultivate" }, context: context(content, state, `cmd:cause:${originId}:${step}:advance`) }).state; } assert.ok(state.run.causes.byId[causeId].echoCount >= 1, originId); } });
test("CONTENT01-021: actor unavailable transform and expire remain traceable", () => { const content = registry(); let mortal = enter(active(content), "content01.xu.mortal-letter", content); mortal = reduce({ state: mortal, command: { type: "CHOOSE_EVENT_OPTION", eventId: "content01.xu.mortal-letter", optionId: "bind-1" }, context: context(content, mortal, "cmd:mortal-origin") }).state; const old = Object.values(mortal.run.causes.byId)[0]; const actorId = old.actorIdsByRole.actor; const transformed = advanceCauses(mortal, content, mortal.contentVersion, { rulesVersion: mortal.rulesVersion, contentVersion: mortal.contentVersion, content, commandId: "cmd:mortal-transform", actorStatusById: { [actorId]: "unavailable" } }); assert.equal(transformed.run.causes.byId[old.causeId].state, "resolved"); assert.ok(Object.values(transformed.run.causes.byId).some((cause) => cause.templateId === "content01.cause.mortal-missed" && cause.causeId !== old.causeId)); let road = enter(active(content), "content01.road.help", content); road = reduce({ state: road, command: { type: "CHOOSE_EVENT_OPTION", eventId: "content01.road.help", optionId: "bind-1" }, context: context(content, road, "cmd:road-origin") }).state; const roadCause = Object.values(road.run.causes.byId)[0]; const expired = advanceCauses(road, content, road.contentVersion, { rulesVersion: road.rulesVersion, contentVersion: road.contentVersion, content, commandId: "cmd:road-expire", actorStatusById: { [roadCause.actorIdsByRole.actor]: "unavailable" } }); assert.equal(expired.run.causes.byId[roadCause.causeId].state, "expired"); });
test("CONTENT01-022: short life ends legally within five effective nodes", () => { const content = registry(); let state = active(content, 24, CONTENT01_VERSION, false, "short-life"); while (state.run.status === "active" && state.run.nodeIndex <= 5) { state = state.run.events.current === undefined ? reduce({ state, command: { type: "CHOOSE_ACTION", actionId: "cultivate" }, context: context(content, state, `cmd:short:${state.stateVersion}`) }).state : resolveCurrent(state, content, `cmd:short:${state.stateVersion}`); } assert.equal(state.run.status, "dying"); assert.equal(state.run.deathRecord.category, "lifespan"); assert.ok(state.run.nodeIndex >= 3 && state.run.nodeIndex <= 5); });
test("CONTENT01-023: long life reaches thirty nodes without forced coverage or unbounded Director memory", () => { const content = registry(); let state = active(content, 800, CONTENT01_VERSION, false, "long-life"); while (state.run.status === "active" && state.run.nodeIndex < 30) state = state.run.events.current === undefined ? reduce({ state, command: { type: "CHOOSE_ACTION", actionId: ["cultivate", "travel", "worldly", "pursuit"][state.run.nodeIndex % 4] }, context: context(content, state, `cmd:long:${state.stateVersion}`) }).state : resolveCurrent(state, content, `cmd:long:${state.stateVersion}`); assert.ok(state.run.nodeIndex >= 30); assert.ok(state.run.director.recentScenes.length <= 8); assert.ok(new Set(state.run.events.history.map((entry) => entry.eventId)).size < CONTENT01_PACK.events.length); assert.ok(Object.keys(state.run.npcs.byId).filter((id) => id.startsWith("npc:core:")).length < 5); assert.equal(Object.values(state.run.build.affinities).filter((affinity) => ["formed", "refined"].includes(buildStage(content.getBuild(state.contentVersion).rules, affinity.affinityBps))).length, 0); });
test("CONTENT01-024: deterministic simulation smoke has no failure or deadlock", () => { const first = runContentSimulation({ runsPerPolicy: 2, maxActions: 10 }); const second = runContentSimulation({ runsPerPolicy: 2, maxActions: 10 }); assert.deepEqual(first, second); assert.equal(first.runtimeFailures, 0); assert.equal(first.deadlocks, 0); assert.equal(first.AIcalls, 0); });
test("CONTENT01-025: command log Snapshot and replay preserve sequence, RNG and hash", () => { const content = registry(); const initial = active(content, 300, CONTENT01_VERSION, true, "replay"); const firstEnvelope = { commandId: "cmd:content01:replay:action", playerId: initial.run.playerId, runId: initial.run.runId, expectedStateVersion: initial.stateVersion, rulesVersion: initial.rulesVersion, contentVersion: initial.contentVersion, clientPlatform: "dev", clientBuild: "content01", command: { type: "CHOOSE_ACTION", actionId: "travel" } }; const first = executeLoggedCommand(initial, createCommandLog(initial), firstEnvelope, {}, content); const current = first.output.state.run.events.current; const event = content.getEvent(initial.contentVersion, current.eventId); const choice = safeChoice(event); const secondEnvelope = { ...firstEnvelope, commandId: "cmd:content01:replay:choice", expectedStateVersion: first.output.state.stateVersion, command: { type: "CHOOSE_EVENT_OPTION", eventId: event.id, optionId: choice.id } }; const second = executeLoggedCommand(first.output.state, first.commandLog, secondEnvelope, {}, content); const replayed = replayCommandLog({ initialState: initial, commandLog: second.commandLog, content }); const snapshot = validateSnapshot(JSON.parse(JSON.stringify(createSnapshot(second.output.state, 2)))); assert.equal(replayed.finalRuleStateHash, ruleStateHash(second.output.state)); assert.deepEqual(replayed.state.run.rng, second.output.state.run.rng); assert.deepEqual(replayed.state.run.events.history, second.output.state.run.events.history); assert.equal(snapshot.ruleStateHash, replayed.finalRuleStateHash); });
test("CONTENT01-026: contentVersion isolates future pack changes", () => { const content = registry(); const initial = active(content, 300, CONTENT01_VERSION, true, "version-lock"); const before = reduce({ state: initial, command: { type: "CHOOSE_ACTION", actionId: "travel" }, context: context(content, initial, "cmd:version-lock") }); const future = structuredClone(CONTENT01_PACK); future.events[0].weight += 1; const { checksum: _checksum, ...manifest } = future.manifest; const sealed = sealContentPack({ ...future, manifest: { ...manifest, contentVersion: "content01.v2-test" } }); content.register(sealed); const after = reduce({ state: initial, command: { type: "CHOOSE_ACTION", actionId: "travel" }, context: context(content, initial, "cmd:version-lock") }); assert.deepEqual(after, before); });
test("CONTENT01-027: extension pack adds Event, archetype and Cause without Core changes", () => {
  const npc = structuredClone(NPC_CONTENT01_V1); npc.id = "npc.content01.extension"; npc.tags.push("scribe");
  npc.archetypes.push({ id: "content01.extension.archetype.scribe", displayLabel: "游方书记", tags: ["scribe", "traveler"], roleTags: ["scribe"], namePoolId: "content01.name-pool.common", traitPoolIds: ["content01.trait-pool.common"], traitCount: 2, defaultFacts: ["content01.fact.identity"], systemOwners: ["NPC01", "CONTENT01"] }); validateNpcPack(npc);
  const source = structuredClone(CONTENT01_PACK); source.npcPackId = npc.id; source.directorTags.push("scribe"); source.references.causes.push("content01.extension.cause.notebook");
  source.causeTemplates.push({ id: "content01.extension.cause.notebook", salience: 2, maturity: { minNodeDelta: 1 }, actors: [{ role: "actor", required: true }], themes: ["memory"], linkedEventIds: ["content01.extension.echo"], onActorUnavailable: { action: "expire" } });
  const hints = { salience: 2, baseWeight: 100, topicTags: ["memory"], continuityTags: ["travel"], buildAffinityTags: [], npcRoleAffinityTags: ["scribe"], worldAffinityTags: [] };
  source.events.push({ id: "content01.extension.origin", version: 1, kind: "choice", titleKey: "extension.origin.title", tags: ["extension"], weight: 100, actionAffinity: ["travel"], directorHints: hints, participants: [{ slot: "actor", source: { kind: "generated", archetypeId: "content01.extension.archetype.scribe" } }], choices: [{ id: "record", scope: "core", labelKey: "extension.origin.choice", outcomes: { success: { effects: [{ op: "ADD_CAUSE", templateId: "content01.extension.cause.notebook", salience: 2, actorBindingKeys: { actor: "actor" } }] } } }], fallback: { bodyKey: "extension.origin.body" } }, { id: "content01.extension.echo", version: 1, kind: "choice", titleKey: "extension.echo.title", tags: ["extension"], weight: 100, directorHints: { ...hints, npcRoleAffinityTags: [] }, choices: [{ id: "read", scope: "core", labelKey: "extension.echo.choice", outcomes: { success: { effects: [{ op: "ADD_CULTIVATION", amount: 100 }] } } }], fallback: { bodyKey: "extension.echo.body" } });
  const { checksum: _checksum, ...manifest } = source.manifest; const extension = sealContentPack({ ...source, manifest: { ...manifest, contentVersion: "content01.extension.v1" } }); const content = registry(extension, npc);
  let state = enter(active(content, 300, extension.manifest.contentVersion, false, "extension"), "content01.extension.origin", content); state = reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "content01.extension.origin", optionId: "record" }, context: context(content, state, "cmd:extension") }).state;
  const snapshot = validateSnapshot(JSON.parse(JSON.stringify(createSnapshot(state, 0)))); assert.equal(snapshot.ruleStateHash, ruleStateHash(state)); assert.ok(Object.values(state.run.causes.byId).some((cause) => cause.templateId === "content01.extension.cause.notebook"));
});
test("CONTENT01-028: arbitrary executable content is rejected", () => { const source = structuredClone(CONTENT01_PACK); source.events[0].script = "return state"; const { checksum: _checksum, ...manifest } = source.manifest; assert.throws(() => validateContentPack(sealContentPack({ ...source, manifest }), undefined, { getNpcPack: () => NPC_CONTENT01_V1 }), /not allowed/); });
test("CONTENT01-029: no direct death, fake item or technique system is authored", () => { const json = JSON.stringify(CONTENT01_PACK); for (const token of ["killPlayer", "setDead", "forceDeath", "END_RUN", "ADD_ITEM", "GRANT_COMPONENT"]) assert.equal(json.includes(token), false, token); assert.deepEqual(CONTENT01_PACK.references.items, []); assert.deepEqual(CONTENT01_PACK.references.components, []); });
test("CONTENT01-030: playability audit has zero hard violations and complete coverage", () => { const report = runContentPlayabilityAudit(CONTENT01_PACK); for (const key of ["unknownTags", "invalidReferences", "unreachableDefinitions", "duplicateTitles", "duplicateBodies", "invalidChoiceCounts", "invalidTextLengths", "riskViolations", "knowledgeLeakViolations", "AIorNetworkDependencies"]) assert.equal(report[key], 0, key); assert.ok(Object.values(report.buildCoverage).every((count) => count >= 3)); assert.ok(Object.values(report.npcCoverage).every((count) => count >= 3)); assert.ok(Object.values(report.causeCoverage).every((coverage) => coverage.origins >= 1 && coverage.echoes >= 1)); });
test("CONTENT01-031: Director uses indexes instead of full Event scans", () => { const content = registry(); const result = content.queryDirectorCandidates(CONTENT01_VERSION, { slot: "contextual", action: "cultivate", buildTags: ["sword"], worldTags: [], npcRoleTags: [] }); assert.ok(result.stats.candidateIdsVisited < result.stats.totalEvents); assert.ok(result.eventIds.length > 1); });
test("CONTENT01-032: ViewModel keeps hidden Cause, RNG, checks and effects private", () => { const content = registry(); let state = enter(active(content), "content01.pei.broken-blade", content); state = reduce({ state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "content01.pei.broken-blade", optionId: "bind-1" }, context: context(content, state, "cmd:view-cause") }).state; const json = JSON.stringify(new ServerViewModelBuilder(content).build(state)); for (const key of ["rootSeed", "drawIndex", "echoBudget", "difficulty", "actorIdsByRole", "EffectSpec", "participantBindings"]) assert.equal(json.includes(key), false, key); });
