import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

import { ContentRegistry, DIRECTOR_V1, runDirectorAudit, sealContentPack, validateContentPack, validateDirectorPack } from "../packages/content/src/index.ts";
import { NPC_V1, BUILD_V1 } from "../packages/content/src/index.ts";
import { applyBuildEvidence, createOfferedRun, createSnapshot, instantiateCoreNpc, recordDirectorScene, reduce, ruleStateHash, scoreDirectorEvent, selectDirectorEvent, spawnNpcFromArchetype, validateGameState, validateSnapshot } from "../packages/core/src/index.ts";
import { ServerViewModelBuilder } from "../server/src/index.ts";

const fixture = JSON.parse(fs.readFileSync(new URL("../packages/content/dev-fixtures/minimal-pack.json", import.meta.url), "utf8"));
function registry(pack = fixture) { const value = new ContentRegistry(); value.register(pack); return value; }
function offered(contentVersion = "dev-0.1.0", seed = "director-seed", firstRun = true) { return createOfferedRun({ schemaVersion: 2, rulesVersion: "2.0.0", contentVersion, runId: `run:${contentVersion}`, playerId: "player:director", rootSeed: seed, metaView: { unlocks: [], entitlements: [], discoveries: [] }, fixture: { offerId: "offer:director", destinyIds: ["a", "b", "c"], age: 20, maxAge: 200, runName: "Director", realm: { id: "mortal", order: 0, cultivation: 0 }, attributes: { insight: 10, body: 10, spiritSense: 10, fortune: 10 }, resources: { spiritStone: 0, items: {} }, availableActions: ["cultivate", "travel", "worldly", "pursuit"], world: { regionId: "dev.start", knownRegionIds: ["dev.start"], tags: [], factionStanding: {} }, firstRun } }); }
function active(content = registry(), contentVersion = "dev-0.1.0", seed = "director-seed", firstRun = true) { const state = offered(contentVersion, seed, firstRun); return reduce({ state, command: { type: "START_RUN", offerId: "offer:director", destinyId: "a" }, context: { rulesVersion: "2.0.0", contentVersion, content, commandId: "cmd:director:start" } }).state; }
function reseal(source, contentVersion) { const copy = structuredClone(source); const { checksum: _checksum, ...manifest } = copy.manifest; return sealContentPack({ ...copy, manifest: { ...manifest, contentVersion } }); }
function recent(state, scenes) { return validateGameState({ ...state, run: { ...state.run, director: { ...state.run.director, recentScenes: scenes } } }); }
function hints(overrides = {}) { return { salience: 2, baseWeight: 100, topicTags: ["choice"], continuityTags: ["life"], buildAffinityTags: [], npcRoleAffinityTags: [], worldAffinityTags: [], ...overrides }; }

test("P1 lifespan remains above Director and consumes no Director RNG", () => { const content = registry(); let state = active(content); state = validateGameState({ ...state, run: { ...state.run, age: 199, maxAge: 200 } }); const before = state.run.rng.streams.director.drawIndex; const result = reduce({ state, command: { type: "CHOOSE_ACTION", actionId: "cultivate" }, context: { rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, content, commandId: "cmd:terminal" } }); assert.equal(result.state.run.status, "dying"); assert.equal(result.state.run.rng.streams.director.drawIndex, before); });
test("P2 onboarding precedes contextual selection", () => { const content = registry(); const result = selectDirectorEvent(active(content), "cultivate", content, ["P2", "P4", "P5", "P6"]); assert.equal(result.trace.selectedPrecedenceLevel, "P2"); assert.equal(result.trace.selectedEventId, "dev.first-choice"); });
test("P3 Cause echo precedes P4-P6 in reducer", () => { const content = registry(); let state = active(content, undefined, undefined, false); state = validateGameState({ ...state, run: { ...state.run, causes: { byId: { c: { causeId: "c", templateId: "cause.rescued-stranger", originCommandId: "cmd:c", originNodeIndex: 0, originAge: 20, actorIdsByRole: { rescuedNpc: "npc:test:1" }, themes: ["rescue"], salience: 3, visibility: "hidden", state: "eligible", maturity: { minNode: 0, minAge: 20, conditions: [] }, eligibleSinceNode: 0, eligibleAge: 20, echoBudget: 1, echoCount: 0, facts: {}, linkedEventIds: ["dev.rescue-echo-a"] } } } } }); const result = reduce({ state, command: { type: "CHOOSE_ACTION", actionId: "worldly" }, context: { rulesVersion: state.rulesVersion, contentVersion: state.contentVersion, content, commandId: "cmd:cause" } }); assert.equal(result.state.run.events.current.eventId, "dev.rescue-echo-a"); assert.equal(result.trace.selector.some((entry) => entry.tier === "P3"), true); });
test("P4 core NPC scene requires a met active core actor", () => { const source = structuredClone(fixture); source.events.at(-1).directorHints = hints({ npcRoleAffinityTags: ["mentor"] }); const pack = reseal(source, "director-p4"); const content = registry(pack); let state = active(content, pack.manifest.contentVersion, undefined, false); state = instantiateCoreNpc(state, NPC_V1, "dev.mysterious-mentor", "event:intro").state; const result = selectDirectorEvent(state, "worldly", content, ["P4"]); assert.equal(result.trace.selectedPrecedenceLevel, "P4"); assert.equal(result.state.run.director.recentScenes.at(-1).actorIds.length, 1); });
test("P5 action context precedes ordinary fallback", () => { const content = registry(); const result = selectDirectorEvent(active(content, undefined, undefined, false), "travel", content, ["P5", "P6"]); assert.equal(result.trace.selectedPrecedenceLevel, "P5"); assert.equal(result.trace.selectedEventId, "dev.first-choice"); });
test("P6 ordinary fallback is available", () => { const content = registry(); const result = selectDirectorEvent(active(content, undefined, undefined, false), "travel", content, ["P6"]); assert.equal(result.trace.selectedPrecedenceLevel, "P6"); assert.equal(result.trace.selectedEventId, "dev.ordinary-fallback"); });
test("zero candidates consume no Director RNG", () => { const content = registry(); const state = active(content, undefined, undefined, false); const result = selectDirectorEvent(state, "travel", content, ["P4"]); assert.equal(result.trace.logicalRngRequests, 0); assert.deepEqual(result.state.run.rng, state.run.rng); });
test("one candidate is direct and consumes no Director RNG", () => { const content = registry(); const state = active(content, undefined, undefined, false); const result = selectDirectorEvent(state, "travel", content, ["P6"]); assert.equal(result.trace.logicalRngRequests, 0); assert.equal(result.trace.candidateCount, 1); });
test("multiple candidates make one logical Director RNG request", () => { const source = structuredClone(fixture); source.events.push({ ...structuredClone(source.events.at(-1)), id: "dev.ordinary-two" }); const pack = reseal(source, "director-multi"); const content = registry(pack); const result = selectDirectorEvent(active(content, pack.manifest.contentVersion, "multi", false), "travel", content, ["P6"]); assert.equal(result.trace.logicalRngRequests, 1); assert.ok(result.rngDraws.length >= 1); assert.ok(result.rngDraws.every((draw) => draw.stream === "director")); });
test("candidate ordering is canonical across content insertion order", () => { const a = structuredClone(fixture); a.events.push({ ...structuredClone(a.events.at(-1)), id: "dev.ordinary-two" }); const pa = reseal(a, "director-order-a"); const b = structuredClone(a); b.events.reverse(); const pb = reseal(b, "director-order-b"); const ca = registry(pa); const cb = registry(pb); const ra = selectDirectorEvent(active(ca, pa.manifest.contentVersion, "same", false), "travel", ca, ["P6"]); const rb = selectDirectorEvent(active(cb, pb.manifest.contentVersion, "same", false), "travel", cb, ["P6"]); assert.equal(ra.trace.selectedEventId, rb.trace.selectedEventId); });
test("action affinity contributes frozen score bonus", () => { const content = registry(); const state = active(content, undefined, undefined, false); const scored = scoreDirectorEvent(state, content.getEvent(state.contentVersion, "dev.first-choice"), "cultivate", content, "P5"); assert.ok(scored.reasons.includes("action-affinity")); assert.ok(scored.weight >= 180); });
test("emerging Build affinity contributes only projection metadata and score", () => { const content = registry(); let state = active(content, undefined, undefined, false); state = applyBuildEvidence(state, BUILD_V1, { buildId: "build.sword", amount: 2500, reasonTag: "test" }, { commandId: "cmd:build", sourceRef: "test" }).state; const scored = scoreDirectorEvent(state, content.getEvent(state.contentVersion, "dev.first-choice"), "cultivate", content, "P5"); assert.ok(scored.reasons.includes("build-emerging")); assert.deepEqual(scored.buildIds, ["build.sword"]); });
test("world affinity contributes frozen score bonus", () => { const content = registry(); const state = active(content, undefined, undefined, false); const event = { id: "x", kind: "narrative", directorHints: hints({ worldAffinityTags: ["dev.start"] }) }; const withWorld = { ...state, run: { ...state.run, world: { ...state.run.world, tags: ["dev.start"] } } }; assert.ok(scoreDirectorEvent(withWorld, event, "travel", content, "P5").reasons.includes("world-affinity")); });
test("recent NPC continuity contributes score without mutating NPC", () => { const content = registry(); let state = instantiateCoreNpc(active(content, undefined, undefined, false), NPC_V1, "dev.mysterious-mentor", "intro").state; const id = Object.keys(state.run.npcs.byId)[0]; state = recent(state, [{ eventId: "old", nodeIndex: 0, slot: "P4", salience: 2, topicTags: [], continuityTags: [], actorIds: [id], buildIds: [] }]); const before = structuredClone(state.run.npcs); const scored = scoreDirectorEvent(state, { id: "x", kind: "narrative", directorHints: hints({ npcRoleAffinityTags: ["mentor"] }) }, "travel", content, "P4"); assert.ok(scored.reasons.includes("npc-continuity")); assert.deepEqual(state.run.npcs, before); });
test("continuity overlap is capped deterministically", () => { const content = registry(); const state = recent(active(content, undefined, undefined, false), [{ eventId: "old", nodeIndex: 0, slot: "P5", salience: 1, topicTags: [], continuityTags: ["a", "b", "c", "d"], actorIds: [], buildIds: [] }]); const score = scoreDirectorEvent(state, { id: "x", kind: "narrative", directorHints: hints({ continuityTags: ["a", "b", "c", "d"] }) }, "travel", content, "P5"); assert.equal(score.reasons.filter((reason) => reason.startsWith("continuity:")).length, 4); assert.ok(score.weight <= 100 + 60 + 20); });
test("novel topic receives novelty bonus", () => { const content = registry(); const score = scoreDirectorEvent(active(content, undefined, undefined, false), { id: "x", kind: "narrative", directorHints: hints({ topicTags: ["new"] }) }, "travel", content, "P5"); assert.ok(score.reasons.includes("topic-novelty")); });
test("exact recent event receives repetition penalty", () => { const content = registry(); const state = recent(active(content, undefined, undefined, false), [{ eventId: "x", nodeIndex: 0, slot: "P5", salience: 1, topicTags: ["old"], continuityTags: [], actorIds: [], buildIds: [] }]); const score = scoreDirectorEvent(state, { id: "x", kind: "narrative", directorHints: hints({ topicTags: ["old"] }) }, "travel", content, "P5"); assert.ok(score.reasons.includes("event-repeat-penalty")); });
test("consecutive topic penalty is bounded", () => { const content = registry(); const scenes = [0, 1, 2].map((nodeIndex) => ({ eventId: `e${nodeIndex}`, nodeIndex, slot: "P5", salience: 1, topicTags: ["same"], continuityTags: [], actorIds: [], buildIds: [] })); const base = active(content, undefined, undefined, false); const score = scoreDirectorEvent(recent({ ...base, run: { ...base.run, nodeIndex: 3 } }, scenes), { id: "x", kind: "narrative", directorHints: hints({ topicTags: ["same"], baseWeight: 200 }) }, "travel", content, "P5"); assert.ok(score.reasons.includes("topic-repeat-penalty")); assert.ok(score.weight >= 1); });
test("major scene gap excludes random major candidates", () => { const content = registry(); const base = active(content, undefined, undefined, false); const state = recent({ ...base, run: { ...base.run, nodeIndex: 3 } }, [{ eventId: "major", nodeIndex: 2, slot: "P5", salience: 4, topicTags: [], continuityTags: [], actorIds: [], buildIds: [] }]); const score = scoreDirectorEvent(state, { id: "x", kind: "narrative", directorHints: hints({ salience: 4 }) }, "travel", content, "P5"); assert.equal(score.exclusionReason, "major-gap"); });
test("random danger gap excludes consecutive danger", () => { const content = registry(); const lethal = content.getRisk("dev-0.1.0").threats.find((threat) => threat.lethalityPolicy?.lethalOnFailure); const base = active(content, undefined, undefined, false); const state = recent({ ...base, run: { ...base.run, nodeIndex: 2 } }, [{ eventId: "danger", nodeIndex: 1, slot: "P5", salience: 2, topicTags: [], continuityTags: [], actorIds: [], buildIds: [], riskTier: "lethal" }]); const score = scoreDirectorEvent(state, { id: "x", kind: "choice", choices: [{ threatId: lethal.id }], directorHints: hints() }, "travel", content, "P5"); assert.equal(score.exclusionReason, "danger-gap"); });
test("authored Cause echo bypasses random major pacing", () => { const content = registry(); const state = active(content, undefined, undefined, false); const recorded = recordDirectorScene(state, "dev.rescue-echo-a", content, "P3", { causeId: "cause:1" }); assert.equal(recorded.run.director.recentScenes.at(-1).slot, "P3"); assert.equal(recorded.run.director.recentScenes.at(-1).causeId, "cause:1"); });
test("short life does not require forced system coverage", () => { const state = active(); assert.deepEqual(state.run.director.recentScenes, []); assert.equal(state.run.director.profileId, "first_run"); });
test("long life keeps only bounded recent scene memory", () => { const content = registry(); let state = active(content, undefined, undefined, false); for (let index = 0; index < 20; index += 1) state = recordDirectorScene({ ...state, run: { ...state.run, nodeIndex: index } }, "dev.ordinary-fallback", content, "P6"); assert.equal(state.run.director.recentScenes.length, DIRECTOR_V1.rules.recentWindowSize); });
test("unresolved death is not Director authority", () => { const text = fs.readFileSync(new URL("../packages/core/src/director.ts", import.meta.url), "utf8"); assert.equal(/deathRecord|status:\s*["']dying/.test(text), false); });
test("Director selection does not fabricate Cause, NPC, Build or rewards", () => { const content = registry(); const state = active(content, undefined, undefined, false); const result = selectDirectorEvent(state, "travel", content, ["P5", "P6"]); assert.strictEqual(result.state.run.causes, state.run.causes); assert.strictEqual(result.state.run.npcs, state.run.npcs); assert.strictEqual(result.state.run.build, state.run.build); assert.strictEqual(result.state.run.resources, state.run.resources); });
test("scene memory contains only compact references", () => { const content = registry(); const result = selectDirectorEvent(active(content), "travel", content, ["P2"]); const json = JSON.stringify(result.state.run.director.recentScenes[0]); for (const forbidden of ["bodyKey", "choices", "outcomes", "effects", "dialogue"]) assert.equal(json.includes(forbidden), false); });
test("snapshot roundtrip preserves Director state and hash", () => { const content = registry(); const state = selectDirectorEvent(active(content), "travel", content, ["P2"]).state; const snapshot = validateSnapshot(JSON.parse(JSON.stringify(createSnapshot(state, 0)))); assert.deepEqual(snapshot.state.run.director, state.run.director); assert.equal(snapshot.ruleStateHash, ruleStateHash(state)); });
test("ViewModel does not expose Director weights, candidates or trace", () => { const content = registry(); const state = selectDirectorEvent(active(content), "travel", content, ["P2"]).state; const json = JSON.stringify(new ServerViewModelBuilder(content).build(state)); for (const secret of ["baseWeight", "selectedWeight", "candidateCount", "director", "continuityReasons"]) assert.equal(json.includes(secret), false, secret); });
test("contentVersion locks Director pack selection", () => { const content = registry(); assert.equal(content.getDirector("dev-0.1.0").id, "director.v1"); assert.equal(content.getDirector("dev-0.1.0").rulesVersion, "2.0.0"); });
test("custom EventDefinition metadata registers without Core change", () => { const source = structuredClone(fixture); source.events.at(-1).directorHints = hints({ topicTags: ["ordinary"] }); const pack = reseal(source, "director-custom-event"); assert.doesNotThrow(() => registry(pack)); });
test("custom Build tag participates through indexed metadata", () => { const content = registry(); const query = content.queryDirectorCandidates("dev-0.1.0", { slot: "contextual", buildTags: ["sword"] }); assert.ok(query.eventIds.includes("dev.first-choice")); });
test("custom NPC role participates through indexed metadata", () => { const source = structuredClone(fixture); source.events.at(-1).directorHints = hints({ npcRoleAffinityTags: ["wanderer"] }); const pack = reseal(source, "director-npc-role"); const content = registry(pack); let state = active(content, pack.manifest.contentVersion, undefined, false); state = spawnNpcFromArchetype(state, NPC_V1, { archetypeId: "npc.archetype.wanderer", sourceRef: "test" }).state; const query = content.queryDirectorCandidates(pack.manifest.contentVersion, { slot: "contextual", npcRoleTags: ["wanderer"] }); assert.ok(query.eventIds.includes("dev.ordinary-fallback")); });
test("5000-event registry query visits only indexed contextual candidates", () => { const source = structuredClone(fixture); for (let index = 0; index < 5000; index += 1) source.events.push({ id: `scale.${String(index).padStart(4, "0")}`, version: 1, kind: "narrative", titleKey: "scale", tags: [], weight: 1, actionAffinity: [index < 50 ? "cultivate" : "travel"], fallback: { bodyKey: "scale" } }); const pack = reseal(source, "director-scale"); const content = registry(pack); const query = content.queryDirectorCandidates(pack.manifest.contentVersion, { slot: "contextual", action: "cultivate" }); assert.equal(query.stats.totalEvents, fixture.events.length + 5000); assert.equal(query.stats.candidateIdsVisited, 51); });
test("50 repeated indexed selections remain deterministic", () => { const content = registry(); const state = active(content, undefined, "repeat", false); const outputs = Array.from({ length: 50 }, () => selectDirectorEvent(state, "travel", content, ["P5", "P6"]).trace.selectedEventId); assert.equal(new Set(outputs).size, 1); });
test("director-audit reports clean baseline", () => { const report = runDirectorAudit(fixture); assert.ok(report.eventDefinitions >= 4); assert.ok(report.directorAnnotatedEvents >= 4); for (const key of ["invalidWeights", "invalidTags", "precedenceViolations", "pacingViolations", "dangerPacingViolations", "determinismFailures", "replayFailures", "securityViolations"]) assert.equal(report[key], 0, key); });
test("fixed seed selection and trace are reproducible", () => { const content = registry(); const a = selectDirectorEvent(active(content, undefined, "fixed", false), "travel", content, ["P5", "P6"]); const b = selectDirectorEvent(active(content, undefined, "fixed", false), "travel", content, ["P5", "P6"]); assert.deepEqual(a, b); });
test("Director metadata rejects executable fields", () => { const source = structuredClone(fixture); source.events[0].directorHints.script = "return state"; const { checksum: _checksum, ...manifest } = source.manifest; assert.throws(() => validateContentPack(sealContentPack({ ...source, manifest })), /not allowed/); });
test("Director metadata rejects undeclared tags", () => { const source = structuredClone(fixture); source.events[0].directorHints.topicTags = ["undeclared"]; const { checksum: _checksum, ...manifest } = source.manifest; assert.throws(() => validateContentPack(sealContentPack({ ...source, manifest })), /declared/); });
test("Director pack rejects NaN and non-safe numeric rules", () => { const pack = structuredClone(DIRECTOR_V1); pack.rules.baseWeightDefault = Number.NaN; assert.throws(() => validateDirectorPack(pack)); });
test("Director pack rejects unknown fields and unowned hooks", () => { const pack = structuredClone(DIRECTOR_V1); pack.hooks = [{ id: "x" }]; assert.throws(() => validateDirectorPack(pack), /not allowed/); });
test("first-run window closes deterministically", () => { const content = registry(); const base = active(content); const state = validateGameState({ ...base, run: { ...base.run, nodeIndex: DIRECTOR_V1.rules.firstRunWindowNodes + 1 } }); const result = selectDirectorEvent(state, "travel", content, ["P2"]); assert.equal(result.state.run.events.current, undefined); });
test("first-run selection cannot change outcome RNG streams", () => { const content = registry(); const state = active(content); const result = selectDirectorEvent(state, "travel", content, ["P2"]); for (const name of ["offer", "event", "check", "npc", "world"]) assert.deepEqual(result.state.run.rng.streams[name], state.run.rng.streams[name]); });
test("selector trace records precedence, weight, RNG indexes and query stats", () => { const content = registry(); const result = selectDirectorEvent(active(content), "travel", content, ["P2"]); assert.equal(result.trace.selectedPrecedenceLevel, "P2"); assert.equal(Number.isSafeInteger(result.trace.selectedWeight), true); assert.equal(Number.isSafeInteger(result.trace.rngDrawIndexBefore), true); assert.equal(Number.isSafeInteger(result.trace.rngDrawIndexAfter), true); assert.equal(Number.isSafeInteger(result.trace.queryStats.candidateIdsVisited), true); });
test("recorded continuity references remain canonically ordered", () => { const content = registry(); const state = recordDirectorScene(active(content), "dev.first-choice", content, "P5", { actorIds: ["z", "a", "a"], buildIds: ["b", "a"] }); assert.deepEqual(state.run.director.recentScenes.at(-1).actorIds, ["a", "z"]); assert.deepEqual(state.run.director.recentScenes.at(-1).buildIds, ["a", "b"]); });
test("Director source has no platform, network, clock, AI or dynamic execution dependency", () => { const text = fs.readFileSync(new URL("../packages/core/src/director.ts", import.meta.url), "utf8"); for (const forbidden of ["wx.", "tt.", "fetch(", "Date.now", "Math.random", "eval(", "new Function", "openai", "anthropic"]) assert.equal(text.includes(forbidden), false, forbidden); });
