import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

import { ContentRegistry, NPC_V1, runParticipantBridgeAudit, sealContentPack, validateContentPack } from "../packages/content/src/index.ts";
import { createCommandLog, createOfferedRun, createSnapshot, executeLoggedCommand, materializeEventParticipants, reduce, replayCommandLog, ruleStateHash, selectDirectorEvent, validateGameState, validateSnapshot } from "../packages/core/src/index.ts";
import { CommandGateway, InMemoryGatewayStore, ServerViewModelBuilder } from "../server/src/index.ts";

const fixture = JSON.parse(fs.readFileSync(new URL("../packages/content/dev-fixtures/minimal-pack.json", import.meta.url), "utf8"));
const DEFAULT_PARTICIPANTS = [
  { slot: "eventTarget", source: { kind: "core", npcDefinitionId: "dev.mysterious-mentor" } },
  { slot: "witness", source: { kind: "generated", archetypeId: "npc.archetype.wanderer" } }
];

function pack(version = "bridge-test", participants = DEFAULT_PARTICIPANTS, mutate) {
  const copy = structuredClone(fixture); const { checksum: _checksum, ...manifest } = copy.manifest;
  copy.events[0].participants = structuredClone(participants); mutate?.(copy);
  return sealContentPack({ ...copy, manifest: { ...manifest, contentVersion: version } });
}
function registry(source = pack()) { const content = new ContentRegistry(); content.register(source); return content; }
function offered(contentVersion = "bridge-test", seed = "bridge-seed") { return createOfferedRun({ schemaVersion: 2, rulesVersion: "2.0.0", contentVersion, runId: `run:${contentVersion}`, playerId: "player:bridge", rootSeed: seed, metaView: { unlocks: [], entitlements: [], discoveries: [] }, fixture: { offerId: "offer:bridge", destinyIds: ["destiny.steady-foundation", "destiny.volatile-star", "destiny.hidden-mentor"], age: 20, maxAge: 200, runName: "Bridge", realm: { id: "mortal", order: 0, cultivation: 0 }, attributes: { insight: 10, body: 10, spiritSense: 10, fortune: 10 }, resources: { spiritStone: 0, items: {} }, availableActions: ["cultivate", "travel", "worldly", "pursuit"], world: { regionId: "dev.start", knownRegionIds: ["dev.start"], tags: [], factionStanding: {} }, firstRun: true } }); }
function active(content = registry(), contentVersion = "bridge-test", seed = "bridge-seed") { return reduce({ state: offered(contentVersion, seed), command: { type: "START_RUN", offerId: "offer:bridge", destinyId: "destiny.steady-foundation" }, context: { rulesVersion: "2.0.0", contentVersion, content, commandId: "cmd:bridge:start" } }).state; }
function enter(content = registry(), contentVersion = "bridge-test", seed = "bridge-seed", commandId = "cmd:bridge:action") { const state = active(content, contentVersion, seed); return reduce({ state, command: { type: "CHOOSE_ACTION", actionId: "travel" }, context: { rulesVersion: state.rulesVersion, contentVersion, content, commandId } }); }
let invalidSequence = 0;
function invalid(mutator) { const source = pack(`invalid:${invalidSequence++}`); mutator(source.events[0]); const { checksum: _checksum, ...manifest } = source.manifest; return sealContentPack({ ...source, manifest }); }

test("BRIDGE-001: schema accepts core and generated participants", () => assert.doesNotThrow(() => validateContentPack(pack())));
test("BRIDGE-002: unknown core definition is rejected", () => assert.throws(() => validateContentPack(invalid((event) => { event.participants[0].source.npcDefinitionId = "missing"; })), /unknown reference/));
test("BRIDGE-003: unknown archetype is rejected", () => assert.throws(() => validateContentPack(invalid((event) => { event.participants[1].source.archetypeId = "missing"; })), /unknown reference/));
test("BRIDGE-004: duplicate participant slot is rejected", () => assert.throws(() => validateContentPack(pack("duplicate-slot", [{ slot: "actor", source: { kind: "core", npcDefinitionId: "dev.mysterious-mentor" } }, { slot: "actor", source: { kind: "generated", archetypeId: "npc.archetype.wanderer" } }])), /duplicate/));
for (const [index, slot] of ["", "1actor", "actor slot", "actor.x", "x".repeat(65)].entries()) test(`BRIDGE-005.${index}: unsafe slot is rejected`, () => assert.throws(() => validateContentPack(pack(`unsafe-${index}`, [{ slot, source: { kind: "core", npcDefinitionId: "dev.mysterious-mentor" } }])), /slot|non-empty/));
test("BRIDGE-006: participant unknown field is rejected", () => assert.throws(() => validateContentPack(invalid((event) => { event.participants[0].npcId = "injected"; })), /not allowed/));
test("BRIDGE-007: source unknown field is rejected", () => assert.throws(() => validateContentPack(invalid((event) => { event.participants[0].source.traits = ["injected"]; })), /not allowed/));
test("BRIDGE-008: executable materializer is rejected", () => assert.throws(() => validateContentPack(invalid((event) => { event.participants[0].source.script = "return state"; })), /not allowed/));
test("BRIDGE-009: Director selection has no NPC side effects", () => { const content = registry(); const selected = selectDirectorEvent(active(content), "travel", content, ["P2", "P4", "P5", "P6"]); assert.equal(Object.keys(selected.state.run.npcs.byId).length, 0); });
test("BRIDGE-010: reducer materializes declared participants after selection", () => { const output = enter(); assert.deepEqual(Object.keys(output.state.run.events.current.participantBindings), ["eventTarget", "witness"]); assert.equal(Object.keys(output.state.run.npcs.byId).length, 2); });
test("BRIDGE-011: active scene has deterministic event instance identity", () => assert.equal(enter(undefined, undefined, undefined, "cmd:instance").state.run.events.current.instanceId, "event:cmd:instance:dev.first-choice"));
test("BRIDGE-012: core participant uses stable identity", () => assert.equal(enter().state.run.events.current.participantBindings.eventTarget, "npc:core:dev.mysterious-mentor"));
test("BRIDGE-013: core participant consumes no NPC RNG", () => { const content = registry(pack("core-only", [DEFAULT_PARTICIPANTS[0]])); const before = active(content, "core-only").run.rng.streams.npc.drawIndex; assert.equal(enter(content, "core-only").state.run.rng.streams.npc.drawIndex, before); });
test("BRIDGE-014: core NPC is reused and never duplicated", () => { const output = enter(); const first = output.state; const current = { eventId: "dev.first-choice", kind: "choice" }; const reset = validateGameState({ ...first, run: { ...first.run, events: { ...first.run.events, current } } }); const again = materializeEventParticipants(reset, registry(), "dev.first-choice", "event:again").state; assert.equal(Object.values(again.run.npcs.byId).filter((npc) => npc.definitionId === "dev.mysterious-mentor").length, 1); });
test("BRIDGE-015: generated participant uses generated identity", () => assert.match(enter().state.run.events.current.participantBindings.witness, /^npc:generated:/));
test("BRIDGE-016: generated participant is created once for an active scene", () => { const output = enter(); const content = registry(); const repeated = materializeEventParticipants(output.state, content, "dev.first-choice", output.state.run.events.current.instanceId); assert.strictEqual(repeated.state, output.state); assert.equal(repeated.rngDraws.length, 0); });
test("BRIDGE-017: generated materialization only advances npc stream", () => { const before = active(); const output = enter(); for (const stream of Object.keys(before.run.rng.streams)) if (stream !== "npc" && stream !== "director") assert.equal(output.state.run.rng.streams[stream].drawIndex, before.run.rng.streams[stream].drawIndex, stream); assert.ok(output.state.run.rng.streams.npc.drawIndex > before.run.rng.streams.npc.drawIndex); });
test("BRIDGE-018: fixed seed materialization is reproducible", () => assert.deepEqual(enter(undefined, undefined, "fixed"), enter(undefined, undefined, "fixed")));
test("BRIDGE-019: declaration order does not change bindings or NPC RNG", () => { const a = pack("order-a", DEFAULT_PARTICIPANTS); const b = pack("order-b", [...DEFAULT_PARTICIPANTS].reverse()); const ca = registry(a); const cb = registry(b); const ra = enter(ca, "order-a", "order-seed"); const rb = enter(cb, "order-b", "order-seed"); assert.deepEqual(ra.state.run.events.current.participantBindings, rb.state.run.events.current.participantBindings); assert.deepEqual(ra.state.run.rng.streams.npc, rb.state.run.rng.streams.npc); });
test("BRIDGE-020: every binding references a persistent NPC", () => { const state = enter().state; for (const id of Object.values(state.run.events.current.participantBindings)) assert.ok(state.run.npcs.byId[id]); });
test("BRIDGE-021: orphan participant binding is invalid state", () => { const state = enter().state; const bad = structuredClone(state); bad.run.events.current.participantBindings.witness = "npc:missing"; assert.throws(() => validateGameState(bad), /existing NPC/); });
test("BRIDGE-022: malformed persisted slot is invalid state", () => { const state = enter().state; const bad = structuredClone(state); bad.run.events.current.participantBindings["bad slot"] = bad.run.events.current.participantBindings.witness; assert.throws(() => validateGameState(bad), /invalid participant slot/); });
test("BRIDGE-023: ADD_CAUSE resolves actorBindingKeys from participant slot", () => { const entered = enter(); const state = reduce({ state: entered.state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "rescue-stranger" }, context: { rulesVersion: entered.state.rulesVersion, contentVersion: entered.state.contentVersion, content: registry(), commandId: "cmd:bridge:rescue" } }).state; const cause = Object.values(state.run.causes.byId)[0]; assert.equal(cause.actorIdsByRole.rescuedNpc, entered.state.run.events.current.participantBindings.eventTarget); });
test("BRIDGE-024: participant binding overrides spoofed context slot", () => { const entered = enter(); const state = reduce({ state: entered.state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "rescue-stranger" }, context: { rulesVersion: entered.state.rulesVersion, contentVersion: entered.state.contentVersion, content: registry(), commandId: "cmd:bridge:spoof", actorBindings: { eventTarget: "npc:spoofed" } } }).state; assert.equal(Object.values(state.run.causes.byId)[0].actorIdsByRole.rescuedNpc, "npc:core:dev.mysterious-mentor"); });
test("BRIDGE-025: NPC effects resolve the same participant slot", () => { const source = pack("npc-effect", DEFAULT_PARTICIPANTS, (copy) => { copy.events[0].choices.find((choice) => choice.id === "continue").outcomes.success.effects = [{ op: "ADJUST_NPC_RELATION", actorBindingKey: "eventTarget", affinityDelta: 7, reasonTag: "npc.reason.event" }]; }); const content = registry(source); const entered = enter(content, "npc-effect"); const id = entered.state.run.events.current.participantBindings.eventTarget; const chosen = reduce({ state: entered.state, command: { type: "CHOOSE_EVENT_OPTION", eventId: "dev.first-choice", optionId: "continue" }, context: { rulesVersion: "2.0.0", contentVersion: "npc-effect", content, commandId: "cmd:npc-effect" } }).state; assert.equal(chosen.run.npcs.byId[id].relation.affinity, 7); });
test("BRIDGE-026: ViewModel projects participant display names", () => { const content = registry(); const view = new ServerViewModelBuilder(content).build(enter(content).state); assert.deepEqual(view.currentInteraction.body.participants.map((entry) => entry.slot), ["eventTarget", "witness"]); assert.ok(view.currentInteraction.body.participants.every((entry) => typeof entry.displayName === "string")); });
test("BRIDGE-027: ViewModel does not expose binding NPC IDs", () => { const content = registry(); const view = new ServerViewModelBuilder(content).build(enter(content).state); assert.equal(JSON.stringify(view.currentInteraction.body).includes("npc:"), false); assert.equal(JSON.stringify(view.currentInteraction.body).includes("participantBindings"), false); });
test("BRIDGE-028: ViewModel excludes hidden NPC and RNG fields", () => { const content = registry(); const json = JSON.stringify(new ServerViewModelBuilder(content).build(enter(content).state)); for (const key of ["actualStatus", "significance", "promotedToA", "traitTags", "factIds", "rootSeed", "drawIndex"]) assert.equal(json.includes(`\"${key}\"`), false, key); });
test("BRIDGE-029: snapshot preserves event identity, bindings and canonical hash", () => { const state = enter().state; const snapshot = validateSnapshot(JSON.parse(JSON.stringify(createSnapshot(state, 0)))); assert.deepEqual(snapshot.state.run.events.current, state.run.events.current); assert.equal(snapshot.ruleStateHash, ruleStateHash(state)); });
test("BRIDGE-030: command log replay preserves participants, RNG and hash", () => { const content = registry(); const initial = active(content); const envelope = { commandId: "cmd:bridge:logged", playerId: initial.run.playerId, runId: initial.run.runId, expectedStateVersion: initial.stateVersion, rulesVersion: initial.rulesVersion, contentVersion: initial.contentVersion, clientPlatform: "dev", clientBuild: "bridge-test", command: { type: "CHOOSE_ACTION", actionId: "travel" } }; const executed = executeLoggedCommand(initial, createCommandLog(initial), envelope, {}, content); const replayed = replayCommandLog({ initialState: initial, commandLog: executed.commandLog, content }); assert.equal(replayed.finalRuleStateHash, ruleStateHash(executed.output.state)); assert.deepEqual(replayed.state.run.events.current, executed.output.state.run.events.current); assert.deepEqual(replayed.state.run.rng, executed.output.state.run.rng); });
test("BRIDGE-031: gateway retry is idempotent with no duplicate NPC or RNG", async () => { const content = registry(); const initial = active(content); const store = new InMemoryGatewayStore(); store.seedRun(initial); const gateway = new CommandGateway({ store, content }); const request = { commandId: "cmd:bridge:gateway", playerId: initial.run.playerId, runId: initial.run.runId, expectedStateVersion: initial.stateVersion, rulesVersion: initial.rulesVersion, contentVersion: initial.contentVersion, clientPlatform: "dev", clientBuild: "bridge-test", command: { type: "CHOOSE_ACTION", actionId: "travel" } }; const first = await gateway.sendCommand({ playerId: initial.run.playerId }, request); const committed = store.readRun(initial.run.runId); const retry = await gateway.sendCommand({ playerId: initial.run.playerId }, request); assert.deepEqual(retry, first); assert.deepEqual(store.readRun(initial.run.runId), committed); assert.equal(Object.keys(committed.state.run.npcs.byId).length, 2); });
test("BRIDGE-032: event without participants creates no NPC and consumes no npc RNG", () => { const source = pack("no-participants", undefined); delete source.events[0].participants; const { checksum: _checksum, ...manifest } = source.manifest; const sealed = sealContentPack({ ...source, manifest }); const content = registry(sealed); const before = active(content, "no-participants"); const output = enter(content, "no-participants"); assert.equal(Object.keys(output.state.run.npcs.byId).length, 0); assert.equal(output.state.run.rng.streams.npc.drawIndex, before.run.rng.streams.npc.drawIndex); });
test("BRIDGE-033: registered NPC lookup is direct and content-version locked", () => { const content = registry(); assert.strictEqual(content.getNpcDefinition("bridge-test", "dev.mysterious-mentor"), content.getNpc("bridge-test").coreDefinitions[0]); assert.strictEqual(content.getNpcArchetype("bridge-test", "npc.archetype.wanderer"), content.getNpc("bridge-test").archetypes.find((entry) => entry.id === "npc.archetype.wanderer")); });
test("BRIDGE-034: core definitions remain lazy and are not preloaded", () => { const state = active(); assert.equal(Object.keys(state.run.npcs.byId).length, 0); assert.ok(NPC_V1.coreDefinitions.length > 0); });
test("BRIDGE-035: participant bridge audit reports zero violations", () => { const report = runParticipantBridgeAudit(fixture); for (const key of ["duplicateParticipantBindings", "orphanParticipantBindings", "invalidNpcReferences", "duplicateCoreInstances", "materializationRngDrift", "causeActorBindingFailures", "knowledgeLeakViolations", "directorSideEffectViolations"]) assert.equal(report[key], 0, key); });
