import { aggregateProgressionModifiers, isValidInnateProfile, type ProgressionAggregate, type ProgressionPack } from "../../core/src/progression.ts";
import { PROGRESSION_V1, validateProgressionPack } from "./progression-v1.ts";

export interface ComboAuditResult { theoreticalProfiles: number; validProfiles: number; invalidProfiles: number; validRatio: number; modifierMinMax: Record<string, { min: number; max: number }>; hookConflicts: number; ownerCoverage: Record<string, number>; determinismFailures: number }
const numericAggregateKeys: Array<Exclude<keyof ProgressionAggregate, "sources">> = ["cultivationGainRateBps", "foundationGainRateBps", "breakthroughDifficultyDelta", "breakthroughScoreDelta", "foundationRetentionDeltaBps", "failureCultivationLossDelta", "failureFoundationLossDelta"];

export function runComboAudit(pack: ProgressionPack = PROGRESSION_V1): ComboAuditResult {
  validateProgressionPack(pack); const theoreticalProfiles = pack.spiritualRoots.length * pack.talents.length * pack.majorDestinies.length; let validProfiles = 0; let determinismFailures = 0; let hookConflicts = 0;
  const reportedKeys = [...numericAggregateKeys, "effectiveBreakthroughDifficulty", "foundationRetentionBps"]; const modifierMinMax = Object.fromEntries(reportedKeys.map((key) => [key, { min: Number.MAX_SAFE_INTEGER, max: Number.MIN_SAFE_INTEGER }])) as ComboAuditResult["modifierMinMax"];
  const ownerCoverage: Record<string, number> = {}; for (const definition of [...pack.spiritualRoots, ...pack.talents, ...pack.majorDestinies]) for (const owner of definition.systemOwners) ownerCoverage[owner] = (ownerCoverage[owner] ?? 0) + 1;
  for (const root of pack.spiritualRoots) for (const talent of pack.talents) for (const destiny of pack.majorDestinies) {
    const profile = { spiritualRoot: root.id, talentIds: [talent.id], majorDestinyId: destiny.id }; if (!isValidInnateProfile(pack, profile)) continue; validProfiles += 1;
    const first = aggregateProgressionModifiers(pack, profile); const second = aggregateProgressionModifiers({ ...pack, spiritualRoots: [...pack.spiritualRoots].reverse(), talents: [...pack.talents].reverse(), majorDestinies: [...pack.majorDestinies].reverse() }, profile); if (JSON.stringify(first) !== JSON.stringify(second)) determinismFailures += 1;
    for (const key of numericAggregateKeys) { const value = first[key]; if (!Number.isSafeInteger(value)) determinismFailures += 1; modifierMinMax[key].min = Math.min(modifierMinMax[key].min, value); modifierMinMax[key].max = Math.max(modifierMinMax[key].max, value); }
    for (const realm of pack.realms) if (realm.breakthroughDifficulty !== undefined) { const difficulty = Math.min(950, Math.max(100, realm.breakthroughDifficulty + first.breakthroughDifficultyDelta)); if (!Number.isSafeInteger(difficulty) || difficulty < 100 || difficulty > 950) determinismFailures += 1; modifierMinMax.effectiveBreakthroughDifficulty.min = Math.min(modifierMinMax.effectiveBreakthroughDifficulty.min, difficulty); modifierMinMax.effectiveBreakthroughDifficulty.max = Math.max(modifierMinMax.effectiveBreakthroughDifficulty.max, difficulty); }
    for (const base of [3_000, 4_500, 6_000]) { const retention = Math.min(8_000, Math.max(1_500, base + first.foundationRetentionDeltaBps)); if (!Number.isSafeInteger(retention) || retention < 1_500 || retention > 8_000) determinismFailures += 1; modifierMinMax.foundationRetentionBps.min = Math.min(modifierMinMax.foundationRetentionBps.min, retention); modifierMinMax.foundationRetentionBps.max = Math.max(modifierMinMax.foundationRetentionBps.max, retention); }
    const hooks = [root, talent, destiny].flatMap((definition) => definition.hooks).sort((left, right) => left.order - right.order || left.id.localeCompare(right.id)); for (let index = 1; index < hooks.length; index += 1) if (hooks[index - 1].order === hooks[index].order && hooks[index - 1].id === hooks[index].id) hookConflicts += 1;
    if (JSON.parse(JSON.stringify(profile)).majorDestinyId !== profile.majorDestinyId) determinismFailures += 1;
  }
  const invalidProfiles = theoreticalProfiles - validProfiles; return { theoreticalProfiles, validProfiles, invalidProfiles, validRatio: theoreticalProfiles === 0 ? 0 : validProfiles / theoreticalProfiles, modifierMinMax, hookConflicts, ownerCoverage: Object.fromEntries(Object.entries(ownerCoverage).sort(([a], [b]) => a.localeCompare(b))), determinismFailures };
}
