/**
 * UI02 — Tianfu-sim 2.0 in-life core-loop preview.
 *
 * DEV PREVIEW ONLY. This route is registered last in app.json and is neither the first page nor a
 * tabBar entry. It carries no gameplay rules of any kind:
 *
 *  - Every value rendered here comes from ./v2-fixtures.json, which is generated by
 *    tools/ui02-preview-fixtures.mjs through the real ServerViewModelBuilder, buildWeChatPageShell,
 *    mapCoreActionIntents, mapSpecialActionIntents and buildArchiveView.
 *  - The page never computes eligibility, difficulty, odds, cost, risk or outcome. Tapping an action
 *    submits the intent's already-built GameCommand shape and nothing else.
 *  - Production transport binding is deliberately NOT wired here; see docs/UI02_PREVIEW.md.
 *
 * Names shown for people/Causes/Builds are public display labels. Hidden Causes and hidden NPC state
 * are absent from the fixture by construction, because the server never projects them.
 */

var fixtures = null;
try {
  fixtures = require("./v2-fixtures.json");
} catch (error) {
  fixtures = null;
}

var STATE_KEYS = ["RUN_HOME", "EVENT", "SPECIAL_NODE", "LIFE_ARCHIVE"];
var STATE_LABELS = {
  RUN_HOME: "修行主页",
  EVENT: "事件",
  SPECIAL_NODE: "特殊节点",
  LIFE_ARCHIVE: "命书"
};
var VARIANT_KEYS = ["RUN_HOME_BREAKTHROUGH_BLOCKED", "RUN_HOME_NO_PLATFORM_CAPABILITY"];
var VARIANT_LABELS = {
  RUN_HOME_BREAKTHROUGH_BLOCKED: "突破未成",
  RUN_HOME_NO_PLATFORM_CAPABILITY: "能力缺省"
};

var ACTION_LABELS = { cultivate: "闭关", travel: "游历", worldly: "入世", pursuit: "追索" };
var RISK_TIER_CLASS = { low: "", caution: "is-caution", dangerous: "is-dangerous", lethal: "is-lethal" };

function text(value, fallback) {
  return typeof value === "string" && value.length > 0 ? value : fallback;
}

function number(value, fallback) {
  return typeof value === "number" && isFinite(value) ? value : fallback;
}

/** Public lifespan pressure presentation derived only from already-public age / maxAge. */
function lifespanView(run) {
  var age = number(run.age, 0);
  var maxAge = number(run.maxAge, 0);
  var remaining = Math.max(0, maxAge - age);
  var percent = maxAge > 0 ? Math.min(100, Math.round((age / maxAge) * 100)) : 0;
  return {
    age: age,
    maxAge: maxAge,
    remaining: remaining,
    percent: percent,
    pressing: remaining <= 20
  };
}

function buildRunHome(vm) {
  var run = vm.view.state.publicRun;
  var lifespan = lifespanView(run);
  var realm = run.realm || {};
  var conditions = (run.conditions || []).map(function (condition) {
    return {
      key: condition.id,
      label: condition.kind,
      stacks: number(condition.stacks, 0)
    };
  });
  var causes = (vm.view.state.publicCauses || []).map(function (cause) {
    return {
      publicId: cause.publicId,
      level: cause.level,
      label: cause.level === "explicit" ? "已知因果" : "隐约因果"
    };
  });
  var builds = (run.builds || []).map(function (build) {
    return {
      buildId: build.buildId,
      name: text(build.displayName, build.buildId),
      stageLabel: build.stage,
      dominant: build.dominant === true
    };
  });
  var people = (run.people || []).map(function (person) {
    var milestones = person.milestones || [];
    return {
      npcId: person.npcId,
      name: text(person.displayName, person.npcId),
      roles: (person.knownRoles || []).join(" · "),
      relation: [person.affinity, person.trust].filter(Boolean).join(" / "),
      status: person.knownStatus,
      milestoneCount: milestones.length
    };
  });
  var actions = vm.coreIntents.map(function (intent) {
    return {
      intentId: intent.intentId,
      label: ACTION_LABELS[intent.command.actionId] || intent.command.actionId,
      enabled: intent.enabled,
      commandType: intent.command.type,
      actionId: intent.command.actionId
    };
  });
  var special = vm.specialIntents.map(function (intent) {
    return {
      intentId: intent.intentId,
      enabled: intent.enabled,
      label: "尝试突破",
      commandType: intent.command.type,
      targetName: "",
      reason: ""
    };
  });
  var entries = run.specialActions || [];
  for (var index = 0; index < special.length; index += 1) {
    var projected = entries[index] || {};
    special[index].targetName = text((projected.targetRealm || {}).displayName, "");
    special[index].reason = projected.available === true ? "" : text(projected.blockedReasonKey, "breakthrough.unavailable");
  }
  return {
    kind: "RUN_HOME",
    runName: text(run.runName, "无名"),
    realmName: text(realm.id, "unknown"),
    realmOrder: number(realm.order, 0),
    cultivation: number(realm.cultivationBps, number(realm.cultivation, 0)),
    foundation: number(realm.realmFoundationBps, 0),
    lifespan: lifespan,
    possessions: number((run.resources || {}).spiritStone, 0),
    conditions: conditions,
    causes: causes,
    builds: builds,
    people: people,
    actions: actions,
    special: special,
    hasBuilds: builds.length > 0,
    hasPeople: people.length > 0,
    hasCauses: causes.length > 0
  };
}

function buildDecision(vm) {
  var interaction = vm.view.currentInteraction || {};
  var body = interaction.body || {};
  var participants = (body.participants || []).map(function (participant) {
    return { slot: participant.slot, name: text(participant.displayName, "未知") };
  });
  var options = (interaction.options || []).map(function (option) {
    var risk = option.riskPresentation || null;
    return {
      optionId: option.optionId,
      label: text(option.labelKey, option.optionId),
      hasRisk: risk !== null,
      tier: risk === null ? "" : risk.tier,
      tierClass: risk === null ? "" : (RISK_TIER_CLASS[risk.tier] || ""),
      canBeFatal: risk !== null && risk.canBeFatal === true,
      reasons: risk === null ? [] : (risk.reasons || [])
    };
  });
  return {
    kind: vm.pageState,
    decisionId: text(interaction.interactionId, "(none)"),
    headline: text(interaction.titleKey, "(no interaction)"),
    bodyKey: text(body.bodyKey, ""),
    state: text(interaction.interactionState, "idle"),
    participants: participants,
    options: options,
    backAllowed: vm.shell.ordinaryBackAllowed === true,
    locked: vm.shell.ordinaryBackAllowed !== true,
    hasInteraction: vm.view.currentInteraction !== undefined
  };
}

function buildArchive(vm) {
  var archive = vm.archive;
  var causes = archive.causes.map(function (cause) {
    return { publicId: cause.publicId, level: cause.level, label: cause.level === "explicit" ? "明确" : "暗示" };
  });
  var entries = archive.history.map(function (entry) {
    return {
      entryId: entry.entryId,
      kind: entry.kind,
      title: entry.titleKey,
      summary: entry.summaryKey
    };
  });
  var builds = archive.builds.map(function (build) {
    return { buildId: build.buildId, name: text(build.displayName, build.buildId), stage: build.stage, dominant: build.dominant };
  });
  var people = archive.people.map(function (person) {
    return { npcId: person.npcId, name: person.displayName, roles: (person.knownRoles || []).join(" · "), status: person.knownStatus };
  });
  var death = archive.death || null;
  return {
    kind: "LIFE_ARCHIVE",
    readOnly: true,
    runName: text(archive.runName, "无名"),
    causes: causes,
    entries: entries,
    builds: builds,
    people: people,
    hasDeath: death !== null,
    deathAge: death === null ? 0 : number(death.deathAge, 0),
    deathRealm: death === null ? "" : text(death.deathRealm, ""),
    deathCause: death === null ? "" : text(death.directCause, ""),
    wasWarned: death !== null && death.wasWarned === true,
    lifespanDeath: death !== null && death.lifespanDeath === true
  };
}

function present(key) {
  if (fixtures === null) return null;
  var entry = fixtures.states[key] || fixtures.variants[key];
  if (entry === undefined || entry === null) return null;
  var base = {
    key: key,
    label: STATE_LABELS[key] || VARIANT_LABELS[key] || key,
    pageState: entry.pageState,
    shell: entry.shell,
    capabilities: entry.view.state.capabilities,
    visibleEntries: entry.shell.visibleEntries,
    gatedEntries: []
  };
  var gated = [];
  var visible = entry.shell.visibleEntries;
  if (visible.dailyChallenge !== true) gated.push("今日命局（能力未开通）");
  if (visible.share !== true) gated.push("分享（能力未开通）");
  if (visible.commerce !== true) gated.push("商行（能力未开通）");
  if (visible.rewardedAd !== true) gated.push("广告（能力未开通）");
  base.gatedEntries = gated;
  if (key === "RUN_HOME" || key === "RUN_HOME_BREAKTHROUGH_BLOCKED" || key === "RUN_HOME_NO_PLATFORM_CAPABILITY") {
    base.runHome = buildRunHome(entry);
  } else if (key === "EVENT" || key === "SPECIAL_NODE") {
    base.decision = buildDecision(entry);
  } else if (key === "LIFE_ARCHIVE") {
    base.archive = buildArchive(entry);
  }
  return base;
}

Page({
  data: {
    ready: fixtures !== null,
    tabs: [],
    activeKey: "RUN_HOME",
    vm: null,
    lastIntent: "(尚未提交意图)"
  },

  onLoad: function () {
    var tabs = [];
    for (var index = 0; index < STATE_KEYS.length; index += 1) {
      tabs.push({ key: STATE_KEYS[index], label: STATE_LABELS[STATE_KEYS[index]] });
    }
    for (var variant = 0; variant < VARIANT_KEYS.length; variant += 1) {
      tabs.push({ key: VARIANT_KEYS[variant], label: VARIANT_LABELS[VARIANT_KEYS[variant]] + "·变体" });
    }
    this.setData({ tabs: tabs });
    this.show("RUN_HOME");
  },

  show: function (key) {
    this.setData({ activeKey: key, vm: present(key) });
  },

  onSelectTab: function (event) {
    var key = event.currentTarget.dataset.key;
    if (typeof key === "string" && key.length > 0) this.show(key);
  },

  /**
   * Intent submission boundary. In this dev preview the intent is only recorded, never sent:
   * production transport binding is explicitly later work (docs/UI02_PREVIEW.md).
   */
  onIntent: function (event) {
    var vm = this.data.vm;
    if (vm === null) return;
    var intentId = event.currentTarget.dataset.intent;
    var pool = (vm.runHome && vm.runHome.actions ? vm.runHome.actions : []).concat(vm.runHome && vm.runHome.special ? vm.runHome.special : []);
    var found = null;
    for (var index = 0; index < pool.length; index += 1) {
      if (pool[index].intentId === intentId) found = pool[index];
    }
    if (found === null) {
      this.setData({ lastIntent: "未知意图，已忽略" });
      return;
    }
    if (found.enabled !== true) {
      this.setData({ lastIntent: "意图 " + intentId + " 当前不可用（服务端投影为不可用），未提交" });
      return;
    }
    this.setData({ lastIntent: "意图 " + intentId + " → 命令 " + found.commandType + "（预览未接线，未发送）" });
  },

  onBlockedBack: function () {
    if (this.data.vm !== null && this.data.vm.decision && this.data.vm.decision.locked) {
      this.setData({ lastIntent: "该决策未落定，普通返回被服务端页面状态锁定" });
      return;
    }
    this.setData({ lastIntent: "普通返回可用" });
  }
});
