// GENERATED FILE — DO NOT HAND-EDIT.
//
// LIVEFIX06 — the full Content01 Chinese copy catalog for the v2-live client.
//
// Derived from packages/content/src/content01-v1.ts (CONTENT01_ZH_CN), which is the single
// source of truth for this wording. The strings are imported, not transcribed, so this file
// cannot drift from the source without the freshness check failing.
//
// Regenerate with:
//   node tools/content01-zh-cn-module.mjs --write
// Verify with:
//   node tools/content01-zh-cn-module.mjs
// tests/livefix06.test.mjs asserts this module equals a fresh read of the source catalog, and
// that a new source key without regeneration fails.
module.exports = [
  [
    "content01.build.alchemy.failed-brew.body",
    "药液的颜色偏了一线，这炉已经不能救人了。承认失败比把它勉强端出去更难：锅里的东西还温着，端出去就会有人喝。你要决定的是倒掉，还是自己承担。"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.consider",
    "先尝一口，弄清偏在哪一味"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.engage",
    "亲手把这炉倒掉，认下这一次失败"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.leave",
    "把炉封了，不去碰它"
  ],
  [
    "content01.build.alchemy.failed-brew.title",
    "废炉"
  ],
  [
    "content01.build.alchemy.fever.body",
    "村中热症蔓延，没有珍稀灵药，只有有限的草药和一夜不能出错的照看。药只能救一部分人，你要决定的是先顾哪一间，以及这一夜怎么轮班。"
  ],
  [
    "content01.build.alchemy.fever.choice.consider",
    "先算清药与人的数目"
  ],
  [
    "content01.build.alchemy.fever.choice.engage",
    "先顾最重的那一间，把药分下去"
  ],
  [
    "content01.build.alchemy.fever.choice.leave",
    "不接手这一夜，交给村里的人"
  ],
  [
    "content01.build.alchemy.fever.title",
    "退热"
  ],
  [
    "content01.build.alchemy.herb-sort.body",
    "三种药草外形近似，药性却相反，认错一味整炉报废。耐心辨认比一炉昂贵的丹火更要紧。三株并排摆着，你要一株一株地看过去，不能靠猜。"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.consider",
    "先把已认出的两味记牢"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.engage",
    "一株一株看过去，把三味分清"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.leave",
    "不再细辨，只取认得出的那一株"
  ],
  [
    "content01.build.alchemy.herb-sort.settle.consider",
    "你没有贪多，先把已认出的两味记牢，反复嗅过才放回去。第三株你没有碰。记得不深，却不会再认错。"
  ],
  [
    "content01.build.alchemy.herb-sort.settle.engage",
    "你一株一株看过去，把三味分清。叶片相似，气味却各走一边，认到最后手心全是汗。这一炉能不能成还难说，但你的眼力长了一分。"
  ],
  [
    "content01.build.alchemy.herb-sort.settle.leave",
    "你不再细辨，只取了认得出的那一株便走。剩下两株留在原地晾着，你也没弄清它们相不相冲。晒药的人来收摊时，天已擦黑。"
  ],
  [
    "content01.build.alchemy.herb-sort.title",
    "辨草"
  ],
  [
    "content01.build.body.boulder.body",
    "巨石堵住山道，术法并非唯一办法。筋骨与耐心也能一点点把困局挪开，只是要耗上好几日。你可以用更省力的法子绕过去，也可以咬着牙把石头一点点挪开。"
  ],
  [
    "content01.build.body.boulder.choice.consider",
    "先估一估石头的重心在哪"
  ],
  [
    "content01.build.body.boulder.choice.engage",
    "咬着牙把这块石头挪开"
  ],
  [
    "content01.build.body.boulder.choice.leave",
    "绕过去，把力气留到后面"
  ],
  [
    "content01.build.body.boulder.title",
    "移石"
  ],
  [
    "content01.build.body.carry-wounded.body",
    "伤者已经无法再走，山路却还有很长一段。背起一个人意味着把自己的退路也交给脚下：不背，他留在这里；背了，你走多慢都得背到底。"
  ],
  [
    "content01.build.body.carry-wounded.choice.consider",
    "先看清前段山路能不能过人"
  ],
  [
    "content01.build.body.carry-wounded.choice.engage",
    "背起他，走多慢都背到底"
  ],
  [
    "content01.build.body.carry-wounded.choice.leave",
    "留下他，自己先赶路"
  ],
  [
    "content01.build.body.carry-wounded.title",
    "背人下山"
  ],
  [
    "content01.build.body.cold-water.body",
    "寒潭入骨。继续停留能磨炼气血，也可能让旧伤在夜里更深一分。水面安静得看不出深浅，你要在下水之前决定，是把这口气咬住，还是今天到此为止。"
  ],
  [
    "content01.build.body.cold-water.choice.consider",
    "先看清潭底深浅再下水"
  ],
  [
    "content01.build.body.cold-water.choice.engage",
    "把气咬住，下潭走一遍"
  ],
  [
    "content01.build.body.cold-water.choice.leave",
    "今日到此为止，收身出水"
  ],
  [
    "content01.build.body.cold-water.title",
    "寒潭"
  ],
  [
    "content01.build.fortune.empty-hand.body",
    "等待多日的机缘没有出现。你按着旧记踏遍三处地方，回过神来时天已经黑了。真正留下的不是收获，而是你如何面对这次落空——以及还要不要再等一次。"
  ],
  [
    "content01.build.fortune.empty-hand.choice.consider",
    "先记下这三处，弄清错在哪一步"
  ],
  [
    "content01.build.fortune.empty-hand.choice.engage",
    "再按旧记走一处，把这一趟走完"
  ],
  [
    "content01.build.fortune.empty-hand.choice.leave",
    "收记回身，这一次就到这里"
  ],
  [
    "content01.build.fortune.empty-hand.title",
    "空手而归"
  ],
  [
    "content01.build.fortune.fork.body",
    "你沿熟路赶往山外，岔路旁却留下新鲜蹄印。熟路有行人，能按时抵达；偏路通向林深，看不清尽头。这里真正要决定的是行程与未知机会，而不是抽象的磨炼。"
  ],
  [
    "content01.build.fortune.fork.choice.climb-and-watch",
    "先登高看清偏路通向哪里"
  ],
  [
    "content01.build.fortune.fork.choice.engage",
    "循着那串蹄印走进偏路"
  ],
  [
    "content01.build.fortune.fork.choice.stay-known-road",
    "放弃偏路，按熟路按时抵达"
  ],
  [
    "content01.build.fortune.fork.title",
    "偏僻岔路"
  ],
  [
    "content01.build.fortune.hidden-stream.body",
    "你在无人在意的石缝里听见了水声。继续挖可能一无所获，也可能改写整段行程；石缝很深，出不来就得等到天黑。溪声一直在响，听不出深浅。"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.consider",
    "先听清这声音是从多深来的"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.engage",
    "顺着水声把石缝挖开"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.leave",
    "不挖了，把石缝照原样盖回"
  ],
  [
    "content01.build.fortune.hidden-stream.title",
    "石下清泉"
  ],
  [
    "content01.build.sword.guard-caravan.body",
    "商队只求平安过岭。剑锋若出得太快，原本能谈的局面会被推成死斗；慢一步，路上的风声却可能先到。你要决定的是先稳住人，还是先稳住剑。"
  ],
  [
    "content01.build.sword.guard-caravan.choice.consider",
    "先听清路上风声从哪来"
  ],
  [
    "content01.build.sword.guard-caravan.choice.engage",
    "握剑走在外侧，先稳住剑"
  ],
  [
    "content01.build.sword.guard-caravan.choice.leave",
    "不接这一趟，让商队自行过岭"
  ],
  [
    "content01.build.sword.guard-caravan.title",
    "护行"
  ],
  [
    "content01.build.sword.no-draw.body",
    "对方故意激你拔剑，把话说得很难听。真正难的并非出手，而是判断这一剑值不值得——拔了可能中了圈套，不拔也可能错过唯一的机会。"
  ],
  [
    "content01.build.sword.no-draw.choice.consider",
    "先看清这是不是圈套"
  ],
  [
    "content01.build.sword.no-draw.choice.engage",
    "按本心拔剑，接下这一场"
  ],
  [
    "content01.build.sword.no-draw.choice.leave",
    "任他骂下去，把剑按回鞘里"
  ],
  [
    "content01.build.sword.no-draw.title",
    "剑未出鞘"
  ],
  [
    "content01.build.sword.river-cut.body",
    "山涧暴涨，石上只容下脚的地方。要用剑开的不是敌人，而是一线可过之路：剑锋偏了半尺就够不着落点，偏得太多又会把整块石头劈塌。你只有一次出手的余地。"
  ],
  [
    "content01.build.sword.river-cut.choice.consider",
    "先把落点看准再动剑"
  ],
  [
    "content01.build.sword.river-cut.choice.engage",
    "出这一剑，只取那一线落点"
  ],
  [
    "content01.build.sword.river-cut.choice.leave",
    "收剑退开，涉水过涧"
  ],
  [
    "content01.build.sword.river-cut.settle.consider",
    "你没有立刻动剑，先把落点看准，又试了两遍腕上的力道，才正式出剑。一剑收势比预想中稳，这一路剑数你记住了七分。"
  ],
  [
    "content01.build.sword.river-cut.settle.engage",
    "你出剑，只取那一线落点。剑锋偏了半分，削下石棱一角，路恰好让开。手臂震得发麻，剑意反倒比先前清楚了一层。"
  ],
  [
    "content01.build.sword.river-cut.settle.leave",
    "你收剑退开，涉水过涧。水冷路远，走得比预想中慢，到对岸已经近黄昏。剑始终没有出鞘，你也没从这一趟里得到什么。"
  ],
  [
    "content01.build.sword.river-cut.title",
    "截流一剑"
  ],
  [
    "content01.cen.shared-echo.body",
    "旧伤在阴雨里同时发作。岑不归看见你按住肩头，便知道那一天的代价没有被忘记，也没有被说出口。他难得开了口，说的却只是今日的天气。"
  ],
  [
    "content01.cen.shared-echo.choice.consider",
    "只说一句今日天凉，不提旧事"
  ],
  [
    "content01.cen.shared-echo.choice.engage",
    "把当年那道伤指给他看"
  ],
  [
    "content01.cen.shared-echo.choice.leave",
    "各自走进雨里，不等对方开口"
  ],
  [
    "content01.cen.shared-echo.title",
    "伤痕相认"
  ],
  [
    "content01.cen.shield-stranger.body",
    "乱石落下时，岑不归已经站到最窄的缺口，抬头看了一眼落石的方向，随即回头等一个共同承担的决定。他没有说「你走吧」，也没有说「我挡着」。"
  ],
  [
    "content01.cen.shield-stranger.choice.read-signs",
    "先看清落石是从哪一侧来"
  ],
  [
    "content01.cen.shield-stranger.choice.take-risk",
    "站到缺口另一侧，与他一起挡"
  ],
  [
    "content01.cen.shield-stranger.choice.turn-away",
    "退到岩壁后，不接这一场"
  ],
  [
    "content01.cen.shield-stranger.title",
    "以身护人"
  ],
  [
    "content01.cen.shoulder-road.body",
    "岑不归替你挡下一击，自己也伤得不轻。他不谈恩情，只问接下来的路怎样走：是一起按原路赶，还是先在这里处理伤势再动。他的肩还在往下滴血。"
  ],
  [
    "content01.cen.shoulder-road.choice.bind-1",
    "与他同行"
  ],
  [
    "content01.cen.shoulder-road.choice.decline",
    "各自按各自的路走，不再同行"
  ],
  [
    "content01.cen.shoulder-road.title",
    "并肩负伤"
  ],
  [
    "content01.cen.stone-steps.body",
    "岑不归背石登阶，每一步都极慢，呼吸比石头还重。他不劝你跟上，也不催你离开，只在山腰留了一瓢清水。台阶还有一半，水已经凉了。"
  ],
  [
    "content01.cen.stone-steps.choice.consider",
    "先看清他走的是哪一条石阶"
  ],
  [
    "content01.cen.stone-steps.choice.engage",
    "跟上他的步子，把剩下的台阶走完"
  ],
  [
    "content01.cen.stone-steps.choice.leave",
    "喝下那瓢水，不再往上"
  ],
  [
    "content01.cen.stone-steps.title",
    "负石登阶"
  ],
  [
    "content01.destiny.echo.advantage",
    "因缘易见"
  ],
  [
    "content01.destiny.echo.body",
    "有些相逢来得早，有些旧事回来得迟。"
  ],
  [
    "content01.destiny.echo.cost",
    "行囊稍薄"
  ],
  [
    "content01.destiny.echo.hook",
    "人间旧识"
  ],
  [
    "content01.destiny.echo.title",
    "旧声"
  ],
  [
    "content01.destiny.edge.advantage",
    "敢近锋芒"
  ],
  [
    "content01.destiny.edge.body",
    "常在险处见路，也常在险处留伤。"
  ],
  [
    "content01.destiny.edge.cost",
    "岁数有折"
  ],
  [
    "content01.destiny.edge.hook",
    "断剑之人"
  ],
  [
    "content01.destiny.edge.title",
    "临锋"
  ],
  [
    "content01.destiny.steady.advantage",
    "心思澄定"
  ],
  [
    "content01.destiny.steady.body",
    "得一分安稳，也少一分骤进。"
  ],
  [
    "content01.destiny.steady.cost",
    "奇缘稍远"
  ],
  [
    "content01.destiny.steady.hook",
    "青河旧路"
  ],
  [
    "content01.destiny.steady.title",
    "守拙"
  ],
  [
    "content01.jiang.bitter-decoction.body",
    "一锅药汤气味辛烈。姜雪芜提醒其中一味药性相冲：省事与稳妥不能两全，快煎伤身，慢煎费时。她把两种代价都摆出来，剩下的由你决定要不要冒这个险。"
  ],
  [
    "content01.jiang.bitter-decoction.choice.read-signs",
    "先分清是哪一味在相冲"
  ],
  [
    "content01.jiang.bitter-decoction.choice.take-risk",
    "按快煎的法子把这锅药端下去"
  ],
  [
    "content01.jiang.bitter-decoction.choice.turn-away",
    "不冒这一炉，把火撤了"
  ],
  [
    "content01.jiang.bitter-decoction.title",
    "苦汤"
  ],
  [
    "content01.jiang.debt-echo.body",
    "姜雪芜翻到旧账那一页，没有催促，指尖停在当年记下的数目上。她只问你如今是否仍认得当年的代价：认，这页就翻过去；不认，也请把话说清。"
  ],
  [
    "content01.jiang.debt-echo.choice.consider",
    "先核一遍旧账里记的到底是什么"
  ],
  [
    "content01.jiang.debt-echo.choice.engage",
    "按当年记下的数还清"
  ],
  [
    "content01.jiang.debt-echo.choice.leave",
    "这一页不必翻，就此作罢"
  ],
  [
    "content01.jiang.debt-echo.title",
    "旧账新页"
  ],
  [
    "content01.jiang.herb-price.body",
    "姜雪芜替人止住了伤势，随后把耗去的药材与时间逐项说清，不多收，也不抹去。账目摆在桌上，谁都可以核。你要决定的是：当场认下这份人情，还是先把每一项都问明白。"
  ],
  [
    "content01.jiang.herb-price.choice.bind-1",
    "认下药债"
  ],
  [
    "content01.jiang.herb-price.choice.decline",
    "不认这份人情，只把账目看清"
  ],
  [
    "content01.jiang.herb-price.settle.bind-1",
    "你认下这份药债。姜雪芜把账目合上，说既认了便不必再算。你欠下的不只是那几味药材，还有她替人止伤耗去的半日。"
  ],
  [
    "content01.jiang.herb-price.settle.decline",
    "你把账目逐项看清，却没有认下这份人情。姜雪芜没有为难你，只把纸收了。此后她若再见你，这一笔仍是两清。"
  ],
  [
    "content01.jiang.herb-price.title",
    "药有其价"
  ],
  [
    "content01.jiang.night-clinic.body",
    "夜深后仍有人敲门。姜雪芜看过伤口，把最稳妥与最昂贵的办法都说在前面，没有替你选，也没有把话说软。她只等着你说出一个能担得起的决定。"
  ],
  [
    "content01.jiang.night-clinic.choice.consider",
    "先把最昂贵的那一种问到底"
  ],
  [
    "content01.jiang.night-clinic.choice.engage",
    "选最稳妥的那一种，当场把话说定"
  ],
  [
    "content01.jiang.night-clinic.choice.leave",
    "今夜先不开口，退出去"
  ],
  [
    "content01.jiang.night-clinic.title",
    "夜诊"
  ],
  [
    "content01.onboarding.first-breath.body",
    "晨雾尚未散尽。你盘坐下来，第一次试着把纷乱心绪收进一呼一吸之间。气息刚走过第三个周天，胸口的滞涩提醒你：这一步还太急。你可以按原路继续行功，也可以先松开半分，或者就到此收功。"
  ],
  [
    "content01.onboarding.first-breath.choice.ease-off",
    "松开半分，改用更缓的呼吸"
  ],
  [
    "content01.onboarding.first-breath.choice.keep-driving",
    "照原路继续行功，把这口气推过去"
  ],
  [
    "content01.onboarding.first-breath.choice.stop-here",
    "就到这里收功，先记住这个节奏"
  ],
  [
    "content01.onboarding.first-breath.settle.ease-off",
    "你松开半分，把急吸换成缓呼。气不再冲撞胸口，散得也慢，一圈走完比方才多花了小半日。你没有强求那一口气，只把新的节奏记了下来。"
  ],
  [
    "content01.onboarding.first-breath.settle.keep-driving",
    "你按原路把这一口气推过第三个周天。胸口先是一紧，那一处滞涩随后松开半分，气息终于连成完整的一圈。收功时掌心微热，这一坐才算真正入了门。"
  ],
  [
    "content01.onboarding.first-breath.settle.stop-here",
    "你在滞涩处停了手，没有硬推过去。这一坐所得不多，只是记住了呼吸的次序：先缓后深，急处不动。起身时晨雾刚散，日头才露。"
  ],
  [
    "content01.onboarding.first-breath.title",
    "初息"
  ],
  [
    "content01.onboarding.forked-path.body",
    "你追寻的线索在此分成两股。一股脚印清楚、方向明确；另一串痕迹像是特意留下的，过于整齐。你可以顺着清楚的那股走，也可以去试那串整齐的，或者暂时按兵不动。"
  ],
  [
    "content01.onboarding.forked-path.choice.clear-trail",
    "顺着清楚的那股脚印走"
  ],
  [
    "content01.onboarding.forked-path.choice.hold-position",
    "暂不动作，先把两股都记下"
  ],
  [
    "content01.onboarding.forked-path.choice.neat-trail",
    "去试那串过于整齐的痕迹"
  ],
  [
    "content01.onboarding.forked-path.resolution",
    "这一次追查还没有取得可以确认的新线索。"
  ],
  [
    "content01.onboarding.forked-path.settle.clear-trail",
    "你顺着清楚的那股脚印走下去。走了许久，脚印忽然混进一片乱石，再找不着了。追索眼下没有明确对象，不如先四处游历，寻到机缘再回来。"
  ],
  [
    "content01.onboarding.forked-path.settle.hold-position",
    "你哪里也没去，只把两股痕迹的位置都记下来。风把草吹得乱晃，站得越久越分不清哪一股才是新的。这一趟没有确认任何东西。"
  ],
  [
    "content01.onboarding.forked-path.settle.neat-trail",
    "你去试了那串过于整齐的痕迹。走了半日，脚印在一处断崖前停住，底下是空的。留下它的人，像是特意把你引到这里。"
  ],
  [
    "content01.onboarding.forked-path.title",
    "岔路"
  ],
  [
    "content01.onboarding.market-choice.body",
    "早市刚开。摊主收了一筐杂药，其中几味他分不清，报给外行一个偏低的数，也没有说为什么低。你可以按他给的数替他把这一筐分好，也可以先把该值多少讲清楚再动手，或者先问清他打算把这一筐卖给谁。"
  ],
  [
    "content01.onboarding.market-choice.choice.ask-source",
    "先问清他打算把这一筐卖给谁"
  ],
  [
    "content01.onboarding.market-choice.choice.haggle-fair",
    "先把这一筐该值多少讲清楚再动手"
  ],
  [
    "content01.onboarding.market-choice.choice.take-deal",
    "按他给的数替他把这一筐分好"
  ],
  [
    "content01.onboarding.market-choice.settle.ask-source",
    "你问他这一筐要卖给谁。他答得含糊，只说往北边去。你没有再问，那一筐药也始终没有分完。你多留了一个心眼，也多花去一日。"
  ],
  [
    "content01.onboarding.market-choice.settle.haggle-fair",
    "你先替他分清三味药，再把这一筐该值多少讲给他听。摊主愣了一会重新报价，多给了你一些。讲价耗去小半日，但账是当面算清的。"
  ],
  [
    "content01.onboarding.market-choice.settle.take-deal",
    "你按摊主给的数，把这一筐杂药一味一味分好。他数出几个灵石放在你手心，没有多话，也没有少给。这笔钱是从他手里出来的，你收得踏实。"
  ],
  [
    "content01.onboarding.market-choice.title",
    "早市"
  ],
  [
    "content01.onboarding.mountain-road.body",
    "一条山路在前方分成两股：靠林的一侧树影深，脚下有旧车辙；绕村的一侧路平些，能听见炊烟，没有新鲜的脚印。没有人为你担保，也没有人为你指路。要紧的是你此刻要赶路，还是要看得清楚。"
  ],
  [
    "content01.onboarding.mountain-road.choice.go-village",
    "绕去村里，按路平的那条走"
  ],
  [
    "content01.onboarding.mountain-road.choice.scout-ridge",
    "先爬上高处看清林里的情形"
  ],
  [
    "content01.onboarding.mountain-road.choice.take-ford",
    "走林边有车辙的那条近路"
  ],
  [
    "content01.onboarding.mountain-road.settle.go-village",
    "你绕去村里，走那条路平的道。炊烟、犬吠、晒谷的场院都从身边过去，没有人拦你，也没有人和你搭话。多走的这一程，只是多走的。"
  ],
  [
    "content01.onboarding.mountain-road.settle.scout-ridge",
    "你先爬上高处。林里的情形看清了：没有埋伏，也不见人烟。你在石头上坐了一阵，借着山风把气息理匀，再下岭时天已近晚。"
  ],
  [
    "content01.onboarding.mountain-road.settle.take-ford",
    "你走了林边那条有车辙的近路。树影压下来，脚下深浅不一，走得急，方向却越走越含糊。好在路是短的，一日就过去了。"
  ],
  [
    "content01.onboarding.mountain-road.title",
    "山路"
  ],
  [
    "content01.onboarding.old-trace.body",
    "石壁上一道旧痕延伸进荒草。来处已经模糊了，断口却很新——留下它的人不久之前还在这里。你可以沿着断口追进荒草，也可以先记下位置，或者转去问附近的人。"
  ],
  [
    "content01.onboarding.old-trace.choice.ask-locals",
    "转去问附近的人有无异常"
  ],
  [
    "content01.onboarding.old-trace.choice.follow-fresh",
    "顺着新断口追进荒草"
  ],
  [
    "content01.onboarding.old-trace.choice.mark-spot",
    "先记下位置，不急于这一步"
  ],
  [
    "content01.onboarding.old-trace.resolution",
    "这一次追查还没有取得可以确认的新线索。"
  ],
  [
    "content01.onboarding.old-trace.settle.ask-locals",
    "你转去问附近的人。有人说前些日子见过一个背竹篓的过客，也有人说那痕是野物蹭的。两句话彼此对不上，你没能问出个准信。"
  ],
  [
    "content01.onboarding.old-trace.settle.follow-fresh",
    "你顺着新断口追进荒草。断痕一路新鲜，走出二里却忽然断了，草叶倒伏的方向与来路对不上。你在原地转了两圈，没有找到第二处痕迹。"
  ],
  [
    "content01.onboarding.old-trace.settle.mark-spot",
    "你没有急着追，只在石壁前把断口的形状看熟，又记下方位。回头看那一眼，仍然看不出这道痕是谁留下的。"
  ],
  [
    "content01.onboarding.old-trace.title",
    "旧痕"
  ],
  [
    "content01.onboarding.quiet-retreat.body",
    "静室里没有异象，只有一次次走神与重新坐定。你数到第几遍时开始怀疑自己走了岔路。你可以照原样再坐一段，也可以换个法子重起一轮，或者今日就此收束。"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.change-method",
    "换个法子重起一轮行功"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.close-day",
    "今日就此收束，改日再来"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.sit-again",
    "照原样再坐一段，看能否坐稳"
  ],
  [
    "content01.onboarding.quiet-retreat.settle.change-method",
    "你换了法子重起一轮：不再数息，只守着丹田那一点。前半日比原样更不顺，直到午后才接上，气机反倒比先前匀了几分。"
  ],
  [
    "content01.onboarding.quiet-retreat.settle.close-day",
    "你把这一日收束了，没有硬撑下去。蒲团归位，静室扫净。所得不多，但也没有把走神坐成习惯，明日再来时还接得上。"
  ],
  [
    "content01.onboarding.quiet-retreat.settle.sit-again",
    "你照原样再坐一段。走神还是有的，只是每回心神散出去再收回来，都比上一回快些。半日过去，心绪沉了下去，气机也跟着稳了。"
  ],
  [
    "content01.onboarding.quiet-retreat.title",
    "静室"
  ],
  [
    "content01.onboarding.rain-shelter.body",
    "骤雨把几名陌生人困在同一檐下。雨声太大，说话要提高嗓门，反而没人先开口。沉默比寒意更先试探彼此：谁挪一挪，谁就先把话说出去了。"
  ],
  [
    "content01.onboarding.rain-shelter.choice.consider",
    "靠着柱子不动，听这一场雨落完"
  ],
  [
    "content01.onboarding.rain-shelter.choice.engage",
    "挪半个身位，先把伞递过去"
  ],
  [
    "content01.onboarding.rain-shelter.choice.leave",
    "雨脚一转就先行赶路"
  ],
  [
    "content01.onboarding.rain-shelter.title",
    "避雨"
  ],
  [
    "content01.onboarding.roadside-injury.body",
    "路边有人坐着捂住伤口。血已经止住，他仍盯着每一双靠近的手。你可以上前替他处理，也可以先站远些问清发生了什么，或者只记住这个人。"
  ],
  [
    "content01.onboarding.roadside-injury.choice.help-dress",
    "上前替他处理伤口"
  ],
  [
    "content01.onboarding.roadside-injury.choice.just-notice",
    "只记下这个人的样子，不去打扰"
  ],
  [
    "content01.onboarding.roadside-injury.choice.keep-distance",
    "先站远些问清他遇到了什么"
  ],
  [
    "content01.onboarding.roadside-injury.settle.help-dress",
    "你蹲下来替他理伤，先封住出血的那一处，再把错开的骨节顺回去。他盯着你的手，直到疼劲过去才松了肩膀，把你的名字问了一遍。"
  ],
  [
    "content01.onboarding.roadside-injury.settle.just-notice",
    "你只记下这个人的样子：左眉一道旧疤，衣角是青灰的。你没有上前，也没有问话。走过去之后，他还在原地坐了一阵。"
  ],
  [
    "content01.onboarding.roadside-injury.settle.keep-distance",
    "你站远了些，问他是怎么伤的。他说是昨夜在岔口遇上了人，其余的说不清楚。你没有靠前，也没有替他处理那道伤口。"
  ],
  [
    "content01.onboarding.roadside-injury.title",
    "路边伤者"
  ],
  [
    "content01.ordinary.broken-bridge.body",
    "山洪冲断了木桥，两岸的人隔水商量，谁也不愿先把绳索抛出去。你可以先帮对岸把绳索拉起来，也可以只问清对面有几个人、家在哪个方向，再决定要不要出力。"
  ],
  [
    "content01.ordinary.broken-bridge.choice.ask-terms",
    "只问清对面的人数与去向"
  ],
  [
    "content01.ordinary.broken-bridge.choice.throw-rope",
    "先把绳索抛过去，帮他们过河"
  ],
  [
    "content01.ordinary.broken-bridge.title",
    "断桥"
  ],
  [
    "content01.ordinary.empty-search.body",
    "你按旧图找了一日，只见苔痕、碎石与几处被雨冲淡的脚印。旧图上标的方位已经偏了。你可以照脚印的走向继续追，也可以承认今日无所得，回头重画。"
  ],
  [
    "content01.ordinary.empty-search.choice.follow-footprints",
    "照那几处脚印继续追下去"
  ],
  [
    "content01.ordinary.empty-search.choice.redraw-map",
    "承认今日无所得，回头重画"
  ],
  [
    "content01.ordinary.empty-search.settle.follow-footprints",
    "你照那几处脚印继续追下去。脚印被雨冲淡，走一段断一段，追到坡下才发现方向反了。一日就这么过去，你什么也没有找到。"
  ],
  [
    "content01.ordinary.empty-search.settle.redraw-map",
    "你承认今日无所得，坐下把旧图重画。照着记忆改了几处方位，画完自己也清楚未必准确。日头偏西，你收了纸笔。"
  ],
  [
    "content01.ordinary.empty-search.title",
    "空寻"
  ],
  [
    "content01.ordinary.ferry-wait.body",
    "河雾压住渡口，船家不肯冒险开船。等的人越来越多，谁也不愿先开口。你可以留在雾里等一趟船，也可以沿河岸走到下一个渡口——那条路更远，但至少在走。"
  ],
  [
    "content01.ordinary.ferry-wait.choice.wait-ferry",
    "留在渡口等一趟船"
  ],
  [
    "content01.ordinary.ferry-wait.choice.walk-upstream",
    "沿河岸走到下一个渡口"
  ],
  [
    "content01.ordinary.ferry-wait.title",
    "候渡"
  ],
  [
    "content01.ordinary.harvest-help.body",
    "村人赶在风雨前收谷，人手不足，只要你肯搭把手，一个时辰就能补上缺口。你可以下地收谷，也可以替他们看住堆在院里的谷堆，等他们回来再一起分。"
  ],
  [
    "content01.ordinary.harvest-help.choice.guard-store",
    "替他们看住院里的谷堆"
  ],
  [
    "content01.ordinary.harvest-help.choice.work-field",
    "下地一起收谷"
  ],
  [
    "content01.ordinary.harvest-help.title",
    "收谷"
  ],
  [
    "content01.ordinary.market-bargain.body",
    "行商修士摆出几味寻常药材，也收草药。价钱报得干脆利落，可他真正想交换的，是一条路况消息：哪一段路近来不太平。你可以只把随身草药作价给他，也可以加进那条消息，用一个承诺换它。"
  ],
  [
    "content01.ordinary.market-bargain.choice.sell-herbs",
    "替他把混在一起的药材分开"
  ],
  [
    "content01.ordinary.market-bargain.choice.trade-for-news",
    "加进那条路况消息，用一个承诺换它"
  ],
  [
    "content01.ordinary.market-bargain.settle.sell-herbs",
    "你把行商那包混在一起的药材逐一分拣，理顺了品相。他看过一遍，挑出两味放错的收好，付了你工钱。这笔灵石是你动手挣来的。"
  ],
  [
    "content01.ordinary.market-bargain.settle.trade-for-news",
    "你把那条路况说给他听，请他替你捎一句话。他听完点头，说这消息值这个价。两人没有过手灵石，只有一句口头约定留在中间。"
  ],
  [
    "content01.ordinary.market-bargain.title",
    "小交易"
  ],
  [
    "content01.ordinary.missed-letter.body",
    "一封辗转多地的旧信终于到了手中，纸角磨损，寄信人没有留下回址。信里只提到一处地方，别的什么都没有。你可以照这处地名去找，也可以先弄清楚这封信为何迟到这么久。"
  ],
  [
    "content01.ordinary.missed-letter.choice.follow-place",
    "照信里那处地名去找"
  ],
  [
    "content01.ordinary.missed-letter.choice.trace-delay",
    "先查这封信为何迟到这么久"
  ],
  [
    "content01.ordinary.missed-letter.title",
    "迟信"
  ],
  [
    "content01.ordinary.mountain-view.body",
    "登高之后并无奇遇。群山在暮色里一层层远去，呼吸也随之平缓。你可以就地调息，把这段山路换来的清醒收进气机；也可以辨清方位后继续上路。"
  ],
  [
    "content01.ordinary.mountain-view.choice.breathe-here",
    "就地调息，把这段清醒收进气机"
  ],
  [
    "content01.ordinary.mountain-view.choice.orient-and-go",
    "辨清方位后继续上路"
  ],
  [
    "content01.ordinary.mountain-view.settle.breathe-here",
    "你在岩石上坐下调息。山风一层层过去，呼吸也跟着平缓。这一坐没有异象，只把登山的疲累换了回来，气机顺了不少。"
  ],
  [
    "content01.ordinary.mountain-view.settle.orient-and-go",
    "你辨清方位，记下远近几座山头的形貌，随后下岭。路上没有遇到人，也没有遇到别的东西。天暗下来时，你已经在另一条道上。"
  ],
  [
    "content01.ordinary.mountain-view.title",
    "山色"
  ],
  [
    "content01.ordinary.night-rain.body",
    "夜雨敲窗。你想起数年前一次仓促告别，那句话至今没有说完。念头一起就压不住。你可以坐下来把这段心绪行功化开，也可以就着雨声把它放到明天。"
  ],
  [
    "content01.ordinary.night-rain.choice.consider",
    "不起身，先把这一夜雨听完"
  ],
  [
    "content01.ordinary.night-rain.choice.engage",
    "就着雨声坐下来，把这段心绪行功化开"
  ],
  [
    "content01.ordinary.night-rain.choice.leave",
    "压下心绪，明日照常赶路"
  ],
  [
    "content01.ordinary.night-rain.title",
    "夜雨"
  ],
  [
    "content01.ordinary.old-song.body",
    "客栈角落有人弹起旧曲。旋律并不精妙，几位过客却同时安静下来。你可以坐到曲终再起身，也可以直接起身去看弹琴的人是谁——后者也许更接近这段曲子的来处。"
  ],
  [
    "content01.ordinary.old-song.choice.meet-player",
    "起身去看弹琴的人是谁"
  ],
  [
    "content01.ordinary.old-song.choice.sit-through",
    "坐到这一曲终了再起身"
  ],
  [
    "content01.ordinary.old-song.settle.meet-player",
    "你起身走到角落。弹琴的是个过路老者，见你过来只把手从弦上挪开，问你要听哪一首。你们说了几句曲子的事，他把琴收进布囊就走了。"
  ],
  [
    "content01.ordinary.old-song.settle.sit-through",
    "你坐到这一曲终了。旋律并不精妙，可琴音一起一落，正好把你散乱的气息带匀。起身时心里静了下来，如同又坐了一小会儿。"
  ],
  [
    "content01.ordinary.old-song.title",
    "旧曲"
  ],
  [
    "content01.ordinary.roadside-debate.body",
    "两名修士为一条旧规争得面红耳赤，围观者各有私心，嘴上却都说为了公道。你可以当场评一句谁站得住，也可以只问清这条旧规究竟伤过谁，再决定要不要开口。"
  ],
  [
    "content01.ordinary.roadside-debate.choice.ask-who-hurt",
    "只问这条旧规究竟伤过谁"
  ],
  [
    "content01.ordinary.roadside-debate.choice.pick-a-side",
    "当场评一句谁站得住"
  ],
  [
    "content01.ordinary.roadside-debate.title",
    "道旁争言"
  ],
  [
    "content01.ordinary.shared-fire.body",
    "荒野风紧，陌生旅人分出半边篝火，谁也没有追问来历。你可以守着火陪到天亮，也可以问问他接下来往哪条路走——问了他才记得你们照过面。"
  ],
  [
    "content01.ordinary.shared-fire.choice.ask-route",
    "问他接下来往哪条路走"
  ],
  [
    "content01.ordinary.shared-fire.choice.keep-watch",
    "守着火陪到天亮"
  ],
  [
    "content01.ordinary.shared-fire.title",
    "同火"
  ],
  [
    "content01.ordinary.tea-house.body",
    "茶棚里只剩半壶温茶。邻桌三人谈起一场与你无关的远行，说得很热闹，没有人问你从哪里来。棚外的路还长，你要决定的只是这壶茶喝完就走，还是坐到它凉透。"
  ],
  [
    "content01.ordinary.tea-house.choice.finish-cup",
    "喝完这半盏茶便走"
  ],
  [
    "content01.ordinary.tea-house.choice.stay-listen",
    "坐到茶凉，听完这段远行"
  ],
  [
    "content01.ordinary.tea-house.settle.finish-cup",
    "你把这半盏茶喝完，起身出门。茶还温着，歇脚也够。棚外的路还长，你把包袱系紧，重新上了道。"
  ],
  [
    "content01.ordinary.tea-house.settle.stay-listen",
    "你坐回原处，听邻桌三人把这趟远行说完。他们谈得热闹，没有人问你从哪里来。听着听着，你反倒静了下来，就着这几盏茶入了定。"
  ],
  [
    "content01.ordinary.tea-house.title",
    "半盏茶"
  ],
  [
    "content01.pei.broken-blade.body",
    "裴照川把断剑横在膝上，剑格上还留着上一次交手的缺口。他谈的是同行，不是收徒，也没有先许下情分。你要决定的是：以剑相争分个明白，还是先问清他这趟要往哪里去。"
  ],
  [
    "content01.pei.broken-blade.choice.bind-1",
    "与他定约"
  ],
  [
    "content01.pei.broken-blade.choice.bind-2",
    "以剑相争"
  ],
  [
    "content01.pei.broken-blade.choice.decline",
    "只说一句改日再会，不问他的去处"
  ],
  [
    "content01.pei.broken-blade.settle.bind-1",
    "你与裴照川把话说定：这一路同行，遇事先通气。他把断剑往膝上按了按，算是应了。此后你若再见他，这一句话都还在。"
  ],
  [
    "content01.pei.broken-blade.settle.bind-2",
    "你与他以剑相争。断剑碰在一处，过了十几个回合才各自收手。谁也没有伤着谁，只是都记住了对方的剑路。"
  ],
  [
    "content01.pei.broken-blade.settle.decline",
    "你只说一句改日再会，没有问他的去处。裴照川把断剑收回鞘里，点了点头。你们此后再无干系，也未通音信。"
  ],
  [
    "content01.pei.broken-blade.title",
    "断剑客"
  ],
  [
    "content01.pei.old-wound.body",
    "裴照川行至半坡忽然停步，旧伤让他的右手微颤。他把剑换到左手，语气仍然平稳，却不肯把这个决定交给旁人照看。你要决定的是：替他分忧，还是等他把话说完。"
  ],
  [
    "content01.pei.old-wound.choice.read-signs",
    "先看清他伤的到底是哪一处"
  ],
  [
    "content01.pei.old-wound.choice.take-risk",
    "接手扶住他发抖的那只手，把这一程走完"
  ],
  [
    "content01.pei.old-wound.choice.turn-away",
    "不强接，退回半步等他开口"
  ],
  [
    "content01.pei.old-wound.title",
    "旧伤复作"
  ],
  [
    "content01.pei.promise-echo.body",
    "多年后那柄断剑仍在，剑身上的缺口没有补。裴照川没有复述当年的旧约，只把另一条路摆到你面前，像在问：当年那件事，现在还算不算数。"
  ],
  [
    "content01.pei.promise-echo.choice.consider",
    "先问清当年断的是哪一段"
  ],
  [
    "content01.pei.promise-echo.choice.engage",
    "接下他递来的第二条路"
  ],
  [
    "content01.pei.promise-echo.choice.leave",
    "不接这条路，转身离开"
  ],
  [
    "content01.pei.promise-echo.title",
    "剑约未冷"
  ],
  [
    "content01.pei.sparring-rain.body",
    "雨线斜落，裴照川只问你是否还愿意拔剑。他没有摆出架势，胜负之外还要看你如何收手：剑出到哪一步算完，收手时剑锋朝哪一边，都是他自己选的事。"
  ],
  [
    "content01.pei.sparring-rain.choice.consider",
    "先问清他今日想试的是剑还是人"
  ],
  [
    "content01.pei.sparring-rain.choice.engage",
    "拔剑，但只走到他说的那一步"
  ],
  [
    "content01.pei.sparring-rain.choice.leave",
    "收剑鞘而不发"
  ],
  [
    "content01.pei.sparring-rain.title",
    "雨中试剑"
  ],
  [
    "content01.risk.beast-trail.body",
    "新鲜兽迹绕过营地三次，每次都绕回同一处。猎物与猎手的位置，可能在下一步互换。你手里的东西还够一次驱赶，也可能只够一次引开。"
  ],
  [
    "content01.risk.beast-trail.choice.read-signs",
    "先看清它绕的是哪一圈"
  ],
  [
    "content01.risk.beast-trail.choice.take-risk",
    "循着兽迹迎过去"
  ],
  [
    "content01.risk.beast-trail.choice.turn-away",
    "收起营地，趁夜换一处"
  ],
  [
    "content01.risk.beast-trail.title",
    "兽迹"
  ],
  [
    "content01.risk.broken-seal.body",
    "封印的裂口只容一线气息外泄。那气息古老而清醒，并不急着扑上来，只在等一个回应。你可以合上裂口转身，也可以听它把话说完。"
  ],
  [
    "content01.risk.broken-seal.choice.read-signs",
    "先辨清这气息出自哪一类封"
  ],
  [
    "content01.risk.broken-seal.choice.take-risk",
    "听它把话说完"
  ],
  [
    "content01.risk.broken-seal.choice.turn-away",
    "合上裂口，转身离开"
  ],
  [
    "content01.risk.broken-seal.title",
    "残封"
  ],
  [
    "content01.risk.critical-crossing.body",
    "伤势未稳，河水又在上涨。此刻强渡，危险来自水势，也来自你自己的身体。两样都在往下压，而对岸已经能看见了。"
  ],
  [
    "content01.risk.critical-crossing.choice.read-signs",
    "先探清水势最缓的一处"
  ],
  [
    "content01.risk.critical-crossing.choice.take-risk",
    "趁还有力气强渡过去"
  ],
  [
    "content01.risk.critical-crossing.choice.turn-away",
    "退回岸上，等水落下去"
  ],
  [
    "content01.risk.critical-crossing.title",
    "负伤渡河"
  ],
  [
    "content01.risk.curse-stone.body",
    "无字石碑在神识触及的一刻传来低语，像有人借你的记忆说话。声音用的是你自己的嗓音，说的却是一句你从未听过的话。"
  ],
  [
    "content01.risk.curse-stone.choice.read-signs",
    "先分辨这话是谁在借声"
  ],
  [
    "content01.risk.curse-stone.choice.take-risk",
    "再把神识探进去，听它说完"
  ],
  [
    "content01.risk.curse-stone.choice.turn-away",
    "收回神识，不去应这一声"
  ],
  [
    "content01.risk.curse-stone.title",
    "无字碑"
  ],
  [
    "content01.risk.falling-star.body",
    "夜空裂开一道暗红弧光，落点近得能感到地面轻震，远处鸟群尽数惊起。碎片还挂在天上，坠势未止——你只有站定或走开这两个选择。"
  ],
  [
    "content01.risk.falling-star.choice.read-signs",
    "先看清落点离你还有多远"
  ],
  [
    "content01.risk.falling-star.choice.take-risk",
    "朝落点走过去，看那是什么"
  ],
  [
    "content01.risk.falling-star.choice.turn-away",
    "背向落点，先离远些"
  ],
  [
    "content01.risk.falling-star.title",
    "坠星"
  ],
  [
    "content01.risk.flood-cave.body",
    "洞中水位正在上升，深处那点微光还没有消失。留给你的时间不多了：往回走要穿过刚涨起来的水，往前走要赌那条路够高。"
  ],
  [
    "content01.risk.flood-cave.choice.read-signs",
    "先看清光亮离水面多高"
  ],
  [
    "content01.risk.flood-cave.choice.take-risk",
    "往深处走，赌那条路够高"
  ],
  [
    "content01.risk.flood-cave.choice.turn-away",
    "顺原路退回洞口"
  ],
  [
    "content01.risk.flood-cave.title",
    "涨水洞"
  ],
  [
    "content01.risk.pine-ambush.body",
    "松针忽然停止落下。前路有人藏住呼吸，退路也在一点点合拢。声音是从两个方向传来的，你分不清哪一个更近，也不敢赌。"
  ],
  [
    "content01.risk.pine-ambush.choice.read-signs",
    "先分辨哪一边的声音更近"
  ],
  [
    "content01.risk.pine-ambush.choice.take-risk",
    "抢在合拢之前冲出去"
  ],
  [
    "content01.risk.pine-ambush.choice.turn-away",
    "退出松林，绕开这一段"
  ],
  [
    "content01.risk.pine-ambush.settle.read-signs.success",
    "你先分辨声音的远近。左边那处一直在原地，右边那处在缓慢挪动。你看清了该往哪边走，趁那个空当退了出去。"
  ],
  [
    "content01.risk.pine-ambush.settle.take-risk.costlySuccess",
    "你硬冲出去，肩上挨了一下。走出松林时血已经浸透衣领，好在人还在，怀里也攥着从对方身上扯下的东西。"
  ],
  [
    "content01.risk.pine-ambush.settle.take-risk.failure",
    "你冲出几步就被截住。松针簌簌落了一地，你被按在树干上，等松开时，身边只剩下自己。"
  ],
  [
    "content01.risk.pine-ambush.settle.take-risk.success",
    "你抢在枝叶合拢之前冲了过去。身后一合落了空，你一路跑出松林才停下。衣衫被划破了几处，人还完整。"
  ],
  [
    "content01.risk.pine-ambush.settle.turn-away.success",
    "你退出松林，松针这才落下来，落在空地上。你退得干脆，绕了一段远路，天黑了也没走出那片坡。"
  ],
  [
    "content01.risk.pine-ambush.title",
    "松林伏影"
  ],
  [
    "content01.risk.poison-mist.body",
    "谷底升起淡青雾气，沾到雾的草叶边缘已经发黑。风把雾往这边吹，绕路要多耗数日，而你带的水只够两天。湿冷顺着衣袖往里渗。"
  ],
  [
    "content01.risk.poison-mist.choice.read-signs",
    "先辨出雾最薄的那一段"
  ],
  [
    "content01.risk.poison-mist.choice.take-risk",
    "屏住呼吸穿过这片青雾"
  ],
  [
    "content01.risk.poison-mist.choice.turn-away",
    "退回谷口，另找一条路"
  ],
  [
    "content01.risk.poison-mist.title",
    "青雾"
  ],
  [
    "content01.risk.revenge-shadow.body",
    "有人沿着旧日冲突留下的线索追来。来者不问解释，只确认你的名字——他已经确认过了。你想起那次争执里，自己确实说过一句过头的话。"
  ],
  [
    "content01.risk.revenge-shadow.choice.read-signs",
    "先认出他是当年哪一个"
  ],
  [
    "content01.risk.revenge-shadow.choice.take-risk",
    "迎上去，把当年那句话说完"
  ],
  [
    "content01.risk.revenge-shadow.choice.turn-away",
    "不进他的问话，先走开"
  ],
  [
    "content01.risk.revenge-shadow.title",
    "旧怨追来"
  ],
  [
    "content01.risk.ruin-depth.body",
    "石阶向下延伸，壁灯早已熄灭，你的脚步声在石壁之间回荡，却比回来时多了一次。回声不会说谎：前面还有别的东西在动。"
  ],
  [
    "content01.risk.ruin-depth.choice.read-signs",
    "先数清回声是从几处来的"
  ],
  [
    "content01.risk.ruin-depth.choice.take-risk",
    "继续往下，看清那是什么"
  ],
  [
    "content01.risk.ruin-depth.choice.turn-away",
    "就此上行，不再往下探"
  ],
  [
    "content01.risk.ruin-depth.settle.read-signs.success",
    "你在阶口站了很久，把回声一处一处数清。数到第四处，你听出那只是水滴，真正在动的只有两处。你没有下去，退回洞口时已过了小半日。"
  ],
  [
    "content01.risk.ruin-depth.settle.take-risk.costlySuccess",
    "你往下走了两级，正撞上在动的那个东西。缠斗中你带伤退出，只抢回一件旧器，血一路滴在石阶上。得手了，代价却在自己身上。"
  ],
  [
    "content01.risk.ruin-depth.settle.take-risk.failure",
    "你循声往下追，脚下的声音不对，退已经来不及。你被撞在石壁上滑了下去，等缓过神，手里什么也没有。"
  ],
  [
    "content01.risk.ruin-depth.settle.take-risk.success",
    "你循着回声一路下到底。石室尽头堆着几件旧器，落尘很厚，却还完整。你挑了两件揣进怀里，旁的没有动，回头在镇上换成了灵石。"
  ],
  [
    "content01.risk.ruin-depth.settle.turn-away.success",
    "你转身往上走。石阶很长，出来时天已经暗了。你没有再弄明白下面是什么，也没有把自己搭进去。"
  ],
  [
    "content01.risk.ruin-depth.title",
    "遗迹深处"
  ],
  [
    "content01.road.conflict-echo.body",
    "同一条窄路，你再次看见那个熟悉的身影。当年的争执已经长出新的分量，谁都没有先提。他停下来，你也没有。"
  ],
  [
    "content01.road.conflict-echo.choice.consider",
    "侧身让路，谁都不提那一段"
  ],
  [
    "content01.road.conflict-echo.choice.engage",
    "这次先把当年的话说完"
  ],
  [
    "content01.road.conflict-echo.choice.leave",
    "退回去，等他先走"
  ],
  [
    "content01.road.conflict-echo.title",
    "旧路再逢"
  ],
  [
    "content01.road.conflict.body",
    "狭窄山道只容一人先过。对面的修士不肯退让，你也看不出他是否另有所图。他把脚跟抵在石缝上，像是已经打算在这里耗到底。"
  ],
  [
    "content01.road.conflict.choice.bind-1",
    "记下此争"
  ],
  [
    "content01.road.conflict.choice.decline",
    "退到路边，让他先过去"
  ],
  [
    "content01.road.conflict.title",
    "窄路相争"
  ],
  [
    "content01.road.help.body",
    "同行的陌生修士在坡前力竭。他没有开口求救，只把行囊向身后挪了挪，腾出一点位置。他不看你，等的是你自己决定要不要停下。"
  ],
  [
    "content01.road.help.choice.bind-1",
    "扶他一程"
  ],
  [
    "content01.road.help.choice.decline",
    "不停脚，越过他继续赶路"
  ],
  [
    "content01.road.help.title",
    "扶一程"
  ],
  [
    "content01.road.kindness-echo.body",
    "多年后雨又落下，一把伞从身侧递来。那张脸比记忆里成熟，旧日那一程仍然被记得——他先开口叫的，还是当年的称呼。"
  ],
  [
    "content01.road.kindness-echo.choice.consider",
    "先问他这些年过得如何"
  ],
  [
    "content01.road.kindness-echo.choice.engage",
    "叫回当年的称呼，接过这把伞"
  ],
  [
    "content01.road.kindness-echo.choice.leave",
    "各走各的路，把这一段雨留给当年"
  ],
  [
    "content01.road.kindness-echo.title",
    "故人递伞"
  ],
  [
    "content01.xie.cave-gamble.body",
    "洞口吹出的风带着金石气。谢听潮判断里面有路，也坦言这个判断可能错——他把手按在石壁上等了一息，石头是凉的。他要你先说，进还是退。"
  ],
  [
    "content01.xie.cave-gamble.choice.read-signs",
    "先在洞口听清风声的来路"
  ],
  [
    "content01.xie.cave-gamble.choice.take-risk",
    "先进洞，把石壁一路摸到底"
  ],
  [
    "content01.xie.cave-gamble.choice.turn-away",
    "记住这个洞口，原路退回"
  ],
  [
    "content01.xie.cave-gamble.title",
    "洞口风声"
  ],
  [
    "content01.xie.divided-spoils.body",
    "所得不如预想，谢听潮仍按旧话分成，只把最后一件用途不明的东西留在中央，谁也没有先动。他问的不是分法，而是这件事还算不算当初约定的那个部分。"
  ],
  [
    "content01.xie.divided-spoils.choice.consider",
    "把中央那件推到一边，先分其余的"
  ],
  [
    "content01.xie.divided-spoils.choice.engage",
    "按当初的约定，先问清那件东西的用途"
  ],
  [
    "content01.xie.divided-spoils.choice.leave",
    "一样都不取，这次到此为止"
  ],
  [
    "content01.xie.divided-spoils.title",
    "分利"
  ],
  [
    "content01.xie.map-echo.body",
    "秘图的旧折痕与眼前山势完全重合。谢听潮没有催你，只把当初说过的话轻轻念了一遍，念到一半就停住——他也在等你想起来，那句话当年是怎么说的。"
  ],
  [
    "content01.xie.map-echo.choice.consider",
    "先按图走一遍，把路线对清楚"
  ],
  [
    "content01.xie.map-echo.choice.engage",
    "把当年没说完的那半句补上"
  ],
  [
    "content01.xie.map-echo.choice.leave",
    "承认你已经想不起那句话"
  ],
  [
    "content01.xie.map-echo.title",
    "图上旧折"
  ],
  [
    "content01.xie.secret-map.body",
    "谢听潮摊开半张秘图，另一半仍收在袖中。他愿意分路，也要求先说清如何分利：谁走前段，谁担风险，图上的记号算不算数。图边角已经磨得起毛。"
  ],
  [
    "content01.xie.secret-map.choice.bind-1",
    "立约同行"
  ],
  [
    "content01.xie.secret-map.choice.bind-2",
    "暗留后手"
  ],
  [
    "content01.xie.secret-map.choice.decline",
    "不谈分利，把图原样还给他"
  ],
  [
    "content01.xie.secret-map.settle.bind-1",
    "你与谢听潮立约同行：他走前段，你担后半的风险，记号两人都认。他把半张图推过来，另一半仍收在袖里。这笔约定算是落定了。"
  ],
  [
    "content01.xie.secret-map.settle.bind-2",
    "你答应同行，心里却留了后手——图上的记号另抄了一份。谢听潮没有察觉。这份心思将来若有回响，也是当年自己埋下的。"
  ],
  [
    "content01.xie.secret-map.settle.decline",
    "你不谈分利，把那半张图原样还给他。谢听潮收好图，没有再劝。此后各走各路，图上那些记号都与你无关。"
  ],
  [
    "content01.xie.secret-map.title",
    "半张秘图"
  ],
  [
    "content01.xu.empty-courtyard.body",
    "院门仍旧，檐下却积了厚灰。邻人只说许长安早已离开，具体去了哪里无人知道。院角那棵旧树还活着，落叶堆在墙根，没有被扫过。"
  ],
  [
    "content01.xu.empty-courtyard.choice.consider",
    "向邻人多问一句他可能去了哪里"
  ],
  [
    "content01.xu.empty-courtyard.choice.engage",
    "扫开墙根的落叶，让院子有人住的样子"
  ],
  [
    "content01.xu.empty-courtyard.choice.leave",
    "把院门掩上，不去问答案"
  ],
  [
    "content01.xu.empty-courtyard.title",
    "空院"
  ],
  [
    "content01.xu.mortal-letter.body",
    "许长安托人送来一封短笺，问的不是仙途，只是你是否还记得旧日门前那棵树。送信人不肯多等，收了脚程钱就走了。信很短，短到只够问这一件事。"
  ],
  [
    "content01.xu.mortal-letter.choice.bind-1",
    "答应归去"
  ],
  [
    "content01.xu.mortal-letter.choice.decline",
    "不回这封信，把短笺收进包里"
  ],
  [
    "content01.xu.mortal-letter.settle.bind-1",
    "你回了信，答应归去。短笺上只写三个字，写起来却比画符还慢。信由送信人带走，树下那件事你答应了下来。"
  ],
  [
    "content01.xu.mortal-letter.settle.decline",
    "你把短笺收进包里，没有回信。许长安托来的人等不到答复，自己走了。这封信你留着，却未必还等得到下一封。"
  ],
  [
    "content01.xu.mortal-letter.title",
    "人间来信"
  ],
  [
    "content01.xu.promise-echo.body",
    "旧树又添了一圈年轮，你终于站回门前。门里没有回应，院子空着。许长安是否还在，已经不再是唯一的问题——你要决定的是推门进去，还是先在这里站一会儿。"
  ],
  [
    "content01.xu.promise-echo.choice.consider",
    "先在门前站一会儿，不急着进去"
  ],
  [
    "content01.xu.promise-echo.choice.engage",
    "推门进去，把话当面问清"
  ],
  [
    "content01.xu.promise-echo.choice.leave",
    "转身离开，把这件事留在原处"
  ],
  [
    "content01.xu.promise-echo.title",
    "树下旧诺"
  ],
  [
    "content01.xu.ten-year-return.body",
    "你眼中的数次闭关，在许长安鬓边已经积了一层霜。他仍认得你，也没有假装岁月轻巧。院门开着，门前那棵树比记忆里高了一些。"
  ],
  [
    "content01.xu.ten-year-return.choice.consider",
    "先在门外看清院里的变化"
  ],
  [
    "content01.xu.ten-year-return.choice.engage",
    "走进院子，把这十年当面说给他听"
  ],
  [
    "content01.xu.ten-year-return.choice.leave",
    "不进门，改日再来"
  ],
  [
    "content01.xu.ten-year-return.title",
    "十年重逢"
  ]
];
