// GENERATED FILE — DO NOT HAND-EDIT.
//
// LIVEFIX06 — the full Content01 Chinese copy catalog for the v2-live client.
//
// Derived from packages/content/src/content01-v1.ts (CONTENT01_ZH_CN), which is the single
// source of truth for this wording. The strings are imported, not transcribed, so this file
// cannot drift from the source without the freshness check failing.
//
// Regenerate with:
//   node tools/content01-zh-cn-module.mjs --write
// Verify with:
//   node tools/content01-zh-cn-module.mjs
// tests/livefix06.test.mjs asserts this module equals a fresh read of the source catalog, and
// that a new source key without regeneration fails.
module.exports = [
  [
    "content01.build.alchemy.failed-brew.body",
    "药液颜色偏了一线，这炉已不能救人；承认失败，比把它勉强端出去更难。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.alchemy.failed-brew.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.alchemy.failed-brew.title",
    "废炉"
  ],
  [
    "content01.build.alchemy.fever.body",
    "村中热症蔓延，没有珍稀灵药，只有有限草药与一夜不能出错的照看。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.alchemy.fever.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.alchemy.fever.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.alchemy.fever.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.alchemy.fever.title",
    "退热"
  ],
  [
    "content01.build.alchemy.herb-sort.body",
    "三种药草外形近似，药性却相反，耐心辨认比一炉昂贵丹火更要紧。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.alchemy.herb-sort.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.alchemy.herb-sort.title",
    "辨草"
  ],
  [
    "content01.build.body.boulder.body",
    "巨石堵住山道，术法并非唯一办法，筋骨与耐心也能一点点挪开困局。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.body.boulder.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.body.boulder.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.body.boulder.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.body.boulder.title",
    "移石"
  ],
  [
    "content01.build.body.carry-wounded.body",
    "伤者无法再走，山路仍长。背起一个人，意味着把自己的退路也交给脚下。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.body.carry-wounded.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.body.carry-wounded.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.body.carry-wounded.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.body.carry-wounded.title",
    "背人下山"
  ],
  [
    "content01.build.body.cold-water.body",
    "寒潭入骨，继续停留能磨炼气血，也可能让旧伤在夜里更深一分。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.body.cold-water.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.body.cold-water.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.body.cold-water.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.body.cold-water.title",
    "寒潭"
  ],
  [
    "content01.build.fortune.empty-hand.body",
    "等待多日的机缘没有出现，真正留下的是你如何面对落空与下一次选择。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.fortune.empty-hand.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.fortune.empty-hand.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.fortune.empty-hand.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.fortune.empty-hand.title",
    "空手而归"
  ],
  [
    "content01.build.fortune.fork.body",
    "熟路能按时抵达，偏路却留下新鲜蹄印；未知并不等同于好运，也不等同于坏事。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.fortune.fork.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.fortune.fork.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.fortune.fork.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.fortune.fork.title",
    "偏僻岔路"
  ],
  [
    "content01.build.fortune.hidden-stream.body",
    "你在无人在意的石缝听见水声，继续挖掘可能一无所获，也可能改写整段行程。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.fortune.hidden-stream.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.fortune.hidden-stream.title",
    "石下清泉"
  ],
  [
    "content01.build.sword.guard-caravan.body",
    "商队只求平安过岭，剑锋若太快，可能把原本能谈的局面推向死斗。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.sword.guard-caravan.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.sword.guard-caravan.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.sword.guard-caravan.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.sword.guard-caravan.title",
    "护行"
  ],
  [
    "content01.build.sword.no-draw.body",
    "对方故意激你拔剑，真正难的并非出手，而是判断这一剑是否值得。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.sword.no-draw.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.sword.no-draw.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.sword.no-draw.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.sword.no-draw.title",
    "剑未出鞘"
  ],
  [
    "content01.build.sword.river-cut.body",
    "山涧暴涨，石上只容一步，你要用剑开的不是敌人，而是一线可过之路。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.build.sword.river-cut.choice.consider",
    "停步细看"
  ],
  [
    "content01.build.sword.river-cut.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.build.sword.river-cut.choice.leave",
    "见好便收"
  ],
  [
    "content01.build.sword.river-cut.title",
    "截流一剑"
  ],
  [
    "content01.cen.shared-echo.body",
    "旧伤在阴雨里同时发作，岑不归看见你按住肩头，便知道那一日没有被忘记。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.cen.shared-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.cen.shared-echo.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.cen.shared-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.cen.shared-echo.title",
    "伤痕相认"
  ],
  [
    "content01.cen.shield-stranger.body",
    "乱石落下时，岑不归已经站到最窄的缺口。他看向你，等一个共同承担的决定。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.cen.shield-stranger.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.cen.shield-stranger.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.cen.shield-stranger.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.cen.shield-stranger.title",
    "以身护人"
  ],
  [
    "content01.cen.shoulder-road.body",
    "岑不归替你挡下一击，自己也伤得不轻。他不谈恩情，只问接下来的路怎样走。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.cen.shoulder-road.choice.bind-1",
    "与他同行"
  ],
  [
    "content01.cen.shoulder-road.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.cen.shoulder-road.title",
    "并肩负伤"
  ],
  [
    "content01.cen.stone-steps.body",
    "岑不归背石登阶，每一步都极慢。他不劝你跟上，只在山腰留了一瓢清水。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.cen.stone-steps.choice.consider",
    "停步细看"
  ],
  [
    "content01.cen.stone-steps.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.cen.stone-steps.choice.leave",
    "见好便收"
  ],
  [
    "content01.cen.stone-steps.title",
    "负石登阶"
  ],
  [
    "content01.destiny.echo.advantage",
    "因缘易见"
  ],
  [
    "content01.destiny.echo.body",
    "有些相逢来得早，有些旧事回来得迟。"
  ],
  [
    "content01.destiny.echo.cost",
    "行囊稍薄"
  ],
  [
    "content01.destiny.echo.hook",
    "人间旧识"
  ],
  [
    "content01.destiny.echo.title",
    "旧声"
  ],
  [
    "content01.destiny.edge.advantage",
    "敢近锋芒"
  ],
  [
    "content01.destiny.edge.body",
    "常在险处见路，也常在险处留伤。"
  ],
  [
    "content01.destiny.edge.cost",
    "岁数有折"
  ],
  [
    "content01.destiny.edge.hook",
    "断剑之人"
  ],
  [
    "content01.destiny.edge.title",
    "临锋"
  ],
  [
    "content01.destiny.steady.advantage",
    "心思澄定"
  ],
  [
    "content01.destiny.steady.body",
    "得一分安稳，也少一分骤进。"
  ],
  [
    "content01.destiny.steady.cost",
    "奇缘稍远"
  ],
  [
    "content01.destiny.steady.hook",
    "青河旧路"
  ],
  [
    "content01.destiny.steady.title",
    "守拙"
  ],
  [
    "content01.jiang.bitter-decoction.body",
    "一锅药汤气味辛烈，姜雪芜提醒其中一味药性相冲，省事与稳妥不能两全。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.jiang.bitter-decoction.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.jiang.bitter-decoction.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.jiang.bitter-decoction.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.jiang.bitter-decoction.title",
    "苦汤"
  ],
  [
    "content01.jiang.debt-echo.body",
    "姜雪芜翻到旧账那一页，没有催促，只问你如今是否仍认得当年的代价。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.jiang.debt-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.jiang.debt-echo.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.jiang.debt-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.jiang.debt-echo.title",
    "旧账新页"
  ],
  [
    "content01.jiang.herb-price.body",
    "姜雪芜替人止住伤势，随后把耗去的药材与时间逐项说清，不多收，也不抹去。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.jiang.herb-price.choice.bind-1",
    "认下药债"
  ],
  [
    "content01.jiang.herb-price.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.jiang.herb-price.title",
    "药有其价"
  ],
  [
    "content01.jiang.night-clinic.body",
    "夜深后仍有人敲门，姜雪芜看过伤口，把最稳妥与最昂贵的办法都说在前面。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.jiang.night-clinic.choice.consider",
    "停步细看"
  ],
  [
    "content01.jiang.night-clinic.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.jiang.night-clinic.choice.leave",
    "见好便收"
  ],
  [
    "content01.jiang.night-clinic.title",
    "夜诊"
  ],
  [
    "content01.onboarding.first-breath.body",
    "晨雾尚未散尽，你第一次把纷乱心绪收进一呼一吸之间。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.first-breath.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.first-breath.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.first-breath.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.first-breath.title",
    "初息"
  ],
  [
    "content01.onboarding.forked-path.body",
    "你追寻的线索在此分成两股，一股清楚，一股更像有意留下的诱饵。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.forked-path.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.forked-path.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.forked-path.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.forked-path.title",
    "岔路"
  ],
  [
    "content01.onboarding.market-choice.body",
    "早市里灵石与人情一同流转，摊主的话半真半假，买卖之外还有眼色。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.market-choice.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.market-choice.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.market-choice.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.market-choice.title",
    "早市"
  ],
  [
    "content01.onboarding.mountain-road.body",
    "一条山路分向林深与村郭，两边都有人走过，却没有人为你担保。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.mountain-road.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.mountain-road.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.mountain-road.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.mountain-road.title",
    "山路"
  ],
  [
    "content01.onboarding.old-trace.body",
    "石壁上一道旧痕延伸进荒草，来处模糊，去处也未必值得追。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.old-trace.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.old-trace.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.old-trace.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.old-trace.title",
    "旧痕"
  ],
  [
    "content01.onboarding.quiet-retreat.body",
    "静室里没有异象，只有一次次走神与重新坐定，修行显得朴素而漫长。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.quiet-retreat.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.quiet-retreat.title",
    "静室"
  ],
  [
    "content01.onboarding.rain-shelter.body",
    "骤雨把几名陌生人困在同一檐下，沉默比寒意更先试探彼此。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.rain-shelter.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.rain-shelter.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.rain-shelter.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.rain-shelter.title",
    "避雨"
  ],
  [
    "content01.onboarding.roadside-injury.body",
    "路边有人捂着伤口，血已经止住，他仍警惕每一双靠近的手。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.onboarding.roadside-injury.choice.consider",
    "停步细看"
  ],
  [
    "content01.onboarding.roadside-injury.choice.engage",
    "顺势而行"
  ],
  [
    "content01.onboarding.roadside-injury.choice.leave",
    "见好便收"
  ],
  [
    "content01.onboarding.roadside-injury.title",
    "路边伤者"
  ],
  [
    "content01.ordinary.broken-bridge.body",
    "山洪冲断木桥，两岸的人隔水商量，谁也不愿先把绳索抛出去。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.broken-bridge.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.broken-bridge.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.broken-bridge.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.broken-bridge.title",
    "断桥"
  ],
  [
    "content01.ordinary.empty-search.body",
    "你按旧图找了一日，只见苔痕、碎石与几处被雨冲淡的脚印。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.empty-search.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.empty-search.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.empty-search.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.empty-search.title",
    "空寻"
  ],
  [
    "content01.ordinary.ferry-wait.body",
    "河雾压住渡口，船家不肯冒险开船，所有人只得等水声慢下来。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.ferry-wait.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.ferry-wait.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.ferry-wait.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.ferry-wait.title",
    "候渡"
  ],
  [
    "content01.ordinary.harvest-help.body",
    "村人赶在风雨前收谷，人手不足，修士的一日也能换来许多凡俗年月。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.harvest-help.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.harvest-help.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.harvest-help.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.harvest-help.title",
    "收谷"
  ],
  [
    "content01.ordinary.market-bargain.body",
    "行商修士摆出几味寻常药材，真正要交换的却是一条路况消息。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.market-bargain.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.market-bargain.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.market-bargain.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.market-bargain.title",
    "小交易"
  ],
  [
    "content01.ordinary.missed-letter.body",
    "一封辗转多地的旧信终于到了手中，纸角磨损，寄信人未留下回址。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.missed-letter.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.missed-letter.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.missed-letter.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.missed-letter.title",
    "迟信"
  ],
  [
    "content01.ordinary.mountain-view.body",
    "登高之后并无奇遇，只有群山在暮色里一层层远去，呼吸也随之平缓。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.mountain-view.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.mountain-view.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.mountain-view.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.mountain-view.title",
    "山色"
  ],
  [
    "content01.ordinary.night-rain.body",
    "夜雨敲窗，你想起数年前一次仓促告别，那句话至今没有说完。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.night-rain.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.night-rain.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.night-rain.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.night-rain.title",
    "夜雨"
  ],
  [
    "content01.ordinary.old-song.body",
    "客栈角落有人弹起旧曲，旋律并不精妙，却让几位过客同时安静下来。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.old-song.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.old-song.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.old-song.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.old-song.title",
    "旧曲"
  ],
  [
    "content01.ordinary.roadside-debate.body",
    "两名修士为一条旧规争得面红耳赤，围观者各有私心，却都说为了公道。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.roadside-debate.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.roadside-debate.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.roadside-debate.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.roadside-debate.title",
    "道旁争言"
  ],
  [
    "content01.ordinary.shared-fire.body",
    "荒野风紧，陌生旅人分出半边篝火，彼此都没有追问来历。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.shared-fire.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.shared-fire.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.shared-fire.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.shared-fire.title",
    "同火"
  ],
  [
    "content01.ordinary.tea-house.body",
    "小镇茶棚只剩半壶温茶，邻桌的人谈论一场与你无关的远行。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.ordinary.tea-house.choice.consider",
    "停步细看"
  ],
  [
    "content01.ordinary.tea-house.choice.engage",
    "顺势而行"
  ],
  [
    "content01.ordinary.tea-house.choice.leave",
    "见好便收"
  ],
  [
    "content01.ordinary.tea-house.title",
    "半盏茶"
  ],
  [
    "content01.pei.broken-blade.body",
    "裴照川把断剑横在膝上，他谈的是同行，不是收徒，也没有先许下情分。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.pei.broken-blade.choice.bind-1",
    "与他定约"
  ],
  [
    "content01.pei.broken-blade.choice.bind-2",
    "以剑相争"
  ],
  [
    "content01.pei.broken-blade.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.pei.broken-blade.title",
    "断剑客"
  ],
  [
    "content01.pei.old-wound.body",
    "裴照川行至半坡忽然停步，旧伤让他的右手微颤，他却不肯把决定交给旁人。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.pei.old-wound.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.pei.old-wound.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.pei.old-wound.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.pei.old-wound.title",
    "旧伤复作"
  ],
  [
    "content01.pei.promise-echo.body",
    "多年后那柄断剑仍在，裴照川没有复述旧约，只把另一条路摆到你面前。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.pei.promise-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.pei.promise-echo.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.pei.promise-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.pei.promise-echo.title",
    "剑约未冷"
  ],
  [
    "content01.pei.sparring-rain.body",
    "雨线斜落，裴照川只问你是否还愿意拔剑，胜负之外还要看你如何收手。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.pei.sparring-rain.choice.consider",
    "停步细看"
  ],
  [
    "content01.pei.sparring-rain.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.pei.sparring-rain.choice.leave",
    "见好便收"
  ],
  [
    "content01.pei.sparring-rain.title",
    "雨中试剑"
  ],
  [
    "content01.risk.beast-trail.body",
    "新鲜兽迹绕过营地三次，猎物与猎手的位置，可能在下一步互换。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.beast-trail.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.beast-trail.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.beast-trail.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.beast-trail.title",
    "兽迹"
  ],
  [
    "content01.risk.broken-seal.body",
    "封印裂口只容一线气息外泄，那气息古老而清醒，像在等待回应。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.broken-seal.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.broken-seal.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.broken-seal.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.broken-seal.title",
    "残封"
  ],
  [
    "content01.risk.critical-crossing.body",
    "伤势未稳，河水又在上涨；此刻强渡，危险来自水势，也来自身体本身。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.critical-crossing.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.critical-crossing.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.critical-crossing.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.critical-crossing.title",
    "负伤渡河"
  ],
  [
    "content01.risk.curse-stone.body",
    "无字石碑在神识触及的一刻传来低语，像有人借你的记忆说话。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.curse-stone.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.curse-stone.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.curse-stone.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.curse-stone.title",
    "无字碑"
  ],
  [
    "content01.risk.falling-star.body",
    "夜空裂开一道暗红弧光，落点近得能感到地面轻震，远处鸟群尽数惊起。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.falling-star.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.falling-star.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.falling-star.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.falling-star.title",
    "坠星"
  ],
  [
    "content01.risk.flood-cave.body",
    "洞中水位正在上升，深处微光尚未消失，留给你判断的时间不多。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.flood-cave.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.flood-cave.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.flood-cave.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.flood-cave.title",
    "涨水洞"
  ],
  [
    "content01.risk.pine-ambush.body",
    "松针忽然停止落下，前路有人藏住呼吸，退路也在一点点合拢。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.pine-ambush.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.pine-ambush.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.pine-ambush.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.pine-ambush.title",
    "松林伏影"
  ],
  [
    "content01.risk.poison-mist.body",
    "谷底升起淡青雾气，草叶边缘已经发黑，绕路要多耗数日。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.poison-mist.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.poison-mist.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.poison-mist.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.poison-mist.title",
    "青雾"
  ],
  [
    "content01.risk.revenge-shadow.body",
    "有人沿着旧日冲突留下的线索追来，来者不问解释，只确认你的名字。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.revenge-shadow.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.revenge-shadow.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.revenge-shadow.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.revenge-shadow.title",
    "旧怨追来"
  ],
  [
    "content01.risk.ruin-depth.body",
    "石阶向下延伸，壁灯早已熄灭，回声却比你的脚步多出一次。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.risk.ruin-depth.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.risk.ruin-depth.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.risk.ruin-depth.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.risk.ruin-depth.title",
    "遗迹深处"
  ],
  [
    "content01.road.conflict-echo.body",
    "同一条窄路上，你再次看见熟悉身影；当年的争执已经长出新的分量。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.road.conflict-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.road.conflict-echo.choice.engage",
    "顺势而行"
  ],
  [
    "content01.road.conflict-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.road.conflict-echo.title",
    "旧路再逢"
  ],
  [
    "content01.road.conflict.body",
    "狭窄山道只容一人先过，对面的修士不肯退，你也看不出他是否另有所图。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.road.conflict.choice.bind-1",
    "记下此争"
  ],
  [
    "content01.road.conflict.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.road.conflict.title",
    "窄路相争"
  ],
  [
    "content01.road.help.body",
    "同行的陌生修士在坡前力竭，他没有求救，只把行囊向身后挪了挪。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.road.help.choice.bind-1",
    "扶他一程"
  ],
  [
    "content01.road.help.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.road.help.title",
    "扶一程"
  ],
  [
    "content01.road.kindness-echo.body",
    "多年后雨又落下，一把伞从身侧递来；那张脸比记忆成熟，旧日一程仍被记得。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.road.kindness-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.road.kindness-echo.choice.engage",
    "顺势而行"
  ],
  [
    "content01.road.kindness-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.road.kindness-echo.title",
    "故人递伞"
  ],
  [
    "content01.xie.cave-gamble.body",
    "洞口吹出的风带着金石气，谢听潮判断里面有路，也坦言判断可能错。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xie.cave-gamble.choice.read-signs",
    "先辨征兆"
  ],
  [
    "content01.xie.cave-gamble.choice.take-risk",
    "承担此险"
  ],
  [
    "content01.xie.cave-gamble.choice.turn-away",
    "及时折返"
  ],
  [
    "content01.xie.cave-gamble.title",
    "洞口风声"
  ],
  [
    "content01.xie.divided-spoils.body",
    "所得不如预想，谢听潮仍按旧话分成，只把最后一件用途不明的东西留在中央。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xie.divided-spoils.choice.consider",
    "停步细看"
  ],
  [
    "content01.xie.divided-spoils.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.xie.divided-spoils.choice.leave",
    "见好便收"
  ],
  [
    "content01.xie.divided-spoils.title",
    "分利"
  ],
  [
    "content01.xie.map-echo.body",
    "秘图旧折痕与眼前山势重合，谢听潮没有催你，只把当初说过的话轻轻念了一遍。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xie.map-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.xie.map-echo.choice.engage",
    "依此磨炼"
  ],
  [
    "content01.xie.map-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.xie.map-echo.title",
    "图上旧折"
  ],
  [
    "content01.xie.secret-map.body",
    "谢听潮摊开半张秘图，另一半仍在袖中。他愿意分路，也要求先说清如何分利。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xie.secret-map.choice.bind-1",
    "立约同行"
  ],
  [
    "content01.xie.secret-map.choice.bind-2",
    "暗留后手"
  ],
  [
    "content01.xie.secret-map.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.xie.secret-map.title",
    "半张秘图"
  ],
  [
    "content01.xu.empty-courtyard.body",
    "院门仍旧，檐下却积了厚灰。邻人只说许长安早已离开，没有人知道他最后去了哪里。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xu.empty-courtyard.choice.consider",
    "停步细看"
  ],
  [
    "content01.xu.empty-courtyard.choice.engage",
    "顺势而行"
  ],
  [
    "content01.xu.empty-courtyard.choice.leave",
    "见好便收"
  ],
  [
    "content01.xu.empty-courtyard.title",
    "空院"
  ],
  [
    "content01.xu.mortal-letter.body",
    "许长安托人送来一封短笺，问的不是仙途，只是你是否还记得旧日门前那棵树。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xu.mortal-letter.choice.bind-1",
    "答应归去"
  ],
  [
    "content01.xu.mortal-letter.choice.decline",
    "留一句话离开"
  ],
  [
    "content01.xu.mortal-letter.title",
    "人间来信"
  ],
  [
    "content01.xu.promise-echo.body",
    "旧树又添一圈年轮，你终于站回门前；许长安是否还在，已不再是唯一的问题。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xu.promise-echo.choice.consider",
    "停步细看"
  ],
  [
    "content01.xu.promise-echo.choice.engage",
    "顺势而行"
  ],
  [
    "content01.xu.promise-echo.choice.leave",
    "见好便收"
  ],
  [
    "content01.xu.promise-echo.title",
    "树下旧诺"
  ],
  [
    "content01.xu.ten-year-return.body",
    "你眼中的数次闭关，已是许长安鬓边的一层霜。他仍认得你，也不假装岁月轻巧。你可以顺势而行，也可以停下来辨清代价；此刻的取舍不会喧哗，却会在往后的年月留下形状。"
  ],
  [
    "content01.xu.ten-year-return.choice.consider",
    "停步细看"
  ],
  [
    "content01.xu.ten-year-return.choice.engage",
    "顺势而行"
  ],
  [
    "content01.xu.ten-year-return.choice.leave",
    "见好便收"
  ],
  [
    "content01.xu.ten-year-return.title",
    "十年重逢"
  ]
];
